# Generated by tools/gen_bodylib.py — the peephole whole-proc
# replacement library ("the cheat"). Do not edit bodies by hand;
# refresh via ARKHAM_BODYFP=1 + distillator splice, see peephole.nim.

type
  BodyEntry* = object
    name*: string     ## basename, diagnostics only
    arch*: string     ## "x64"/"a64": the target the body is machine code for.
                      ## Fingerprints are taken over the finished per-target
                      ## asm-NIF so they cannot collide across targets, but a
                      ## body splice is target machine code and the gate is
                      ## stated, not inferred.
    fp*: uint64       ## structural fingerprint of the ORIGINAL body
    toks*: int        ## its node count (cheap second key)
    body*: string     ## `(stmts (lenient) …)` replacement text

const BodyLib* = [
  BodyEntry(name: "mmIkj64", arch: "x64", fp: 0x463DE392173A0CA4'u64, toks: 651,
    body: """(stmts (lenient)
  (stmts
   (push
    (rcx))
   (push
    (rdx))
   (push
    (rsi))
   (push
    (rdi))
   (push
    (r8))
   (push
    (r9))
   (sub
    (rsp)64)
   (movdqu
    (mem
     (rsp))
    (xmm0))
   (movdqu
    (mem
     (rsp)16)
    (xmm1))
   (movdqu
    (mem
     (rsp)32)
    (xmm2))
   (movdqu
    (mem
     (rsp)48)
    (xmm3))
   (mov
    (rax)
    (r9))
   (push
    (r15))
   (mov
    (r15)
    (r8))
   (push
    (r14))
   (imul
    (rax)
    (r9))
   (push
    (r13))
   (push
    (r12))
   (mov
    (r12)
    (rdx))
   (push
    (rbp))
   (mov
    (rbp)
    (rdi))
   (push
    (rbx))
   (mov
    (rbx)
    (r9))
   (sub
    (rsp)56)
   (test
    (rax)
    (rax))
   (je L0.0)
   (mov
    (rdi)
    (mem
     (rdi)8))
   (mov
    (rdx)
    (rax))
   (shl
    (rdx)3)
   (mov
    (rsi)0)
   (mov (rax) 0)
   (mov (rcx) (rdx))
   (shr (rcx) 3)
   (repstosq)
   (mov (rcx) (rdx))
   (and (rcx) 7)
   (repstosb)
   (lab :L0.0)
   (test
    (rbx)
    (rbx))
   (jle L1.0)
   (mov
    (rax)
    (mem
     (rbp)8))
   (lea
    (rsi)
    (r15)8)
   (mov
    (r14)
    (rbx))
   (mov
    (rdi)0)
   (mov
    (mem
     (rsp)40)
    (rsi))
   (mov
    (rsi)
    (rbx))
   (mov
    (r9)
    (rbx))
   (shl
    (r9)3)
   (and
    (r14)-2)
   (mov
    (mem
     (rsp)32)
    (rax))
   (shr
    (rsi)1)
   (add
    (r12)
    (r9))
   (mov
    (rbp)
    (rax))
   (add
    (rbp)
    (r9))
   (mov
    (mem
     (rsp)8)0)
   (shl
    (rsi)4)
   (lab :L9.0)
   (mov
    (r13)
    (mem
     (rsp)32))
   (mov
    (mem
     (rsp)24)
    (rdi))
   (mov
    (r8)
    (r12))
   (mov
    (rcx)
    (r15))
   (mov
    (r10)
    (mem
     (rsp)40))
   (sub
    (r8)
    (r9))
   (mov
    (r11)0)
   (mov
    (rdx)
    (rdi))
   (shl
    (rdx)3)
   (add
    (rdx)
    (r13))
   (mov
    (mem
     (rsp)16)
    (rdx))
   (mov
    (rdx)
    (r14))
   (add
    (rdx)
    (rdi))
   (lea
    (r13)
    (mem
     (r13)
     (rdx)8))
   (lab :L8.0)
   (movsd
    (xmm2)
    (mem
     (r8)))
   (cmp
    (rbx)1)
   (je L2.0)
   (cmp
    (r10)
    (rax))
   (je L2.0)
   (lab :L6.0)
   (movapd
    (xmm1)
    (xmm2))
   (mov
    (rdx)0)
   (punpcklqdq
    (xmm1)
    (xmm1))
   (lab :L3.0)
   (movdqu
    (xmm0)
    (mem
     (rcx)
     (rdx)1))
   (movdqu
    (xmm3)
    (mem
     (rax)
     (rdx)1))
   (mulpd
    (xmm0)
    (xmm1))
   (addpd
    (xmm0)
    (xmm3))
   (movdqu
    (mem
     (rax)
     (rdx)1)
    (xmm0))
   (add
    (rdx)16)
   (cmp
    (rsi)
    (rdx))
   (jne L3.0)
   (test
    (cast
     (u 8)
     (rbx))1)
   (je L4.0)
   (mov
    (rdx)
    (r14))
   (add
    (rdx)
    (r11))
   (mulsd
    (xmm2)
    (mem
     (r15)
     (rdx)8))
   (addsd
    (xmm2)
    (mem
     (r13)))
   (movsd
    (mem
     (r13))
    (xmm2))
   (lab :L4.0)
   (add
    (r8)8)
   (cmp
    (r8)
    (r12))
   (je L5.0)
   (add
    (r10)
    (r9))
   (movsd
    (xmm2)
    (mem
     (r8)))
   (add
    (rcx)
    (r9))
   (add
    (r11)
    (rbx))
   (cmp
    (r10)
    (rax))
   (jne L6.0)
   (lab :L2.0)
   (mov
    (rdx)
    (mem
     (rsp)16))
   (mov
    (rdi)
    (rcx))
   (lab :L7.0)
   (movsd
    (xmm0)
    (mem
     (rdi)))
   (add
    (rdx)8)
   (add
    (rdi)8)
   (mulsd
    (xmm0)
    (xmm2))
   (addsd
    (xmm0)
    (mem
     (rdx)-8))
   (movsd
    (mem
     (rdx)-8)
    (xmm0))
   (cmp
    (rdx)
    (rbp))
   (jne L7.0)
   (add
    (r8)8)
   (add
    (rcx)
    (r9))
   (add
    (r11)
    (rbx))
   (add
    (r10)
    (r9))
   (cmp
    (r8)
    (r12))
   (jne L8.0)
   (lab :L5.0)
   (mov
    (rdi)
    (mem
     (rsp)24))
   (add
    (r12)
    (r9))
   (add
    (rax)
    (r9))
   (add
    (rbp)
    (r9))
   (add
    (mem
     (rsp)8)1)
   (add
    (rdi)
    (rbx))
   (cmp
    (rbx)
    (mem
     (rsp)8))
   (jne L9.0)
   (lab :L1.0)
   (add
    (rsp)56)
   (pop
    (rbx))
   (pop
    (rbp))
   (pop
    (r12))
   (pop
    (r13))
   (pop
    (r14))
   (pop
    (r15))
   (movdqu
    (xmm3)
    (mem
     (rsp)48))
   (movdqu
    (xmm2)
    (mem
     (rsp)32))
   (movdqu
    (xmm1)
    (mem
     (rsp)16))
   (movdqu
    (xmm0)
    (mem
     (rsp)))
   (add
    (rsp)64)
   (pop
    (r9))
   (pop
    (r8))
   (pop
    (rdi))
   (pop
    (rsi))
   (pop
    (rdx))
   (pop
    (rcx))
   (ret)))"""),
  BodyEntry(name: "mmTiled64", arch: "x64", fp: 0x2398FA3A855D56E5'u64, toks: 1085,
    body: """(stmts (lenient)
  (stmts
   (push
    (rcx))
   (push
    (rdx))
   (push
    (rsi))
   (push
    (rdi))
   (push
    (r8))
   (push
    (r9))
   (sub
    (rsp)64)
   (movdqu
    (mem
     (rsp))
    (xmm0))
   (movdqu
    (mem
     (rsp)16)
    (xmm1))
   (movdqu
    (mem
     (rsp)32)
    (xmm2))
   (movdqu
    (mem
     (rsp)48)
    (xmm3))
   (push
    (r15))
   (mov
    (rax)
    (r9))
   (push
    (r14))
   (imul
    (rax)
    (r9))
   (push
    (r13))
   (mov
    (r13)
    (r9))
   (push
    (r12))
   (push
    (rbp))
   (push
    (rbx))
   (mov
    (rbx)
    (rdx))
   (sub
    (rsp)184)
   (mov
    (mem
     (rsp)104)
    (rdi))
   (mov
    (mem
     (rsp))
    (r8))
   (test
    (rax)
    (rax))
   (je L0.0)
   (mov
    (rdi)
    (mem
     (rdi)8))
   (mov
    (rdx)
    (rax))
   (shl
    (rdx)3)
   (mov
    (rsi)0)
   (mov (rax) 0)
   (mov (rcx) (rdx))
   (shr (rcx) 3)
   (repstosq)
   (mov (rcx) (rdx))
   (and (rcx) 7)
   (repstosb)
   (lab :L0.0)
   (test
    (r13)
    (r13))
   (jle L1.0)
   (mov
    (rax)
    (mem
     (rsp)))
   (mov
    (r9)
    (r13))
   (mov
    (rsi)
    (r13))
   (mov
    (rcx)0)
   (shl
    (r9)5)
   (shl
    (rsi)8)
   (mov
    (r8)0)
   (mov
    (rdi)
    (rax))
   (lea
    (r14)
    (rax)8)
   (neg
    (rdi))
   (mov
    (mem
     (rsp)88)
    (rdi))
   (mov
    (rdi)
    (r13))
   (shl
    (rdi)3)
   (mov
    (mem
     (rsp)64)
    (rdi))
   (lab :L15.0)
   (mov
    (mem
     (rsp)96)
    (rcx))
   (mov
    (rdi)
    (rcx))
   (add
    (rcx)32)
   (cmp
    (r13)
    (rcx))
   (mov
    (rax)
    (rcx))
   (cmovle
    (rax)
    (r13))
   (mov
    (mem
     (rsp)56)
    (rax))
   (cmp
    (rax)
    (rdi))
   (jle L2.0)
   (mov
    (mem
     (rsp)40)0)
   (mov
    (r12)
    (r13))
   (mov
    (rax)0)
   (mov
    (r13)
    (r14))
   (lab :L14.0)
   (mov
    (rdx)
    (rax))
   (add
    (rax)32)
   (cmp
    (r12)
    (rax))
   (mov
    (r10)
    (rax))
   (cmovle
    (r10)
    (r12))
   (cmp
    (r10)
    (rdx))
   (jle L3.0)
   (sub
    (rdx)
    (r10))
   (mov
    (mem
     (rsp)112)
    (rcx))
   (mov
    (rdi)
    (r8))
   (add
    (rdi)
    (r10))
   (mov
    (r14)
    (mem
     (rsp)))
   (mov
    (mem
     (rsp)120)
    (rax))
   (shl
    (rdx)3)
   (shl
    (rdi)3)
   (add
    (rdi)
    (rbx))
   (mov
    (mem
     (rsp)128)
    (r9))
   (mov
    (mem
     (rsp)136)
    (rsi))
   (mov
    (mem
     (rsp)144)
    (rbx))
   (mov
    (mem
     (rsp)72)
    (rdx))
   (mov
    (rdx)0)
   (lab :L13.0)
   (mov
    (rax)
    (rdx))
   (mov
    (rbx)
    (rdx))
   (add
    (rdx)32)
   (cmp
    (r12)
    (rdx))
   (mov
    (r11)
    (rdx))
   (cmovle
    (r11)
    (r12))
   (cmp
    (r11)
    (rax))
   (jle L4.0)
   (mov
    (rsi)
    (mem
     (rsp)88))
   (mov
    (rcx)
    (mem
     (rsp)))
   (sub
    (r11)
    (rax))
   (mov
    (r9)
    (rdi))
   (mov
    (rbp)
    (r11))
   (mov
    (mem
     (rsp)16)
    (r8))
   (mov
    (r15)
    (rsi))
   (add
    (r15)
    (r14))
   (lea
    (rcx)
    (mem
     (rcx)
     (rax)8))
   (mov
    (rsi)
    (mem
     (rsp)104))
   (mov
    (mem
     (rsp)152)
    (rdi))
   (mov
    (mem
     (rsp)24)
    (rcx))
   (mov
    (rcx)
    (mem
     (rsp)96))
   (and
    (rbp)-2)
   (mov
    (rsi)
    (mem
     (rsi)8))
   (mov
    (mem
     (rsp)160)
    (rdx))
   (add
    (rbp)
    (rax))
   (mov
    (mem
     (rsp)8)
    (rcx))
   (mov
    (rcx)
    (r11))
   (mov
    (mem
     (rsp)48)
    (rsi))
   (lea
    (rsi)
    (mem
     (rsi)
     (r11)8))
   (shr
    (rcx)1)
   (mov
    (mem
     (rsp)80)
    (rsi))
   (shl
    (rcx)4)
   (mov
    (mem
     (rsp)168)
    (r8))
   (lab :L12.0)
   (mov
    (rax)
    (mem
     (rsp)72))
   (mov
    (r10)
    (mem
     (rsp)48))
   (mov
    (mem
     (rsp)32)
    (r15))
   (mov
    (rsi)
    (mem
     (rsp)40))
   (mov
    (rdi)
    (rax))
   (add
    (rdi)
    (r9))
   (mov
    (rax)
    (mem
     (rsp)80))
   (mov
    (rdx)
    (r15))
   (add
    (rdx)
    (r10))
   (mov
    (r8)
    (r15))
   (add
    (r8)
    (rax))
   (mov
    (rax)
    (mem
     (rsp)16))
   (add
    (rax)
    (rbp))
   (lea
    (r10)
    (mem
     (r10)
     (rax)8))
   (lab :L11.0)
   (movsd
    (xmm2)
    (mem
     (rdi)))
   (cmp
    (r11)1)
   (je L5.0)
   (mov
    (rax)
    (rsi))
   (add
    (rax)
    (rbx))
   (shl
    (rax)3)
   (add
    (rax)
    (r13))
   (cmp
    (rdx)
    (rax))
   (je L5.0)
   (lab :L9.0)
   (movapd
    (xmm1)
    (xmm2))
   (mov
    (r15)
    (rsi))
   (shl
    (r15)3)
   (add
    (r15)
    (r14))
   (mov
    (rax)0)
   (punpcklqdq
    (xmm1)
    (xmm1))
   (lab :L6.0)
   (movdqu
    (xmm0)
    (mem
     (r15)
     (rax)1))
   (movdqu
    (xmm3)
    (mem
     (rdx)
     (rax)1))
   (mulpd
    (xmm0)
    (xmm1))
   (addpd
    (xmm0)
    (xmm3))
   (movdqu
    (mem
     (rdx)
     (rax)1)
    (xmm0))
   (add
    (rax)16)
   (cmp
    (rax)
    (rcx))
   (jne L6.0)
   (test
    (cast
     (u 8)
     (r11))1)
   (je L7.0)
   (mov
    (r15)
    (mem
     (rsp)))
   (mov
    (rax)
    (rsi))
   (add
    (rax)
    (rbp))
   (mulsd
    (xmm2)
    (mem
     (r15)
     (rax)8))
   (addsd
    (xmm2)
    (mem
     (r10)))
   (movsd
    (mem
     (r10))
    (xmm2))
   (lab :L7.0)
   (add
    (rdi)8)
   (cmp
    (rdi)
    (r9))
   (je L8.0)
   (add
    (rsi)
    (r12))
   (movsd
    (xmm2)
    (mem
     (rdi)))
   (mov
    (rax)
    (rsi))
   (add
    (rax)
    (rbx))
   (shl
    (rax)3)
   (add
    (rax)
    (r13))
   (cmp
    (rdx)
    (rax))
   (jne L9.0)
   (lab :L5.0)
   (mov
    (rax)
    (mem
     (rsp)24))
   (mov
    (r15)
    (rsi))
   (shl
    (r15)3)
   (add
    (r15)
    (rax))
   (mov
    (rax)
    (rdx))
   (lab :L10.0)
   (movsd
    (xmm0)
    (mem
     (r15)))
   (add
    (rax)8)
   (add
    (r15)8)
   (mulsd
    (xmm0)
    (xmm2))
   (addsd
    (xmm0)
    (mem
     (rax)-8))
   (movsd
    (mem
     (rax)-8)
    (xmm0))
   (cmp
    (r8)
    (rax))
   (jne L10.0)
   (add
    (rdi)8)
   (add
    (rsi)
    (r12))
   (cmp
    (rdi)
    (r9))
   (jne L11.0)
   (lab :L8.0)
   (mov
    (rdi)
    (mem
     (rsp)64))
   (mov
    (r15)
    (mem
     (rsp)32))
   (add
    (mem
     (rsp)8)1)
   (mov
    (rax)
    (mem
     (rsp)8))
   (add
    (mem
     (rsp)16)
    (r12))
   (add
    (r9)
    (rdi))
   (add
    (r15)
    (rdi))
   (cmp
    (mem
     (rsp)56)
    (rax))
   (jne L12.0)
   (mov
    (rdi)
    (mem
     (rsp)152))
   (mov
    (rdx)
    (mem
     (rsp)160))
   (mov
    (r8)
    (mem
     (rsp)168))
   (lab :L4.0)
   (add
    (r14)256)
   (cmp
    (r12)
    (rdx))
   (jg L13.0)
   (mov
    (rcx)
    (mem
     (rsp)112))
   (mov
    (rax)
    (mem
     (rsp)120))
   (mov
    (r9)
    (mem
     (rsp)128))
   (mov
    (rsi)
    (mem
     (rsp)136))
   (mov
    (rbx)
    (mem
     (rsp)144))
   (lab :L3.0)
   (add
    (mem
     (rsp)40)
    (r9))
   (cmp
    (r12)
    (rax))
   (jg L14.0)
   (mov
    (r14)
    (r13))
   (mov
    (r13)
    (r12))
   (lab :L2.0)
   (add
    (mem
     (rsp)88)
    (rsi))
   (add
    (r8)
    (r9))
   (cmp
    (r13)
    (rcx))
   (jg L15.0)
   (lab :L1.0)
   (add
    (rsp)184)
   (pop
    (rbx))
   (pop
    (rbp))
   (pop
    (r12))
   (pop
    (r13))
   (pop
    (r14))
   (pop
    (r15))
   (movdqu
    (xmm3)
    (mem
     (rsp)48))
   (movdqu
    (xmm2)
    (mem
     (rsp)32))
   (movdqu
    (xmm1)
    (mem
     (rsp)16))
   (movdqu
    (xmm0)
    (mem
     (rsp)))
   (add
    (rsp)64)
   (pop
    (r9))
   (pop
    (r8))
   (pop
    (rdi))
   (pop
    (rsi))
   (pop
    (rdx))
   (pop
    (rcx))
   (ret)))"""),
  BodyEntry(name: "mmIkj32", arch: "x64", fp: 0xAF7F47E702A29AE0'u64, toks: 651,
    body: """(stmts (lenient)
  (stmts
   (push
    (rcx))
   (push
    (rdx))
   (push
    (rsi))
   (push
    (rdi))
   (push
    (r8))
   (push
    (r9))
   (sub
    (rsp)64)
   (movdqu
    (mem
     (rsp))
    (xmm0))
   (movdqu
    (mem
     (rsp)16)
    (xmm1))
   (movdqu
    (mem
     (rsp)32)
    (xmm2))
   (movdqu
    (mem
     (rsp)48)
    (xmm3))
   (push
    (r15))
   (mov
    (rax)
    (r9))
   (push
    (r14))
   (imul
    (rax)
    (r9))
   (mov
    (r14)
    (rdx))
   (push
    (r13))
   (push
    (r12))
   (push
    (rbp))
   (mov
    (rbp)
    (rdi))
   (push
    (rbx))
   (mov
    (rbx)
    (r9))
   (sub
    (rsp)72)
   (mov
    (mem
     (rsp)32)
    (r8))
   (test
    (rax)
    (rax))
   (je L0.0)
   (mov
    (rdi)
    (mem
     (rdi)8))
   (mov
    (rdx)
    (rax))
   (shl
    (rdx)2)
   (mov
    (rsi)0)
   (mov (rax) 0)
   (mov (rcx) (rdx))
   (shr (rcx) 3)
   (repstosq)
   (mov (rcx) (rdx))
   (and (rcx) 7)
   (repstosb)
   (lab :L0.0)
   (test
    (rbx)
    (rbx))
   (jle L1.0)
   (mov
    (r13)
    (mem
     (rbp)8))
   (mov
    (rcx)
    (rbx))
   (mov
    (r15)0)
   (mov
    (r8)0)
   (mov
    (rbp)
    (rbx))
   (shl
    (rbp)2)
   (mov
    (rdx)-4)
   (sub
    (rdx)
    (mem
     (rsp)32))
   (shr
    (rcx)2)
   (mov
    (rax)
    (r14))
   (add
    (rax)
    (rbp))
   (mov
    (mem
     (rsp)56)
    (rdx))
   (mov
    (r12)
    (r13))
   (add
    (r12)
    (rbp))
   (shl
    (rcx)4)
   (mov
    (mem
     (rsp))
    (rax))
   (lea
    (rax)
    (rbx)-1)
   (mov
    (mem
     (rsp)8)
    (rax))
   (mov
    (rax)
    (r13))
   (lab :L12.0)
   (mov
    (r10)
    (mem
     (rsp)56))
   (mov
    (rsi)
    (r15))
   (shl
    (rsi)2)
   (mov
    (rdx)
    (mem
     (rsp)32))
   (mov
    (r9)0)
   (mov
    (mem
     (rsp)48)
    (r8))
   (mov
    (rdi)
    (rsi))
   (add
    (rdi)
    (r14))
   (mov
    (r8)
    (r14))
   (mov
    (r14)
    (rsi))
   (add
    (r14)
    (r13))
   (add
    (r10)
    (rax))
   (lab :L11.0)
   (movss
    (xmm2)
    (cast
     (u 32)
     (mem
      (rdi))))
   (cmp
    (rbx)1)
   (je L2.0)
   (mov
    (mem
     (rsp)24)
    (r8))
   (mov
    (r8)
    (mem
     (rsp)32))
   (mov
    (mem
     (rsp)40)
    (r14))
   (mov
    (mem
     (rsp)16)
    (r12))
   (cmp
    (r10)8)
   (jbe L3.0)
   (lab :L9.0)
   (cmp
    (mem
     (rsp)8)2)
   (jbe L4.0)
   (movdqu
    (xmm1)
    (xmm2))
   (mov
    (rsi)0)
   (shufps
    (xmm1)
    (xmm1)0)
   (lab :L5.0)
   (movdqu
    (xmm0)
    (mem
     (rdx)
     (rsi)1))
   (movdqu
    (xmm3)
    (mem
     (rax)
     (rsi)1))
   (mulps
    (xmm0)
    (xmm1))
   (addps
    (xmm0)
    (xmm3))
   (movdqu
    (mem
     (rax)
     (rsi)1)
    (xmm0))
   (add
    (rsi)16)
   (cmp
    (rcx)
    (rsi))
   (jne L5.0)
   (mov
    (rsi)
    (rbx))
   (and
    (rsi)-4)
   (mov
    (r11)
    (rsi))
   (cmp
    (rsi)
    (rbx))
   (je L6.0)
   (mov
    (r12)
    (rbx))
   (sub
    (r12)
    (rsi))
   (cmp
    (r12)1)
   (je L7.0)
   (lab :L14.0)
   (mov
    (r14)
    (r11))
   (add
    (r14)
    (r15))
   (add
    (r11)
    (r9))
   (movdqu
    (xmm1)
    (xmm2))
   (movsd
    (xmm0)
    (mem
     (r8)
     (r11)4))
   (shufps
    (xmm1)
    (xmm1)224)
   (movfq
    (xmm1)
    (xmm1))
   (mulps
    (xmm0)
    (xmm1))
   (movsd
    (xmm1)
    (mem
     (r13)
     (r14)4))
   (movfq
    (xmm0)
    (xmm0))
   (addps
    (xmm0)
    (xmm1))
   (movsd
    (mem
     (r13)
     (r14)4)
    (xmm0))
   (test
    (cast
     (u 8)
     (r12))1)
   (je L6.0)
   (and
    (r12)-2)
   (add
    (rsi)
    (r12))
   (lab :L7.0)
   (mov
    (r11)
    (rsi))
   (add
    (r11)
    (r15))
   (add
    (rsi)
    (r9))
   (mulss
    (xmm2)
    (cast
     (u 32)
     (mem
      (r8)
      (rsi)4)))
   (addss
    (xmm2)
    (cast
     (u 32)
     (mem
      (r13)
      (r11)4)))
   (movss
    (cast
     (u 32)
     (mem
      (r13)
      (r11)4))
    (xmm2))
   (lab :L6.0)
   (add
    (rdi)4)
   (cmp
    (mem
     (rsp))
    (rdi))
   (je L8.0)
   (sub
    (r10)
    (rbp))
   (movss
    (xmm2)
    (cast
     (u 32)
     (mem
      (rdi))))
   (add
    (rdx)
    (rbp))
   (add
    (r9)
    (rbx))
   (cmp
    (r10)8)
   (ja L9.0)
   (lab :L3.0)
   (mov
    (r14)
    (mem
     (rsp)40))
   (mov
    (r12)
    (mem
     (rsp)16))
   (mov
    (r8)
    (mem
     (rsp)24))
   (lab :L2.0)
   (mov
    (r11)
    (rdx))
   (mov
    (rsi)
    (r14))
   (lab :L10.0)
   (movss
    (xmm0)
    (cast
     (u 32)
     (mem
      (r11))))
   (add
    (rsi)4)
   (add
    (r11)4)
   (mulss
    (xmm0)
    (xmm2))
   (addss
    (xmm0)
    (cast
     (u 32)
     (mem
      (rsi)-4)))
   (movss
    (cast
     (u 32)
     (mem
      (rsi)-4))
    (xmm0))
   (cmp
    (rsi)
    (r12))
   (jne L10.0)
   (add
    (rdi)4)
   (add
    (rdx)
    (rbp))
   (add
    (r9)
    (rbx))
   (sub
    (r10)
    (rbp))
   (cmp
    (rdi)
    (mem
     (rsp)))
   (jne L11.0)
   (mov
    (r14)
    (r8))
   (mov
    (r8)
    (mem
     (rsp)48))
   (lab :L13.0)
   (add
    (r8)1)
   (add
    (mem
     (rsp))
    (rbp))
   (add
    (rax)
    (rbp))
   (add
    (r15)
    (rbx))
   (add
    (r12)
    (rbp))
   (cmp
    (rbx)
    (r8))
   (jne L12.0)
   (lab :L1.0)
   (add
    (rsp)72)
   (pop
    (rbx))
   (pop
    (rbp))
   (pop
    (r12))
   (pop
    (r13))
   (pop
    (r14))
   (pop
    (r15))
   (movdqu
    (xmm3)
    (mem
     (rsp)48))
   (movdqu
    (xmm2)
    (mem
     (rsp)32))
   (movdqu
    (xmm1)
    (mem
     (rsp)16))
   (movdqu
    (xmm0)
    (mem
     (rsp)))
   (add
    (rsp)64)
   (pop
    (r9))
   (pop
    (r8))
   (pop
    (rdi))
   (pop
    (rsi))
   (pop
    (rdx))
   (pop
    (rcx))
   (ret)
   (lab :L8.0)
   (mov
    (r8)
    (mem
     (rsp)48))
   (mov
    (r12)
    (mem
     (rsp)16))
   (mov
    (r14)
    (mem
     (rsp)24))
   (jmp L13.0)
   (lab :L4.0)
   (mov
    (r12)
    (rbx))
   (mov
    (rsi)0)
   (mov
    (r11)0)
   (jmp L14.0)))"""),
  BodyEntry(name: "mmTiled32", arch: "x64", fp: 0x03BEB4CFA9AE62F9'u64, toks: 1085,
    body: """(stmts (lenient)
  (stmts
   (push
    (rcx))
   (push
    (rdx))
   (push
    (rsi))
   (push
    (rdi))
   (push
    (r8))
   (push
    (r9))
   (sub
    (rsp)64)
   (movdqu
    (mem
     (rsp))
    (xmm0))
   (movdqu
    (mem
     (rsp)16)
    (xmm1))
   (movdqu
    (mem
     (rsp)32)
    (xmm2))
   (movdqu
    (mem
     (rsp)48)
    (xmm3))
   (push
    (r15))
   (mov
    (rax)
    (r9))
   (push
    (r14))
   (imul
    (rax)
    (r9))
   (mov
    (r14)
    (r8))
   (push
    (r13))
   (mov
    (r13)
    (r9))
   (push
    (r12))
   (push
    (rbp))
   (mov
    (rbp)
    (rdx))
   (push
    (rbx))
   (sub
    (rsp)232)
   (mov
    (mem
     (rsp)144)
    (rdi))
   (test
    (rax)
    (rax))
   (je L0.0)
   (mov
    (rdi)
    (mem
     (rdi)8))
   (mov
    (rdx)
    (rax))
   (shl
    (rdx)2)
   (mov
    (rsi)0)
   (mov (rax) 0)
   (mov (rcx) (rdx))
   (shr (rcx) 3)
   (repstosq)
   (mov (rcx) (rdx))
   (and (rcx) 7)
   (repstosb)
   (lab :L0.0)
   (test
    (r13)
    (r13))
   (jle L1.0)
   (mov
    (rbx)
    (r13))
   (mov
    (rax)
    (r13))
   (mov
    (r15)
    (r13))
   (shl
    (r15)2)
   (mov
    (rcx)0)
   (mov
    (r13)
    (r14))
   (shl
    (rbx)5)
   (mov
    (r8)0)
   (mov
    (r10)
    (rbp))
   (mov
    (r14)
    (rax))
   (lab :L18.0)
   (mov
    (mem
     (rsp)136)
    (rcx))
   (mov
    (rsi)
    (rcx))
   (add
    (rcx)32)
   (cmp
    (r14)
    (rcx))
   (mov
    (rax)
    (rcx))
   (cmovle
    (rax)
    (r14))
   (mov
    (mem
     (rsp)112)
    (rax))
   (cmp
    (rax)
    (rsi))
   (jle L2.0)
   (mov
    (mem
     (rsp)104)0)
   (mov
    (rdx)0)
   (lab :L17.0)
   (mov
    (rax)
    (rdx))
   (add
    (rdx)32)
   (cmp
    (r14)
    (rdx))
   (mov
    (rsi)
    (rdx))
   (cmovle
    (rsi)
    (r14))
   (cmp
    (rsi)
    (rax))
   (jle L3.0)
   (sub
    (rax)
    (rsi))
   (mov
    (mem
     (rsp)152)
    (rcx))
   (mov
    (rdi)
    (r8))
   (add
    (rdi)
    (rsi))
   (mov
    (rsi)
    (r8))
   (shl
    (rax)2)
   (mov
    (mem
     (rsp)160)
    (rdx))
   (mov
    (r9)
    (rdi))
   (shl
    (r9)2)
   (add
    (r9)
    (r10))
   (mov
    (mem
     (rsp)120)
    (rax))
   (mov
    (rax)
    (mem
     (rsp)104))
   (mov
    (mem
     (rsp)168)
    (r8))
   (mov
    (mem
     (rsp)176)
    (rbx))
   (mov
    (rdi)
    (rax))
   (shl
    (rdi)2)
   (add
    (rdi)
    (r13))
   (mov
    (rax)0)
   (mov
    (mem
     (rsp)184)
    (r10))
   (lab :L16.0)
   (mov
    (mem
     (rsp)48)
    (rax))
   (mov
    (rcx)
    (rax))
   (mov
    (mem
     (rsp)40)
    (rax))
   (add
    (rax)32)
   (cmp
    (r14)
    (rax))
   (mov
    (rdx)
    (rax))
   (cmovle
    (rdx)
    (r14))
   (cmp
    (rdx)
    (rcx))
   (jle L4.0)
   (sub
    (rdx)
    (rcx))
   (mov
    (rbp)
    (rcx))
   (shl
    (rbp)2)
   (add
    (rbp)
    (rdi))
   (mov
    (mem
     (rsp)32)
    (rsi))
   (mov
    (r12)
    (r9))
   (mov
    (rbx)
    (mem
     (rsp)144))
   (lea
    (rcx)
    (rdx)-1)
   (mov
    (r11)
    (rdx))
   (mov
    (mem
     (rsp)16)
    (rdx))
   (mov
    (mem
     (rsp)24)
    (rcx))
   (and
    (r11)-4)
   (mov
    (rcx)
    (rdx))
   (mov
    (r8)
    (mem
     (rsp)136))
   (mov
    (rbx)
    (mem
     (rbx)8))
   (mov
    (mem
     (rsp)96)
    (r11))
   (shr
    (rcx)2)
   (mov
    (mem
     (rsp)128)
    (rbp))
   (shl
    (rcx)4)
   (mov
    (r10)
    (rdx))
   (shl
    (r10)2)
   (add
    (r10)
    (rbx))
   (and
    (cast
     (u 32)
     (rdx))3)
   (mov
    (mem
     (rsp)192)
    (r9))
   (mov
    (mem
     (rsp)56)
    (rdx))
   (mov
    (mem
     (rsp)200)
    (rax))
   (mov
    (mem
     (rsp)208)
    (rsi))
   (mov
    (mem
     (rsp)216)
    (rdi))
   (lab :L15.0)
   (mov
    (rax)
    (mem
     (rsp)32))
   (mov
    (r9)
    (mem
     (rsp)104))
   (mov
    (rbp)
    (r8))
   (mov
    (rdx)
    (mem
     (rsp)128))
   (mov
    (rsi)
    (rax))
   (sub
    (rsi)
    (mem
     (rsp)40))
   (mov
    (r11)
    (rax))
   (shl
    (r11)2)
   (mov
    (mem
     (rsp)64)
    (rsi))
   (mov
    (rsi)
    (mem
     (rsp)120))
   (mov
    (rax)
    (r11))
   (add
    (rax)
    (rbx))
   (add
    (r11)
    (r10))
   (add
    (rsi)
    (r12))
   (lab :L14.0)
   (movss
    (xmm2)
    (cast
     (u 32)
     (mem
      (rsi))))
   (cmp
    (mem
     (rsp)16)1)
   (je L5.0)
   (lea
    (r8)
    (rdx)4)
   (mov
    (rdi)
    (rax))
   (mov
    (mem
     (rsp)80)
    (r10))
   (mov
    (r10)
    (mem
     (rsp)96))
   (sub
    (rdi)
    (r8))
   (mov
    (mem
     (rsp)72)
    (rbp))
   (mov
    (mem
     (rsp)88)
    (r11))
   (cmp
    (rdi)8)
   (jbe L6.0)
   (lab :L12.0)
   (cmp
    (mem
     (rsp)24)2)
   (jbe L7.0)
   (movdqu
    (xmm1)
    (xmm2))
   (mov
    (rdi)0)
   (shufps
    (xmm1)
    (xmm1)0)
   (lab :L8.0)
   (movdqu
    (xmm0)
    (mem
     (rdx)
     (rdi)1))
   (movdqu
    (xmm3)
    (mem
     (rax)
     (rdi)1))
   (mulps
    (xmm0)
    (xmm1))
   (addps
    (xmm0)
    (xmm3))
   (movdqu
    (mem
     (rax)
     (rdi)1)
    (xmm0))
   (add
    (rdi)16)
   (cmp
    (rdi)
    (rcx))
   (jne L8.0)
   (test
    (cast
     (u 8)
     (mem
      (rsp)16))3)
   (je L9.0)
   (mov
    (r11)
    (mem
     (rsp)48))
   (mov
    (rbp)
    (mem
     (rsp)56))
   (mov
    (rdi)
    (r10))
   (mov
    (mem
     (rsp)8)
    (rbp))
   (mov
    (r8)
    (r11))
   (add
    (r8)
    (r10))
   (cmp
    (rbp)1)
   (je L10.0)
   (lab :L20.0)
   (mov
    (rbp)
    (mem
     (rsp)32))
   (movdqu
    (xmm1)
    (xmm2))
   (shufps
    (xmm1)
    (xmm1)224)
   (movfq
    (xmm1)
    (xmm1))
   (add
    (rbp)
    (rdi))
   (add
    (rdi)
    (r9))
   (add
    (rdi)
    (mem
     (rsp)40))
   (movsd
    (xmm0)
    (mem
     (r13)
     (rdi)4))
   (mov
    (rdi)
    (mem
     (rsp)8))
   (mulps
    (xmm0)
    (xmm1))
   (movsd
    (xmm1)
    (mem
     (rbx)
     (rbp)4))
   (movfq
    (xmm0)
    (xmm0))
   (addps
    (xmm0)
    (xmm1))
   (movsd
    (mem
     (rbx)
     (rbp)4)
    (xmm0))
   (test
    (cast
     (u 8)
     (rdi))1)
   (je L9.0)
   (mov
    (r11)
    (rdi))
   (and
    (r11)-2)
   (add
    (r8)
    (r11))
   (lab :L10.0)
   (mov
    (rdi)
    (mem
     (rsp)64))
   (add
    (rdi)
    (r8))
   (add
    (r8)
    (r9))
   (mulss
    (xmm2)
    (cast
     (u 32)
     (mem
      (r13)
      (r8)4)))
   (addss
    (xmm2)
    (cast
     (u 32)
     (mem
      (rbx)
      (rdi)4)))
   (movss
    (cast
     (u 32)
     (mem
      (rbx)
      (rdi)4))
    (xmm2))
   (lab :L9.0)
   (add
    (rsi)4)
   (cmp
    (r12)
    (rsi))
   (je L11.0)
   (add
    (rdx)
    (r15))
   (mov
    (rdi)
    (rax))
   (movss
    (xmm2)
    (cast
     (u 32)
     (mem
      (rsi))))
   (add
    (r9)
    (r14))
   (lea
    (r8)
    (rdx)4)
   (sub
    (rdi)
    (r8))
   (cmp
    (rdi)8)
   (ja L12.0)
   (lab :L6.0)
   (mov
    (rbp)
    (mem
     (rsp)72))
   (mov
    (r11)
    (mem
     (rsp)88))
   (mov
    (r10)
    (mem
     (rsp)80))
   (lab :L5.0)
   (mov
    (r8)
    (rdx))
   (mov
    (rdi)
    (rax))
   (lab :L13.0)
   (movss
    (xmm0)
    (cast
     (u 32)
     (mem
      (r8))))
   (add
    (rdi)4)
   (add
    (r8)4)
   (mulss
    (xmm0)
    (xmm2))
   (addss
    (xmm0)
    (cast
     (u 32)
     (mem
      (rdi)-4)))
   (movss
    (cast
     (u 32)
     (mem
      (rdi)-4))
    (xmm0))
   (cmp
    (rdi)
    (r11))
   (jne L13.0)
   (add
    (rsi)4)
   (add
    (rdx)
    (r15))
   (add
    (r9)
    (r14))
   (cmp
    (r12)
    (rsi))
   (jne L14.0)
   (mov
    (r8)
    (rbp))
   (lab :L19.0)
   (add
    (mem
     (rsp)32)
    (r14))
   (add
    (r8)1)
   (add
    (r12)
    (r15))
   (cmp
    (mem
     (rsp)112)
    (r8))
   (jne L15.0)
   (mov
    (r9)
    (mem
     (rsp)192))
   (mov
    (rax)
    (mem
     (rsp)200))
   (mov
    (rsi)
    (mem
     (rsp)208))
   (mov
    (rdi)
    (mem
     (rsp)216))
   (lab :L4.0)
   (add
    (rsi)32)
   (cmp
    (r14)
    (rax))
   (jg L16.0)
   (mov
    (rcx)
    (mem
     (rsp)152))
   (mov
    (rdx)
    (mem
     (rsp)160))
   (mov
    (r8)
    (mem
     (rsp)168))
   (mov
    (rbx)
    (mem
     (rsp)176))
   (mov
    (r10)
    (mem
     (rsp)184))
   (lab :L3.0)
   (add
    (mem
     (rsp)104)
    (rbx))
   (cmp
    (r14)
    (rdx))
   (jg L17.0)
   (lab :L2.0)
   (add
    (r8)
    (rbx))
   (cmp
    (r14)
    (rcx))
   (jg L18.0)
   (lab :L1.0)
   (add
    (rsp)232)
   (pop
    (rbx))
   (pop
    (rbp))
   (pop
    (r12))
   (pop
    (r13))
   (pop
    (r14))
   (pop
    (r15))
   (movdqu
    (xmm3)
    (mem
     (rsp)48))
   (movdqu
    (xmm2)
    (mem
     (rsp)32))
   (movdqu
    (xmm1)
    (mem
     (rsp)16))
   (movdqu
    (xmm0)
    (mem
     (rsp)))
   (add
    (rsp)64)
   (pop
    (r9))
   (pop
    (r8))
   (pop
    (rdi))
   (pop
    (rsi))
   (pop
    (rdx))
   (pop
    (rcx))
   (ret)
   (lab :L11.0)
   (mov
    (r8)
    (mem
     (rsp)72))
   (mov
    (r10)
    (mem
     (rsp)80))
   (jmp L19.0)
   (lab :L7.0)
   (mov
    (rdi)
    (mem
     (rsp)16))
   (mov
    (r8)
    (mem
     (rsp)48))
   (mov
    (mem
     (rsp)8)
    (rdi))
   (mov
    (rdi)0)
   (jmp L20.0)))"""),
  BodyEntry(name: "mmIkj64", arch: "a64", fp: 0x1EB93D35953FC36C'u64, toks: 1394,
    body: """(stmts (lenient)
  (stmts
   (mov (x6) (mem (x0) 8))
   (lsl3 (x7) (x5) 3)
   (mul3 (x9) (x5) (x5))
   (lsl3 (x9) (x9) 3)
   (add3 (x9) (x6) (x9))
   (mov (x0) (x6))
   (veor (d0) (d0) (d0))
   (mov (x10) (x9))
   (sub (x10) 16)
   (lab :Lz16.0)
   (cmp (x0) (x10))
   (bhi Lz1.0)
   (fstrq (mem (x0)) (d0))
   (add (x0) 16)
   (b Lz16.0)
   (lab :Lz1.0)
   (cmp (x0) (x9))
   (bhs Lzd.0)
   (fstr (mem (x0)) (d0))
   (add (x0) 8)
   (b Lz1.0)
   (lab :Lzd.0)
   (mov (x1) (x5))
   (sub (x1) 4)
   (mov (x3) (x5))
   (sub (x3) 2)
   (mov (x8) 0)
   (mov (x9) (x6))
   (mov (x10) (x2))
   (lab :Li.0)
   (cmp (x8) (x5))
   (bge Ld.0)
   (mov (x11) 0)
   (mov (x12) (x4))
   (lab :Lk.0)
   (cmp (x11) (x5))
   (bge Lkd.0)
   (fldr (d1) (mem (x10)))
   (vdup (d1) (d1))
   (mov (x13) (x9))
   (mov (x14) (x12))
   (mov (x15) 0)
   (lab :Lv.0)
   (cmp (x15) (x1))
   (bgt Lp.0)
   (fldrq (d2) (mem (x14)))
   (fldrq (d3) (mem (x14) 16))
   (fldrq (d4) (mem (x13)))
   (fldrq (d5) (mem (x13) 16))
   (vfmla (d4) (d2) (d1))
   (vfmla (d5) (d3) (d1))
   (fstrq (mem (x13)) (d4))
   (fstrq (mem (x13) 16) (d5))
   (add (x14) 32)
   (add (x13) 32)
   (add (x15) 4)
   (b Lv.0)
   (lab :Lp.0)
   (cmp (x15) (x3))
   (bgt Ls.0)
   (fldrq (d2) (mem (x14)))
   (fldrq (d4) (mem (x13)))
   (vfmla (d4) (d2) (d1))
   (fstrq (mem (x13)) (d4))
   (add (x14) 16)
   (add (x13) 16)
   (add (x15) 2)
   (lab :Ls.0)
   (cmp (x15) (x5))
   (bge Lsd.0)
   (fldr (d2) (mem (x14)))
   (fmul (d2) (d1))
   (fldr (d3) (mem (x13)))
   (fadd (d3) (d2))
   (fstr (mem (x13)) (d3))
   (add (x14) 8)
   (add (x13) 8)
   (add (x15) 1)
   (b Ls.0)
   (lab :Lsd.0)
   (add (x10) 8)
   (add (x12) (x7))
   (add (x11) 1)
   (b Lk.0)
   (lab :Lkd.0)
   (add (x9) (x7))
   (add (x8) 1)
   (b Li.0)
   (lab :Ld.0)
   (ret)))"""),
  BodyEntry(name: "mmIkj32", arch: "a64", fp: 0xA5B2CEA35C6266A2'u64, toks: 1394,
    body: """(stmts (lenient)
  (stmts
   (mov (x6) (mem (x0) 8))
   (lsl3 (x7) (x5) 2)
   (mul3 (x9) (x5) (x5))
   (lsl3 (x9) (x9) 2)
   (add3 (x9) (x6) (x9))
   (mov (x0) (x6))
   (veor (s0) (s0) (s0))
   (mov (x10) (x9))
   (sub (x10) 16)
   (lab :Lz16.0)
   (cmp (x0) (x10))
   (bhi Lz1.0)
   (fstrq (mem (x0)) (s0))
   (add (x0) 16)
   (b Lz16.0)
   (lab :Lz1.0)
   (cmp (x0) (x9))
   (bhs Lzd.0)
   (fstr (mem (x0)) (s0))
   (add (x0) 4)
   (b Lz1.0)
   (lab :Lzd.0)
   (mov (x1) (x5))
   (sub (x1) 8)
   (mov (x3) (x5))
   (sub (x3) 4)
   (mov (x8) 0)
   (mov (x9) (x6))
   (mov (x10) (x2))
   (lab :Li.0)
   (cmp (x8) (x5))
   (bge Ld.0)
   (mov (x11) 0)
   (mov (x12) (x4))
   (lab :Lk.0)
   (cmp (x11) (x5))
   (bge Lkd.0)
   (fldr (s1) (mem (x10)))
   (vdup (s1) (s1))
   (mov (x13) (x9))
   (mov (x14) (x12))
   (mov (x15) 0)
   (lab :Lv.0)
   (cmp (x15) (x1))
   (bgt Lp.0)
   (fldrq (s2) (mem (x14)))
   (fldrq (s3) (mem (x14) 16))
   (fldrq (s4) (mem (x13)))
   (fldrq (s5) (mem (x13) 16))
   (vfmla (s4) (s2) (s1))
   (vfmla (s5) (s3) (s1))
   (fstrq (mem (x13)) (s4))
   (fstrq (mem (x13) 16) (s5))
   (add (x14) 32)
   (add (x13) 32)
   (add (x15) 8)
   (b Lv.0)
   (lab :Lp.0)
   (cmp (x15) (x3))
   (bgt Ls.0)
   (fldrq (s2) (mem (x14)))
   (fldrq (s4) (mem (x13)))
   (vfmla (s4) (s2) (s1))
   (fstrq (mem (x13)) (s4))
   (add (x14) 16)
   (add (x13) 16)
   (add (x15) 4)
   (lab :Ls.0)
   (cmp (x15) (x5))
   (bge Lsd.0)
   (fldr (s2) (mem (x14)))
   (fmul (s2) (s1))
   (fldr (s3) (mem (x13)))
   (fadd (s3) (s2))
   (fstr (mem (x13)) (s3))
   (add (x14) 4)
   (add (x13) 4)
   (add (x15) 1)
   (b Ls.0)
   (lab :Lsd.0)
   (add (x10) 4)
   (add (x12) (x7))
   (add (x11) 1)
   (b Lk.0)
   (lab :Lkd.0)
   (add (x9) (x7))
   (add (x8) 1)
   (b Li.0)
   (lab :Ld.0)
   (ret)))"""),
  BodyEntry(name: "mmTiled64", arch: "a64", fp: 0xD9FFB6F723B7F371'u64, toks: 1662,
    body: """(stmts (lenient)
  (stmts
   (mov (x6) (mem (x0) 8))
   (lsl3 (x7) (x5) 3)
   (mul3 (x9) (x5) (x5))
   (lsl3 (x9) (x9) 3)
   (add3 (x9) (x6) (x9))
   (mov (x0) (x6))
   (veor (d0) (d0) (d0))
   (mov (x10) (x9))
   (sub (x10) 16)
   (lab :Lz16.0)
   (cmp (x0) (x10))
   (bhi Lz1.0)
   (fstrq (mem (x0)) (d0))
   (add (x0) 16)
   (b Lz16.0)
   (lab :Lz1.0)
   (cmp (x0) (x9))
   (bhs Lzd.0)
   (fstr (mem (x0)) (d0))
   (add (x0) 8)
   (b Lz1.0)
   (lab :Lzd.0)
   (sub (sp) 48)
   (mov (x1) 0)
   (lab :Lii.0)
   (cmp (x1) (x5))
   (bge Ldone.0)
   (mov (x0) (x1))
   (add (x0) 32)
   (cmp (x0) (x5))
   (cselgt (x0) (x5) (x0))
   (mul3 (x0) (x0) (x7))
   (add3 (x0) (x2) (x0))
   (mov (mem (sp)) (x0))
   (mov (x3) 0)
   (lab :Lkk.0)
   (cmp (x3) (x5))
   (bge Liid.0)
   (lsl3 (x0) (x3) 3)
   (mov (mem (sp) 8) (x0))
   (mov (x0) (x3))
   (add (x0) 32)
   (cmp (x0) (x5))
   (cselgt (x0) (x5) (x0))
   (lsl3 (x0) (x0) 3)
   (mov (mem (sp) 16) (x0))
   (mov (x8) 0)
   (lab :Ljj.0)
   (cmp (x8) (x5))
   (bge Lkkd.0)
   (mov (x0) (x8))
   (add (x0) 32)
   (cmp (x0) (x5))
   (cselgt (x0) (x5) (x0))
   (sub3 (x11) (x0) (x8))
   (mov (x9) (x11))
   (sub (x9) 4)
   (mov (x10) (x11))
   (sub (x10) 2)
   (mul3 (x0) (x3) (x7))
   (add3 (x0) (x4) (x0))
   (lsl3 (x12) (x8) 3)
   (add3 (x0) (x0) (x12))
   (mov (mem (sp) 32) (x0))
   (mul3 (x0) (x1) (x7))
   (add3 (x13) (x2) (x0))
   (add3 (x12) (x6) (x0))
   (lsl3 (x0) (x8) 3)
   (add3 (x12) (x12) (x0))
   (lab :Li.0)
   (mov (x0) (mem (sp) 8))
   (add3 (x15) (x13) (x0))
   (mov (x14) (mem (sp) 32))
   (lab :Lk.0)
   (fldr (d1) (mem (x15)))
   (add (x15) 8)
   (vdup (d1) (d1))
   (mov (mem (sp) 24) (x15))
   (mov (x0) (x12))
   (mov (x15) 0)
   (lab :Lv.0)
   (cmp (x15) (x9))
   (bgt Lp.0)
   (fldrq (d2) (mem (x14)))
   (fldrq (d3) (mem (x14) 16))
   (fldrq (d4) (mem (x0)))
   (fldrq (d5) (mem (x0) 16))
   (vfmla (d4) (d2) (d1))
   (vfmla (d5) (d3) (d1))
   (fstrq (mem (x0)) (d4))
   (fstrq (mem (x0) 16) (d5))
   (add (x14) 32)
   (add (x0) 32)
   (add (x15) 4)
   (b Lv.0)
   (lab :Lp.0)
   (cmp (x15) (x10))
   (bgt Ls.0)
   (fldrq (d2) (mem (x14)))
   (fldrq (d4) (mem (x0)))
   (vfmla (d4) (d2) (d1))
   (fstrq (mem (x0)) (d4))
   (add (x14) 16)
   (add (x0) 16)
   (add (x15) 2)
   (lab :Ls.0)
   (cmp (x15) (x11))
   (bge Lsd.0)
   (fldr (d2) (mem (x14)))
   (fmul (d2) (d1))
   (fldr (d3) (mem (x0)))
   (fadd (d3) (d2))
   (fstr (mem (x0)) (d3))
   (add (x14) 8)
   (add (x0) 8)
   (add (x15) 1)
   (b Ls.0)
   (lab :Lsd.0)
   (lsl3 (x0) (x11) 3)
   (sub3 (x14) (x14) (x0))
   (add (x14) (x7))
   (mov (x15) (mem (sp) 24))
   (mov (x0) (mem (sp) 16))
   (add3 (x0) (x13) (x0))
   (cmp (x15) (x0))
   (blo Lk.0)
   (add (x13) (x7))
   (add (x12) (x7))
   (mov (x0) (mem (sp)))
   (cmp (x13) (x0))
   (blo Li.0)
   (add (x8) 32)
   (b Ljj.0)
   (lab :Lkkd.0)
   (add (x3) 32)
   (b Lkk.0)
   (lab :Liid.0)
   (add (x1) 32)
   (b Lii.0)
   (lab :Ldone.0)
   (add (sp) 48)
   (ret)))"""),
  BodyEntry(name: "mmTiled32", arch: "a64", fp: 0x25FF8591444D4405'u64, toks: 1662,
    body: """(stmts (lenient)
  (stmts
   (mov (x6) (mem (x0) 8))
   (lsl3 (x7) (x5) 2)
   (mul3 (x9) (x5) (x5))
   (lsl3 (x9) (x9) 2)
   (add3 (x9) (x6) (x9))
   (mov (x0) (x6))
   (veor (s0) (s0) (s0))
   (mov (x10) (x9))
   (sub (x10) 16)
   (lab :Lz16.0)
   (cmp (x0) (x10))
   (bhi Lz1.0)
   (fstrq (mem (x0)) (s0))
   (add (x0) 16)
   (b Lz16.0)
   (lab :Lz1.0)
   (cmp (x0) (x9))
   (bhs Lzd.0)
   (fstr (mem (x0)) (s0))
   (add (x0) 4)
   (b Lz1.0)
   (lab :Lzd.0)
   (sub (sp) 48)
   (mov (x1) 0)
   (lab :Lii.0)
   (cmp (x1) (x5))
   (bge Ldone.0)
   (mov (x0) (x1))
   (add (x0) 32)
   (cmp (x0) (x5))
   (cselgt (x0) (x5) (x0))
   (mul3 (x0) (x0) (x7))
   (add3 (x0) (x2) (x0))
   (mov (mem (sp)) (x0))
   (mov (x3) 0)
   (lab :Lkk.0)
   (cmp (x3) (x5))
   (bge Liid.0)
   (lsl3 (x0) (x3) 2)
   (mov (mem (sp) 8) (x0))
   (mov (x0) (x3))
   (add (x0) 32)
   (cmp (x0) (x5))
   (cselgt (x0) (x5) (x0))
   (lsl3 (x0) (x0) 2)
   (mov (mem (sp) 16) (x0))
   (mov (x8) 0)
   (lab :Ljj.0)
   (cmp (x8) (x5))
   (bge Lkkd.0)
   (mov (x0) (x8))
   (add (x0) 32)
   (cmp (x0) (x5))
   (cselgt (x0) (x5) (x0))
   (sub3 (x11) (x0) (x8))
   (mov (x9) (x11))
   (sub (x9) 8)
   (mov (x10) (x11))
   (sub (x10) 4)
   (mul3 (x0) (x3) (x7))
   (add3 (x0) (x4) (x0))
   (lsl3 (x12) (x8) 2)
   (add3 (x0) (x0) (x12))
   (mov (mem (sp) 32) (x0))
   (mul3 (x0) (x1) (x7))
   (add3 (x13) (x2) (x0))
   (add3 (x12) (x6) (x0))
   (lsl3 (x0) (x8) 2)
   (add3 (x12) (x12) (x0))
   (lab :Li.0)
   (mov (x0) (mem (sp) 8))
   (add3 (x15) (x13) (x0))
   (mov (x14) (mem (sp) 32))
   (lab :Lk.0)
   (fldr (s1) (mem (x15)))
   (add (x15) 4)
   (vdup (s1) (s1))
   (mov (mem (sp) 24) (x15))
   (mov (x0) (x12))
   (mov (x15) 0)
   (lab :Lv.0)
   (cmp (x15) (x9))
   (bgt Lp.0)
   (fldrq (s2) (mem (x14)))
   (fldrq (s3) (mem (x14) 16))
   (fldrq (s4) (mem (x0)))
   (fldrq (s5) (mem (x0) 16))
   (vfmla (s4) (s2) (s1))
   (vfmla (s5) (s3) (s1))
   (fstrq (mem (x0)) (s4))
   (fstrq (mem (x0) 16) (s5))
   (add (x14) 32)
   (add (x0) 32)
   (add (x15) 8)
   (b Lv.0)
   (lab :Lp.0)
   (cmp (x15) (x10))
   (bgt Ls.0)
   (fldrq (s2) (mem (x14)))
   (fldrq (s4) (mem (x0)))
   (vfmla (s4) (s2) (s1))
   (fstrq (mem (x0)) (s4))
   (add (x14) 16)
   (add (x0) 16)
   (add (x15) 4)
   (lab :Ls.0)
   (cmp (x15) (x11))
   (bge Lsd.0)
   (fldr (s2) (mem (x14)))
   (fmul (s2) (s1))
   (fldr (s3) (mem (x0)))
   (fadd (s3) (s2))
   (fstr (mem (x0)) (s3))
   (add (x14) 4)
   (add (x0) 4)
   (add (x15) 1)
   (b Ls.0)
   (lab :Lsd.0)
   (lsl3 (x0) (x11) 2)
   (sub3 (x14) (x14) (x0))
   (add (x14) (x7))
   (mov (x15) (mem (sp) 24))
   (mov (x0) (mem (sp) 16))
   (add3 (x0) (x13) (x0))
   (cmp (x15) (x0))
   (blo Lk.0)
   (add (x13) (x7))
   (add (x12) (x7))
   (mov (x0) (mem (sp)))
   (cmp (x13) (x0))
   (blo Li.0)
   (add (x8) 32)
   (b Ljj.0)
   (lab :Lkkd.0)
   (add (x3) 32)
   (b Lkk.0)
   (lab :Liid.0)
   (add (x1) 32)
   (b Lii.0)
   (lab :Ldone.0)
   (add (sp) 48)
   (ret)))"""),
]
