# Generated by tools/gen_instructions.nim from doc\nj.md. DO NOT EDIT!

type
  TagEnum* = enum
    InvalidTagId
    SufTagId
    AtTagId
    DerefTagId
    DotTagId
    PatTagId
    ParTagId
    AddrTagId
    NilTagId
    NotnilTagId
    InfTagId
    NeginfTagId
    NanTagId
    FalseTagId
    TrueTagId
    NotTagId
    NegTagId
    SizeofTagId
    AlignofTagId
    OffsetofTagId
    OconstrTagId
    AconstrTagId
    KvTagId
    VvTagId
    OvfTagId
    AddTagId
    SubTagId
    MulTagId
    DivTagId
    ModTagId
    ShrTagId
    ShlTagId
    BitandTagId
    BitorTagId
    BitxorTagId
    BitnotTagId
    EqTagId
    NeqTagId
    LeTagId
    LtTagId
    CastTagId
    ConvTagId
    CallTagId
    GvarTagId
    TvarTagId
    VarTagId
    ParamTagId
    ConstTagId
    ResultTagId
    FldTagId
    ProcTagId
    TypeTagId
    StoreTagId
    KeepovfTagId
    StmtsTagId
    ParamsTagId
    UnionTagId
    ObjectTagId
    ProctypeTagId
    AtomicTagId
    RoTagId
    RestrictTagId
    CpprefTagId
    ITagId
    UTagId
    FTagId
    CTagId
    BoolTagId
    VoidTagId
    PtrTagId
    ArrayTagId
    FlexarrayTagId
    AptrTagId
    CdeclTagId
    StdcallTagId
    SafecallTagId
    SyscallTagId
    FastcallTagId
    ThiscallTagId
    NoconvTagId
    MemberTagId
    NimcallTagId
    InlineTagId
    NoinlineTagId
    VarargsTagId
    WasTagId
    AlignTagId
    BitsTagId
    IteTagId
    ItecTagId
    LoopTagId
    VTagId
    UnknownTagId
    JtrueTagId
    CfvarTagId
    JoinTagId
    KillTagId
    PointerTagId
    DynlibTagId
    ExportcTagId
    ThreadvarTagId
    NoreturnTagId
    NoinitTagId
    RequiresTagId
    EnsuresTagId
    AssumeTagId
    AssertTagId
    AshrTagId
    BaseobjTagId
    AsmTagId
    PackedTagId
const
  TagData*: array[TagEnum, (string, int)] = [
    ("InvalidTagId", 0),
    ("suf", 1),
    ("at", 2),
    ("deref", 3),
    ("dot", 4),
    ("pat", 5),
    ("par", 6),
    ("addr", 7),
    ("nil", 8),
    ("notnil", 9),
    ("inf", 10),
    ("neginf", 11),
    ("nan", 12),
    ("false", 13),
    ("true", 14),
    ("not", 15),
    ("neg", 16),
    ("sizeof", 17),
    ("alignof", 18),
    ("offsetof", 19),
    ("oconstr", 20),
    ("aconstr", 21),
    ("kv", 22),
    ("vv", 23),
    ("ovf", 24),
    ("add", 25),
    ("sub", 26),
    ("mul", 27),
    ("div", 28),
    ("mod", 29),
    ("shr", 30),
    ("shl", 31),
    ("bitand", 32),
    ("bitor", 33),
    ("bitxor", 34),
    ("bitnot", 35),
    ("eq", 36),
    ("neq", 37),
    ("le", 38),
    ("lt", 39),
    ("cast", 40),
    ("conv", 41),
    ("call", 42),
    ("gvar", 43),
    ("tvar", 44),
    ("var", 45),
    ("param", 46),
    ("const", 47),
    ("result", 48),
    ("fld", 49),
    ("proc", 50),
    ("type", 51),
    ("store", 52),
    ("keepovf", 53),
    ("stmts", 54),
    ("params", 55),
    ("union", 56),
    ("object", 57),
    ("proctype", 58),
    ("atomic", 59),
    ("ro", 60),
    ("restrict", 61),
    ("cppref", 62),
    ("i", 63),
    ("u", 64),
    ("f", 65),
    ("c", 66),
    ("bool", 67),
    ("void", 68),
    ("ptr", 69),
    ("array", 70),
    ("flexarray", 71),
    ("aptr", 72),
    ("cdecl", 73),
    ("stdcall", 74),
    ("safecall", 75),
    ("syscall", 76),
    ("fastcall", 77),
    ("thiscall", 78),
    ("noconv", 79),
    ("member", 80),
    ("nimcall", 81),
    ("inline", 82),
    ("noinline", 83),
    ("varargs", 84),
    ("was", 85),
    ("align", 86),
    ("bits", 87),
    ("ite", 88),
    ("itec", 89),
    ("loop", 90),
    ("v", 91),
    ("unknown", 92),
    ("jtrue", 93),
    ("cfvar", 94),
    ("join", 95),
    ("kill", 96),
    ("pointer", 97),
    ("dynlib", 98),
    ("exportc", 99),
    ("threadvar", 100),
    ("noreturn", 101),
    ("noinit", 102),
    ("requires", 103),
    ("ensures", 104),
    ("assume", 105),
    ("assert", 106),
    ("ashr", 107),
    ("baseobj", 108),
    ("asm", 109),
    ("packed", 110)
  ]
