# Generated by tools/gen_instructions.nim from doc/instructions.md. DO NOT EDIT!

type
  TagEnum* = enum
    InvalidTagId
    AnonTagId
    BoolTagId
    NilTagId
    ITagId
    UTagId
    FTagId
    PtrTagId
    AptrTagId
    ArrayTagId
    TypeTagId
    ObjectTagId
    UnionTagId
    FldTagId
    PackedTagId
    ProcTagId
    ParamsTagId
    ParamTagId
    ResultTagId
    ClobberTagId
    VarTagId
    LayoutTagId
    FlashTagId
    SramTagId
    StartAddressTagId
    BytesTagId
    KilobytesTagId
    MegabytesTagId
    StacksTagId
    SlotsTagId
    HeapTagId
    NoinitTagId
    CoreTagId
    InterruptsTagId
    IrqTagId
    ArchTagId
    STagId
    AlignTagId
    SsizeTagId
    CsizeTagId
    DataloadTagId
    DatavmaTagId
    DatasizeTagId
    HeapstartTagId
    HeapsizeTagId
    NoinitstartTagId
    NoinitsizeTagId
    BsssizeTagId
    ArgTagId
    ResTagId
    LoTagId
    HiTagId
    PrepareTagId
    MovTagId
    LeaTagId
    AddTagId
    SubTagId
    MulTagId
    SdivTagId
    UdivTagId
    Add3TagId
    Sub3TagId
    Mul3TagId
    And3TagId
    Orr3TagId
    Eor3TagId
    Lsl3TagId
    Lsr3TagId
    Asr3TagId
    AddwTagId
    SubwTagId
    MulwTagId
    Addw3TagId
    Subw3TagId
    Mulw3TagId
    GloadTagId
    GstoreTagId
    AndTagId
    OrTagId
    OrrTagId
    XorTagId
    EorTagId
    LslTagId
    LsrTagId
    AsrTagId
    IncTagId
    DecTagId
    NegTagId
    NotTagId
    CmpTagId
    JmpTagId
    CallTagId
    ExtcallTagId
    TailcallTagId
    PopframeTagId
    RetTagId
    PushTagId
    PopTagId
    NopTagId
    AdrTagId
    LdrTagId
    StrTagId
    BTagId
    BlTagId
    BeqTagId
    BneTagId
    BltTagId
    BleTagId
    BgtTagId
    BgeTagId
    BloTagId
    BlsTagId
    BhiTagId
    BhsTagId
    CbzTagId
    CbnzTagId
    CselltTagId
    LabTagId
    IteTagId
    LoopTagId
    StmtsTagId
    CfvarTagId
    JtrueTagId
    DotTagId
    AtTagId
    MemTagId
    RodataTagId
    GvarTagId
    TvarTagId
    ImpTagId
    ExtprocTagId
    SyprocTagId
    KillTagId
    CastTagId
    RelocTagId
    RaxTagId
    RbxTagId
    RcxTagId
    RdxTagId
    RsiTagId
    RdiTagId
    RbpTagId
    RspTagId
    R8TagId
    R9TagId
    R10TagId
    R11TagId
    R12TagId
    R13TagId
    R14TagId
    R15TagId
    R0TagId
    R1TagId
    R2TagId
    R3TagId
    R4TagId
    R5TagId
    R6TagId
    R7TagId
    Xmm0TagId
    Xmm1TagId
    Xmm2TagId
    Xmm3TagId
    Xmm4TagId
    Xmm5TagId
    Xmm6TagId
    Xmm7TagId
    Xmm8TagId
    Xmm9TagId
    Xmm10TagId
    Xmm11TagId
    Xmm12TagId
    Xmm13TagId
    Xmm14TagId
    Xmm15TagId
    X0TagId
    X1TagId
    X2TagId
    X3TagId
    X4TagId
    X5TagId
    X6TagId
    X7TagId
    X8TagId
    X9TagId
    X10TagId
    X11TagId
    X12TagId
    X13TagId
    X14TagId
    X15TagId
    X16TagId
    X17TagId
    X18TagId
    X19TagId
    X20TagId
    X21TagId
    X22TagId
    X23TagId
    X24TagId
    X25TagId
    X26TagId
    X27TagId
    X28TagId
    X29TagId
    X30TagId
    SpTagId
    W0TagId
    W1TagId
    W2TagId
    W3TagId
    W4TagId
    W5TagId
    W6TagId
    W7TagId
    W8TagId
    W9TagId
    W10TagId
    W11TagId
    W12TagId
    W13TagId
    W14TagId
    W15TagId
    W16TagId
    W17TagId
    W18TagId
    W19TagId
    W20TagId
    W21TagId
    W22TagId
    W23TagId
    W24TagId
    W25TagId
    W26TagId
    W27TagId
    W28TagId
    W29TagId
    W30TagId
    WspTagId
    LrTagId
    FpTagId
    XzrTagId
    OfTagId
    NoTagId
    ZfTagId
    NzTagId
    SfTagId
    NsTagId
    CfTagId
    NcTagId
    PfTagId
    NpTagId
    CTagId
    VoidTagId
    VarargsTagId
    FlexarrayTagId
    EnumTagId
    EfldTagId
    ProctypeTagId
    DmbTagId
    ClrexTagId
    YieldTagId
    D0TagId
    D1TagId
    D2TagId
    D3TagId
    D4TagId
    D5TagId
    D6TagId
    D7TagId
    D8TagId
    D9TagId
    D10TagId
    D11TagId
    D12TagId
    D13TagId
    D14TagId
    D15TagId
    D16TagId
    D17TagId
    D18TagId
    D19TagId
    D20TagId
    D21TagId
    D22TagId
    D23TagId
    D24TagId
    D25TagId
    D26TagId
    D27TagId
    D28TagId
    D29TagId
    D30TagId
    D31TagId
    S0TagId
    S1TagId
    S2TagId
    S3TagId
    S4TagId
    S5TagId
    S6TagId
    S7TagId
    S8TagId
    S9TagId
    S10TagId
    S11TagId
    S12TagId
    S13TagId
    S14TagId
    S15TagId
    S16TagId
    S17TagId
    S18TagId
    S19TagId
    S20TagId
    S21TagId
    S22TagId
    S23TagId
    S24TagId
    S25TagId
    S26TagId
    S27TagId
    S28TagId
    S29TagId
    S30TagId
    S31TagId
    FmovTagId
    FaddTagId
    FsubTagId
    FmulTagId
    FdivTagId
    FnegTagId
    FcmpTagId
    FldrTagId
    FstrTagId
    ScvtfTagId
    UcvtfTagId
    FcvtzsTagId
    FcvtzuTagId
    LdrbTagId
    StrbTagId
    RebindTagId
    WithregTagId
    RegsTagId
    ScopeTagId
    ClzTagId
    RbitTagId
    RevTagId
    LenientTagId
    BkptTagId
    OtherTagId
    MovzxTagId
    MovsxTagId
    MovapdTagId
    MovsdTagId
    MovdquTagId
    ImulTagId
    DivTagId
    IdivTagId
    SmulhTagId
    UmulhTagId
    AddsdTagId
    SubsdTagId
    MulsdTagId
    DivsdTagId
    MovssTagId
    AddssTagId
    SubssTagId
    MulssTagId
    DivssTagId
    Cvtsi2sdTagId
    Cvtsi2ssTagId
    Cvttsd2siTagId
    Cvttss2siTagId
    Cvtsd2ssTagId
    Cvtss2sdTagId
    ComisdTagId
    ComissTagId
    MovfqTagId
    MovfdTagId
    ShlTagId
    ShrTagId
    SalTagId
    SarTagId
    RolTagId
    RorTagId
    RclTagId
    RcrTagId
    BsfTagId
    BsrTagId
    BtTagId
    BtsTagId
    BtrTagId
    BtcTagId
    TestTagId
    SeteTagId
    SetzTagId
    SetneTagId
    SetnzTagId
    SetaTagId
    SetnbeTagId
    SetaeTagId
    SetnbTagId
    SetncTagId
    SetbTagId
    SetnaeTagId
    SetcTagId
    SetbeTagId
    SetnaTagId
    SetgTagId
    SetnleTagId
    SetgeTagId
    SetnlTagId
    SetlTagId
    SetngeTagId
    SetleTagId
    SetngTagId
    SetoTagId
    SetsTagId
    SetpTagId
    CmoveTagId
    CmovzTagId
    CmovneTagId
    CmovnzTagId
    CmovaTagId
    CmovnbeTagId
    CmovaeTagId
    CmovnbTagId
    CmovncTagId
    CmovbTagId
    CmovnaeTagId
    CmovcTagId
    CmovbeTagId
    CmovnaTagId
    CmovgTagId
    CmovnleTagId
    CmovgeTagId
    CmovnlTagId
    CmovlTagId
    CmovngeTagId
    CmovleTagId
    CmovngTagId
    CmovoTagId
    CmovnoTagId
    CmovsTagId
    CmovnsTagId
    CmovpTagId
    CmovnpTagId
    CmovpeTagId
    CmovpoTagId
    JeTagId
    JzTagId
    JneTagId
    JnzTagId
    JgTagId
    JngTagId
    JgeTagId
    JngeTagId
    JaTagId
    JnaTagId
    JaeTagId
    JnaeTagId
    JlTagId
    JleTagId
    JbTagId
    JbeTagId
    JoTagId
    JnoTagId
    JpTagId
    IatTagId
    SyscallTagId
    SvcTagId
    StpTagId
    LdpTagId
    CseleqTagId
    CselneTagId
    CselleTagId
    CselgtTagId
    CselgeTagId
    CselloTagId
    CsellsTagId
    CselhiTagId
    CselhsTagId
    CseteqTagId
    CsetneTagId
    CsetltTagId
    CsetleTagId
    CsetgtTagId
    CsetgeTagId
    CsetloTagId
    CsetlsTagId
    CsethiTagId
    CsethsTagId
    LockTagId
    XchgTagId
    CmpxchgTagId
    XaddTagId
    Cmpxchg8bTagId
    MfenceTagId
    SfenceTagId
    LfenceTagId
    PauseTagId
    ClflushTagId
    ClflushoptTagId
    Prefetcht0TagId
    Prefetcht1TagId
    Prefetcht2TagId
    PrefetchntaTagId
    RepmovsbTagId
    RepmovswTagId
    RepmovsdTagId
    RepmovsqTagId
    LdaxrTagId
    StlxrTagId
    LdarTagId
    StlrTagId
    LdrexTagId
    StrexTagId
    FcvtTagId
    FstpTagId
    FldpTagId
    BswapTagId
    PopcntTagId
    CasejmpTagId
    JsTagId
    JnsTagId
    PunpcklqdqTagId
    MovupdTagId
    MovupsTagId
    AddpdTagId
    SubpdTagId
    MulpdTagId
    AddpsTagId
    SubpsTagId
    MulpsTagId
    ShufpsTagId
    RepstosbTagId
    RepstosqTagId
    FldrqTagId
    FstrqTagId
    VfaddTagId
    VfsubTagId
    VfmulTagId
    VfmlaTagId
    VdupTagId
    VeorTagId
    VaddvTagId
    VgreqTagId
    BxTagId
    BlxTagId
    MvnTagId
    Bic3TagId
    Adds3TagId
    Adcs3TagId
    Subs3TagId
    Sbcs3TagId
    MlsTagId
    UmullTagId
    SmullTagId
    TstTagId
    UxtbTagId
    SxtbTagId
    UxthTagId
    SxthTagId
    LdrhTagId
    StrhTagId
    LdrsbTagId
    LdrshTagId
    WfiTagId
    DsbTagId
    IsbTagId
    CsrwTagId
    CsrsTagId
    MretTagId
    LrwTagId
    ScwTagId
    SemihostTagId
    R16TagId
    R17TagId
    R18TagId
    R19TagId
    R20TagId
    R21TagId
    R22TagId
    R23TagId
    R24TagId
    R25TagId
    R26TagId
    R27TagId
    R28TagId
    R29TagId
    R30TagId
    R31TagId
    Rp0TagId
    Rp2TagId
    Rp4TagId
    Rp6TagId
    Rp8TagId
    Rp10TagId
    Rp12TagId
    Rp14TagId
    Rp16TagId
    Rp18TagId
    Rp20TagId
    Rp22TagId
    Rp24TagId
    Rp26TagId
    Rp28TagId
    Rp30TagId
    LdiTagId
    MovwTagId
    AdcTagId
    SbcTagId
    SubiTagId
    SbciTagId
    AndiTagId
    OriTagId
    CpiTagId
    CpcTagId
    CpseTagId
    AdiwTagId
    SbiwTagId
    Lsl1TagId
    Rol1TagId
    Lsr1TagId
    Ror1TagId
    Asr1TagId
    SwapTagId
    MulbTagId
    MulsbTagId
    LdbTagId
    StbTagId
    LdpiTagId
    StpiTagId
    InbTagId
    OutbTagId
    SbrcTagId
    SbrsTagId
    IcallTagId
    IjmpTagId
    RetiTagId
    SeiTagId
    CliTagId
    SleepTagId
    WdrTagId
    LpmTagId
    LpmpiTagId
const
  TagData*: array[TagEnum, (string, int)] = [
    ("InvalidTagId", 0),
    ("", 1),
    ("bool", 2),
    ("nil", 3),
    ("i", 4),
    ("u", 5),
    ("f", 6),
    ("ptr", 7),
    ("aptr", 8),
    ("array", 9),
    ("type", 10),
    ("object", 11),
    ("union", 12),
    ("fld", 13),
    ("packed", 14),
    ("proc", 15),
    ("params", 16),
    ("param", 17),
    ("result", 18),
    ("clobber", 19),
    ("var", 20),
    ("layout", 21),
    ("flash", 22),
    ("sram", 23),
    ("startAddress", 24),
    ("bytes", 25),
    ("kilobytes", 26),
    ("megabytes", 27),
    ("stacks", 28),
    ("slots", 29),
    ("heap", 30),
    ("noinit", 31),
    ("core", 32),
    ("interrupts", 33),
    ("irq", 34),
    ("arch", 35),
    ("s", 36),
    ("align", 37),
    ("ssize", 38),
    ("csize", 39),
    ("dataload", 40),
    ("datavma", 41),
    ("datasize", 42),
    ("heapstart", 43),
    ("heapsize", 44),
    ("noinitstart", 45),
    ("noinitsize", 46),
    ("bsssize", 47),
    ("arg", 48),
    ("res", 49),
    ("lo", 50),
    ("hi", 51),
    ("prepare", 52),
    ("mov", 53),
    ("lea", 54),
    ("add", 55),
    ("sub", 56),
    ("mul", 57),
    ("sdiv", 58),
    ("udiv", 59),
    ("add3", 60),
    ("sub3", 61),
    ("mul3", 62),
    ("and3", 63),
    ("orr3", 64),
    ("eor3", 65),
    ("lsl3", 66),
    ("lsr3", 67),
    ("asr3", 68),
    ("addw", 69),
    ("subw", 70),
    ("mulw", 71),
    ("addw3", 72),
    ("subw3", 73),
    ("mulw3", 74),
    ("gload", 75),
    ("gstore", 76),
    ("and", 77),
    ("or", 78),
    ("orr", 79),
    ("xor", 80),
    ("eor", 81),
    ("lsl", 82),
    ("lsr", 83),
    ("asr", 84),
    ("inc", 85),
    ("dec", 86),
    ("neg", 87),
    ("not", 88),
    ("cmp", 89),
    ("jmp", 90),
    ("call", 91),
    ("extcall", 92),
    ("tailcall", 93),
    ("popframe", 94),
    ("ret", 95),
    ("push", 96),
    ("pop", 97),
    ("nop", 98),
    ("adr", 99),
    ("ldr", 100),
    ("str", 101),
    ("b", 102),
    ("bl", 103),
    ("beq", 104),
    ("bne", 105),
    ("blt", 106),
    ("ble", 107),
    ("bgt", 108),
    ("bge", 109),
    ("blo", 110),
    ("bls", 111),
    ("bhi", 112),
    ("bhs", 113),
    ("cbz", 114),
    ("cbnz", 115),
    ("csellt", 116),
    ("lab", 117),
    ("ite", 118),
    ("loop", 119),
    ("stmts", 120),
    ("cfvar", 121),
    ("jtrue", 122),
    ("dot", 123),
    ("at", 124),
    ("mem", 125),
    ("rodata", 126),
    ("gvar", 127),
    ("tvar", 128),
    ("imp", 129),
    ("extproc", 130),
    ("syproc", 131),
    ("kill", 132),
    ("cast", 133),
    ("reloc", 134),
    ("rax", 135),
    ("rbx", 136),
    ("rcx", 137),
    ("rdx", 138),
    ("rsi", 139),
    ("rdi", 140),
    ("rbp", 141),
    ("rsp", 142),
    ("r8", 143),
    ("r9", 144),
    ("r10", 145),
    ("r11", 146),
    ("r12", 147),
    ("r13", 148),
    ("r14", 149),
    ("r15", 150),
    ("r0", 151),
    ("r1", 152),
    ("r2", 153),
    ("r3", 154),
    ("r4", 155),
    ("r5", 156),
    ("r6", 157),
    ("r7", 158),
    ("xmm0", 159),
    ("xmm1", 160),
    ("xmm2", 161),
    ("xmm3", 162),
    ("xmm4", 163),
    ("xmm5", 164),
    ("xmm6", 165),
    ("xmm7", 166),
    ("xmm8", 167),
    ("xmm9", 168),
    ("xmm10", 169),
    ("xmm11", 170),
    ("xmm12", 171),
    ("xmm13", 172),
    ("xmm14", 173),
    ("xmm15", 174),
    ("x0", 175),
    ("x1", 176),
    ("x2", 177),
    ("x3", 178),
    ("x4", 179),
    ("x5", 180),
    ("x6", 181),
    ("x7", 182),
    ("x8", 183),
    ("x9", 184),
    ("x10", 185),
    ("x11", 186),
    ("x12", 187),
    ("x13", 188),
    ("x14", 189),
    ("x15", 190),
    ("x16", 191),
    ("x17", 192),
    ("x18", 193),
    ("x19", 194),
    ("x20", 195),
    ("x21", 196),
    ("x22", 197),
    ("x23", 198),
    ("x24", 199),
    ("x25", 200),
    ("x26", 201),
    ("x27", 202),
    ("x28", 203),
    ("x29", 204),
    ("x30", 205),
    ("sp", 206),
    ("w0", 207),
    ("w1", 208),
    ("w2", 209),
    ("w3", 210),
    ("w4", 211),
    ("w5", 212),
    ("w6", 213),
    ("w7", 214),
    ("w8", 215),
    ("w9", 216),
    ("w10", 217),
    ("w11", 218),
    ("w12", 219),
    ("w13", 220),
    ("w14", 221),
    ("w15", 222),
    ("w16", 223),
    ("w17", 224),
    ("w18", 225),
    ("w19", 226),
    ("w20", 227),
    ("w21", 228),
    ("w22", 229),
    ("w23", 230),
    ("w24", 231),
    ("w25", 232),
    ("w26", 233),
    ("w27", 234),
    ("w28", 235),
    ("w29", 236),
    ("w30", 237),
    ("wsp", 238),
    ("lr", 239),
    ("fp", 240),
    ("xzr", 241),
    ("of", 242),
    ("no", 243),
    ("zf", 244),
    ("nz", 245),
    ("sf", 246),
    ("ns", 247),
    ("cf", 248),
    ("nc", 249),
    ("pf", 250),
    ("np", 251),
    ("c", 252),
    ("void", 253),
    ("varargs", 254),
    ("flexarray", 255),
    ("enum", 256),
    ("efld", 257),
    ("proctype", 258),
    ("dmb", 259),
    ("clrex", 260),
    ("yield", 261),
    ("d0", 262),
    ("d1", 263),
    ("d2", 264),
    ("d3", 265),
    ("d4", 266),
    ("d5", 267),
    ("d6", 268),
    ("d7", 269),
    ("d8", 270),
    ("d9", 271),
    ("d10", 272),
    ("d11", 273),
    ("d12", 274),
    ("d13", 275),
    ("d14", 276),
    ("d15", 277),
    ("d16", 278),
    ("d17", 279),
    ("d18", 280),
    ("d19", 281),
    ("d20", 282),
    ("d21", 283),
    ("d22", 284),
    ("d23", 285),
    ("d24", 286),
    ("d25", 287),
    ("d26", 288),
    ("d27", 289),
    ("d28", 290),
    ("d29", 291),
    ("d30", 292),
    ("d31", 293),
    ("s0", 294),
    ("s1", 295),
    ("s2", 296),
    ("s3", 297),
    ("s4", 298),
    ("s5", 299),
    ("s6", 300),
    ("s7", 301),
    ("s8", 302),
    ("s9", 303),
    ("s10", 304),
    ("s11", 305),
    ("s12", 306),
    ("s13", 307),
    ("s14", 308),
    ("s15", 309),
    ("s16", 310),
    ("s17", 311),
    ("s18", 312),
    ("s19", 313),
    ("s20", 314),
    ("s21", 315),
    ("s22", 316),
    ("s23", 317),
    ("s24", 318),
    ("s25", 319),
    ("s26", 320),
    ("s27", 321),
    ("s28", 322),
    ("s29", 323),
    ("s30", 324),
    ("s31", 325),
    ("fmov", 326),
    ("fadd", 327),
    ("fsub", 328),
    ("fmul", 329),
    ("fdiv", 330),
    ("fneg", 331),
    ("fcmp", 332),
    ("fldr", 333),
    ("fstr", 334),
    ("scvtf", 335),
    ("ucvtf", 336),
    ("fcvtzs", 337),
    ("fcvtzu", 338),
    ("ldrb", 339),
    ("strb", 340),
    ("rebind", 341),
    ("withreg", 342),
    ("regs", 343),
    ("scope", 344),
    ("clz", 345),
    ("rbit", 346),
    ("rev", 347),
    ("lenient", 348),
    ("bkpt", 349),
    ("other", 350),
    ("movzx", 351),
    ("movsx", 352),
    ("movapd", 353),
    ("movsd", 354),
    ("movdqu", 355),
    ("imul", 356),
    ("div", 357),
    ("idiv", 358),
    ("smulh", 359),
    ("umulh", 360),
    ("addsd", 361),
    ("subsd", 362),
    ("mulsd", 363),
    ("divsd", 364),
    ("movss", 365),
    ("addss", 366),
    ("subss", 367),
    ("mulss", 368),
    ("divss", 369),
    ("cvtsi2sd", 370),
    ("cvtsi2ss", 371),
    ("cvttsd2si", 372),
    ("cvttss2si", 373),
    ("cvtsd2ss", 374),
    ("cvtss2sd", 375),
    ("comisd", 376),
    ("comiss", 377),
    ("movfq", 378),
    ("movfd", 379),
    ("shl", 380),
    ("shr", 381),
    ("sal", 382),
    ("sar", 383),
    ("rol", 384),
    ("ror", 385),
    ("rcl", 386),
    ("rcr", 387),
    ("bsf", 388),
    ("bsr", 389),
    ("bt", 390),
    ("bts", 391),
    ("btr", 392),
    ("btc", 393),
    ("test", 394),
    ("sete", 395),
    ("setz", 396),
    ("setne", 397),
    ("setnz", 398),
    ("seta", 399),
    ("setnbe", 400),
    ("setae", 401),
    ("setnb", 402),
    ("setnc", 403),
    ("setb", 404),
    ("setnae", 405),
    ("setc", 406),
    ("setbe", 407),
    ("setna", 408),
    ("setg", 409),
    ("setnle", 410),
    ("setge", 411),
    ("setnl", 412),
    ("setl", 413),
    ("setnge", 414),
    ("setle", 415),
    ("setng", 416),
    ("seto", 417),
    ("sets", 418),
    ("setp", 419),
    ("cmove", 420),
    ("cmovz", 421),
    ("cmovne", 422),
    ("cmovnz", 423),
    ("cmova", 424),
    ("cmovnbe", 425),
    ("cmovae", 426),
    ("cmovnb", 427),
    ("cmovnc", 428),
    ("cmovb", 429),
    ("cmovnae", 430),
    ("cmovc", 431),
    ("cmovbe", 432),
    ("cmovna", 433),
    ("cmovg", 434),
    ("cmovnle", 435),
    ("cmovge", 436),
    ("cmovnl", 437),
    ("cmovl", 438),
    ("cmovnge", 439),
    ("cmovle", 440),
    ("cmovng", 441),
    ("cmovo", 442),
    ("cmovno", 443),
    ("cmovs", 444),
    ("cmovns", 445),
    ("cmovp", 446),
    ("cmovnp", 447),
    ("cmovpe", 448),
    ("cmovpo", 449),
    ("je", 450),
    ("jz", 451),
    ("jne", 452),
    ("jnz", 453),
    ("jg", 454),
    ("jng", 455),
    ("jge", 456),
    ("jnge", 457),
    ("ja", 458),
    ("jna", 459),
    ("jae", 460),
    ("jnae", 461),
    ("jl", 462),
    ("jle", 463),
    ("jb", 464),
    ("jbe", 465),
    ("jo", 466),
    ("jno", 467),
    ("jp", 468),
    ("iat", 469),
    ("syscall", 470),
    ("svc", 471),
    ("stp", 472),
    ("ldp", 473),
    ("cseleq", 474),
    ("cselne", 475),
    ("cselle", 476),
    ("cselgt", 477),
    ("cselge", 478),
    ("csello", 479),
    ("csells", 480),
    ("cselhi", 481),
    ("cselhs", 482),
    ("cseteq", 483),
    ("csetne", 484),
    ("csetlt", 485),
    ("csetle", 486),
    ("csetgt", 487),
    ("csetge", 488),
    ("csetlo", 489),
    ("csetls", 490),
    ("csethi", 491),
    ("cseths", 492),
    ("lock", 493),
    ("xchg", 494),
    ("cmpxchg", 495),
    ("xadd", 496),
    ("cmpxchg8b", 497),
    ("mfence", 498),
    ("sfence", 499),
    ("lfence", 500),
    ("pause", 501),
    ("clflush", 502),
    ("clflushopt", 503),
    ("prefetcht0", 504),
    ("prefetcht1", 505),
    ("prefetcht2", 506),
    ("prefetchnta", 507),
    ("repmovsb", 508),
    ("repmovsw", 509),
    ("repmovsd", 510),
    ("repmovsq", 511),
    ("ldaxr", 512),
    ("stlxr", 513),
    ("ldar", 514),
    ("stlr", 515),
    ("ldrex", 516),
    ("strex", 517),
    ("fcvt", 518),
    ("fstp", 519),
    ("fldp", 520),
    ("bswap", 521),
    ("popcnt", 522),
    ("casejmp", 523),
    ("js", 524),
    ("jns", 525),
    ("punpcklqdq", 526),
    ("movupd", 527),
    ("movups", 528),
    ("addpd", 529),
    ("subpd", 530),
    ("mulpd", 531),
    ("addps", 532),
    ("subps", 533),
    ("mulps", 534),
    ("shufps", 535),
    ("repstosb", 536),
    ("repstosq", 537),
    ("fldrq", 538),
    ("fstrq", 539),
    ("vfadd", 540),
    ("vfsub", 541),
    ("vfmul", 542),
    ("vfmla", 543),
    ("vdup", 544),
    ("veor", 545),
    ("vaddv", 546),
    ("vgreq", 547),
    ("bx", 548),
    ("blx", 549),
    ("mvn", 550),
    ("bic3", 551),
    ("adds3", 552),
    ("adcs3", 553),
    ("subs3", 554),
    ("sbcs3", 555),
    ("mls", 556),
    ("umull", 557),
    ("smull", 558),
    ("tst", 559),
    ("uxtb", 560),
    ("sxtb", 561),
    ("uxth", 562),
    ("sxth", 563),
    ("ldrh", 564),
    ("strh", 565),
    ("ldrsb", 566),
    ("ldrsh", 567),
    ("wfi", 568),
    ("dsb", 569),
    ("isb", 570),
    ("csrw", 571),
    ("csrs", 572),
    ("mret", 573),
    ("lrw", 574),
    ("scw", 575),
    ("semihost", 576),
    ("r16", 577),
    ("r17", 578),
    ("r18", 579),
    ("r19", 580),
    ("r20", 581),
    ("r21", 582),
    ("r22", 583),
    ("r23", 584),
    ("r24", 585),
    ("r25", 586),
    ("r26", 587),
    ("r27", 588),
    ("r28", 589),
    ("r29", 590),
    ("r30", 591),
    ("r31", 592),
    ("rp0", 593),
    ("rp2", 594),
    ("rp4", 595),
    ("rp6", 596),
    ("rp8", 597),
    ("rp10", 598),
    ("rp12", 599),
    ("rp14", 600),
    ("rp16", 601),
    ("rp18", 602),
    ("rp20", 603),
    ("rp22", 604),
    ("rp24", 605),
    ("rp26", 606),
    ("rp28", 607),
    ("rp30", 608),
    ("ldi", 609),
    ("movw", 610),
    ("adc", 611),
    ("sbc", 612),
    ("subi", 613),
    ("sbci", 614),
    ("andi", 615),
    ("ori", 616),
    ("cpi", 617),
    ("cpc", 618),
    ("cpse", 619),
    ("adiw", 620),
    ("sbiw", 621),
    ("lsl1", 622),
    ("rol1", 623),
    ("lsr1", 624),
    ("ror1", 625),
    ("asr1", 626),
    ("swap", 627),
    ("mulb", 628),
    ("mulsb", 629),
    ("ldb", 630),
    ("stb", 631),
    ("ldpi", 632),
    ("stpi", 633),
    ("inb", 634),
    ("outb", 635),
    ("sbrc", 636),
    ("sbrs", 637),
    ("icall", 638),
    ("ijmp", 639),
    ("reti", 640),
    ("sei", 641),
    ("cli", 642),
    ("sleep", 643),
    ("wdr", 644),
    ("lpm", 645),
    ("lpmpi", 646)
  ]
