# Generated by tools/gen_tags.nim from doc/instructions.md. DO NOT EDIT!

type
  TagEnum* = enum
    InvalidTagId
    BoolTagId
    ITagId
    UTagId
    FTagId
    PtrTagId
    AptrTagId
    ArrayTagId
    TypeTagId
    ObjectTagId
    UnionTagId
    FldTagId
    ProcTagId
    ParamsTagId
    ParamTagId
    ResultTagId
    ClobberTagId
    VarTagId
    ArchTagId
    STagId
    SsizeTagId
    CsizeTagId
    ArgTagId
    ResTagId
    PrepareTagId
    MovTagId
    LeaTagId
    MovapdTagId
    MovsdTagId
    AddTagId
    SubTagId
    MulTagId
    ImulTagId
    DivTagId
    IdivTagId
    SdivTagId
    UdivTagId
    AddsdTagId
    SubsdTagId
    MulsdTagId
    DivsdTagId
    AndTagId
    OrTagId
    OrrTagId
    XorTagId
    EorTagId
    ShlTagId
    LslTagId
    ShrTagId
    LsrTagId
    SalTagId
    SarTagId
    AsrTagId
    IncTagId
    DecTagId
    NegTagId
    NotTagId
    CmpTagId
    TestTagId
    SeteTagId
    SetzTagId
    SetneTagId
    SetnzTagId
    SetaTagId
    SetnbeTagId
    SetaeTagId
    SetnbTagId
    SetncTagId
    SetbTagId
    SetnaeTagId
    SetcTagId
    SetbeTagId
    SetnaTagId
    SetgTagId
    SetnleTagId
    SetgeTagId
    SetnlTagId
    SetlTagId
    SetngeTagId
    SetleTagId
    SetngTagId
    SetoTagId
    SetsTagId
    SetpTagId
    CmoveTagId
    CmovzTagId
    CmovneTagId
    CmovnzTagId
    CmovaTagId
    CmovnbeTagId
    CmovaeTagId
    CmovnbTagId
    CmovncTagId
    CmovbTagId
    CmovnaeTagId
    CmovcTagId
    CmovbeTagId
    CmovnaTagId
    CmovgTagId
    CmovnleTagId
    CmovgeTagId
    CmovnlTagId
    CmovlTagId
    CmovngeTagId
    CmovleTagId
    CmovngTagId
    CmovoTagId
    CmovnoTagId
    CmovsTagId
    CmovnsTagId
    CmovpTagId
    CmovnpTagId
    CmovpeTagId
    CmovpoTagId
    JmpTagId
    JeTagId
    JzTagId
    JneTagId
    JnzTagId
    JgTagId
    JngTagId
    JgeTagId
    JngeTagId
    JaTagId
    JnaTagId
    JaeTagId
    JnaeTagId
    JlTagId
    JleTagId
    JbTagId
    JbeTagId
    CallTagId
    ExtcallTagId
    IatTagId
    RetTagId
    PushTagId
    PopTagId
    NopTagId
    SyscallTagId
    SvcTagId
    AdrTagId
    LdrTagId
    StrTagId
    StpTagId
    LdpTagId
    BTagId
    BlTagId
    BeqTagId
    BneTagId
    LabTagId
    IteTagId
    LoopTagId
    StmtsTagId
    CfvarTagId
    JtrueTagId
    DotTagId
    AtTagId
    MemTagId
    RodataTagId
    GvarTagId
    TvarTagId
    ImpTagId
    ExtprocTagId
    KillTagId
    CastTagId
    LockTagId
    XchgTagId
    CmpxchgTagId
    XaddTagId
    Cmpxchg8bTagId
    MfenceTagId
    SfenceTagId
    LfenceTagId
    PauseTagId
    ClflushTagId
    ClflushoptTagId
    Prefetcht0TagId
    Prefetcht1TagId
    Prefetcht2TagId
    PrefetchntaTagId
    RaxTagId
    RbxTagId
    RcxTagId
    RdxTagId
    RsiTagId
    RdiTagId
    RbpTagId
    RspTagId
    R8TagId
    R9TagId
    R10TagId
    R11TagId
    R12TagId
    R13TagId
    R14TagId
    R15TagId
    R0TagId
    R1TagId
    R2TagId
    R3TagId
    R4TagId
    R5TagId
    R6TagId
    R7TagId
    Xmm0TagId
    Xmm1TagId
    Xmm2TagId
    Xmm3TagId
    Xmm4TagId
    Xmm5TagId
    Xmm6TagId
    Xmm7TagId
    Xmm8TagId
    Xmm9TagId
    Xmm10TagId
    Xmm11TagId
    Xmm12TagId
    Xmm13TagId
    Xmm14TagId
    Xmm15TagId
    X0TagId
    X1TagId
    X2TagId
    X3TagId
    X4TagId
    X5TagId
    X6TagId
    X7TagId
    X8TagId
    X9TagId
    X10TagId
    X11TagId
    X12TagId
    X13TagId
    X14TagId
    X15TagId
    X16TagId
    X17TagId
    X18TagId
    X19TagId
    X20TagId
    X21TagId
    X22TagId
    X23TagId
    X24TagId
    X25TagId
    X26TagId
    X27TagId
    X28TagId
    X29TagId
    X30TagId
    SpTagId
    W0TagId
    W1TagId
    W2TagId
    W3TagId
    W4TagId
    W5TagId
    W6TagId
    W7TagId
    W8TagId
    W9TagId
    W10TagId
    W11TagId
    W12TagId
    W13TagId
    W14TagId
    W15TagId
    W16TagId
    W17TagId
    W18TagId
    W19TagId
    W20TagId
    W21TagId
    W22TagId
    W23TagId
    W24TagId
    W25TagId
    W26TagId
    W27TagId
    W28TagId
    W29TagId
    W30TagId
    WspTagId
    LrTagId
    FpTagId
    XzrTagId
    OfTagId
    NoTagId
    ZfTagId
    NzTagId
    SfTagId
    NsTagId
    CfTagId
    NcTagId
    PfTagId
    NpTagId
const
  TagData*: array[TagEnum, (string, int)] = [
    ("InvalidTagId", 0),
    ("bool", 1),
    ("i", 2),
    ("u", 3),
    ("f", 4),
    ("ptr", 5),
    ("aptr", 6),
    ("array", 7),
    ("type", 8),
    ("object", 9),
    ("union", 10),
    ("fld", 11),
    ("proc", 12),
    ("params", 13),
    ("param", 14),
    ("result", 15),
    ("clobber", 16),
    ("var", 17),
    ("arch", 18),
    ("s", 19),
    ("ssize", 20),
    ("csize", 21),
    ("arg", 22),
    ("res", 23),
    ("prepare", 24),
    ("mov", 25),
    ("lea", 26),
    ("movapd", 27),
    ("movsd", 28),
    ("add", 29),
    ("sub", 30),
    ("mul", 31),
    ("imul", 32),
    ("div", 33),
    ("idiv", 34),
    ("sdiv", 35),
    ("udiv", 36),
    ("addsd", 37),
    ("subsd", 38),
    ("mulsd", 39),
    ("divsd", 40),
    ("and", 41),
    ("or", 42),
    ("orr", 43),
    ("xor", 44),
    ("eor", 45),
    ("shl", 46),
    ("lsl", 47),
    ("shr", 48),
    ("lsr", 49),
    ("sal", 50),
    ("sar", 51),
    ("asr", 52),
    ("inc", 53),
    ("dec", 54),
    ("neg", 55),
    ("not", 56),
    ("cmp", 57),
    ("test", 58),
    ("sete", 59),
    ("setz", 60),
    ("setne", 61),
    ("setnz", 62),
    ("seta", 63),
    ("setnbe", 64),
    ("setae", 65),
    ("setnb", 66),
    ("setnc", 67),
    ("setb", 68),
    ("setnae", 69),
    ("setc", 70),
    ("setbe", 71),
    ("setna", 72),
    ("setg", 73),
    ("setnle", 74),
    ("setge", 75),
    ("setnl", 76),
    ("setl", 77),
    ("setnge", 78),
    ("setle", 79),
    ("setng", 80),
    ("seto", 81),
    ("sets", 82),
    ("setp", 83),
    ("cmove", 84),
    ("cmovz", 85),
    ("cmovne", 86),
    ("cmovnz", 87),
    ("cmova", 88),
    ("cmovnbe", 89),
    ("cmovae", 90),
    ("cmovnb", 91),
    ("cmovnc", 92),
    ("cmovb", 93),
    ("cmovnae", 94),
    ("cmovc", 95),
    ("cmovbe", 96),
    ("cmovna", 97),
    ("cmovg", 98),
    ("cmovnle", 99),
    ("cmovge", 100),
    ("cmovnl", 101),
    ("cmovl", 102),
    ("cmovnge", 103),
    ("cmovle", 104),
    ("cmovng", 105),
    ("cmovo", 106),
    ("cmovno", 107),
    ("cmovs", 108),
    ("cmovns", 109),
    ("cmovp", 110),
    ("cmovnp", 111),
    ("cmovpe", 112),
    ("cmovpo", 113),
    ("jmp", 114),
    ("je", 115),
    ("jz", 116),
    ("jne", 117),
    ("jnz", 118),
    ("jg", 119),
    ("jng", 120),
    ("jge", 121),
    ("jnge", 122),
    ("ja", 123),
    ("jna", 124),
    ("jae", 125),
    ("jnae", 126),
    ("jl", 127),
    ("jle", 128),
    ("jb", 129),
    ("jbe", 130),
    ("call", 131),
    ("extcall", 132),
    ("iat", 133),
    ("ret", 134),
    ("push", 135),
    ("pop", 136),
    ("nop", 137),
    ("syscall", 138),
    ("svc", 139),
    ("adr", 140),
    ("ldr", 141),
    ("str", 142),
    ("stp", 143),
    ("ldp", 144),
    ("b", 145),
    ("bl", 146),
    ("beq", 147),
    ("bne", 148),
    ("lab", 149),
    ("ite", 150),
    ("loop", 151),
    ("stmts", 152),
    ("cfvar", 153),
    ("jtrue", 154),
    ("dot", 155),
    ("at", 156),
    ("mem", 157),
    ("rodata", 158),
    ("gvar", 159),
    ("tvar", 160),
    ("imp", 161),
    ("extproc", 162),
    ("kill", 163),
    ("cast", 164),
    ("lock", 165),
    ("xchg", 166),
    ("cmpxchg", 167),
    ("xadd", 168),
    ("cmpxchg8b", 169),
    ("mfence", 170),
    ("sfence", 171),
    ("lfence", 172),
    ("pause", 173),
    ("clflush", 174),
    ("clflushopt", 175),
    ("prefetcht0", 176),
    ("prefetcht1", 177),
    ("prefetcht2", 178),
    ("prefetchnta", 179),
    ("rax", 180),
    ("rbx", 181),
    ("rcx", 182),
    ("rdx", 183),
    ("rsi", 184),
    ("rdi", 185),
    ("rbp", 186),
    ("rsp", 187),
    ("r8", 188),
    ("r9", 189),
    ("r10", 190),
    ("r11", 191),
    ("r12", 192),
    ("r13", 193),
    ("r14", 194),
    ("r15", 195),
    ("r0", 196),
    ("r1", 197),
    ("r2", 198),
    ("r3", 199),
    ("r4", 200),
    ("r5", 201),
    ("r6", 202),
    ("r7", 203),
    ("xmm0", 204),
    ("xmm1", 205),
    ("xmm2", 206),
    ("xmm3", 207),
    ("xmm4", 208),
    ("xmm5", 209),
    ("xmm6", 210),
    ("xmm7", 211),
    ("xmm8", 212),
    ("xmm9", 213),
    ("xmm10", 214),
    ("xmm11", 215),
    ("xmm12", 216),
    ("xmm13", 217),
    ("xmm14", 218),
    ("xmm15", 219),
    ("x0", 220),
    ("x1", 221),
    ("x2", 222),
    ("x3", 223),
    ("x4", 224),
    ("x5", 225),
    ("x6", 226),
    ("x7", 227),
    ("x8", 228),
    ("x9", 229),
    ("x10", 230),
    ("x11", 231),
    ("x12", 232),
    ("x13", 233),
    ("x14", 234),
    ("x15", 235),
    ("x16", 236),
    ("x17", 237),
    ("x18", 238),
    ("x19", 239),
    ("x20", 240),
    ("x21", 241),
    ("x22", 242),
    ("x23", 243),
    ("x24", 244),
    ("x25", 245),
    ("x26", 246),
    ("x27", 247),
    ("x28", 248),
    ("x29", 249),
    ("x30", 250),
    ("sp", 251),
    ("w0", 252),
    ("w1", 253),
    ("w2", 254),
    ("w3", 255),
    ("w4", 256),
    ("w5", 257),
    ("w6", 258),
    ("w7", 259),
    ("w8", 260),
    ("w9", 261),
    ("w10", 262),
    ("w11", 263),
    ("w12", 264),
    ("w13", 265),
    ("w14", 266),
    ("w15", 267),
    ("w16", 268),
    ("w17", 269),
    ("w18", 270),
    ("w19", 271),
    ("w20", 272),
    ("w21", 273),
    ("w22", 274),
    ("w23", 275),
    ("w24", 276),
    ("w25", 277),
    ("w26", 278),
    ("w27", 279),
    ("w28", 280),
    ("w29", 281),
    ("w30", 282),
    ("wsp", 283),
    ("lr", 284),
    ("fp", 285),
    ("xzr", 286),
    ("of", 287),
    ("no", 288),
    ("zf", 289),
    ("nz", 290),
    ("sf", 291),
    ("ns", 292),
    ("cf", 293),
    ("nc", 294),
    ("pf", 295),
    ("np", 296)
  ]
