# Generated by tools/gen_tags.nim from doc/tags.md. DO NOT EDIT!

import tags

type
  X64Inst* = enum
    NoInst
    MovI = (ord(MovTagId), "mov")  ## move instruction
    LeaI = (ord(LeaTagId), "lea")  ## load effective address
    MovapdI = (ord(MovapdTagId), "movapd")  ## move aligned packed double
    MovsdI = (ord(MovsdTagId), "movsd")  ## move scalar double
    AddI = (ord(AddTagId), "add")  ## add instruction
    SubI = (ord(SubTagId), "sub")  ## subtract instruction
    MulI = (ord(MulTagId), "mul")  ## unsigned multiply
    ImulI = (ord(ImulTagId), "imul")  ## signed multiply
    DivI = (ord(DivTagId), "div")  ## unsigned divide
    IdivI = (ord(IdivTagId), "idiv")  ## signed divide
    AddsdI = (ord(AddsdTagId), "addsd")  ## add scalar double
    SubsdI = (ord(SubsdTagId), "subsd")  ## subtract scalar double
    MulsdI = (ord(MulsdTagId), "mulsd")  ## multiply scalar double
    DivsdI = (ord(DivsdTagId), "divsd")  ## divide scalar double
    AndI = (ord(AndTagId), "and")  ## bitwise and
    OrI = (ord(OrTagId), "or")  ## bitwise or
    XorI = (ord(XorTagId), "xor")  ## bitwise xor
    ShlI = (ord(ShlTagId), "shl")  ## shift left
    ShrI = (ord(ShrTagId), "shr")  ## shift right
    SalI = (ord(SalTagId), "sal")  ## shift arithmetic left
    SarI = (ord(SarTagId), "sar")  ## shift arithmetic right
    IncI = (ord(IncTagId), "inc")  ## increment
    DecI = (ord(DecTagId), "dec")  ## decrement
    NegI = (ord(NegTagId), "neg")  ## negate
    NotI = (ord(NotTagId), "not")  ## bitwise not
    CmpI = (ord(CmpTagId), "cmp")  ## compare
    TestI = (ord(TestTagId), "test")  ## test
    SeteI = (ord(SeteTagId), "sete")  ## set byte if equal
    SetzI = (ord(SetzTagId), "setz")  ## set byte if zero
    SetneI = (ord(SetneTagId), "setne")  ## set byte if not equal
    SetnzI = (ord(SetnzTagId), "setnz")  ## set byte if not zero
    SetaI = (ord(SetaTagId), "seta")  ## set byte if above
    SetnbeI = (ord(SetnbeTagId), "setnbe")  ## set byte if not below or equal
    SetaeI = (ord(SetaeTagId), "setae")  ## set byte if above or equal
    SetnbI = (ord(SetnbTagId), "setnb")  ## set byte if not below
    SetncI = (ord(SetncTagId), "setnc")  ## set byte if not carry
    SetbI = (ord(SetbTagId), "setb")  ## set byte if below
    SetnaeI = (ord(SetnaeTagId), "setnae")  ## set byte if not above or equal
    SetcI = (ord(SetcTagId), "setc")  ## set byte if carry
    SetbeI = (ord(SetbeTagId), "setbe")  ## set byte if below or equal
    SetnaI = (ord(SetnaTagId), "setna")  ## set byte if not above
    SetgI = (ord(SetgTagId), "setg")  ## set byte if greater
    SetnleI = (ord(SetnleTagId), "setnle")  ## set byte if not less or equal
    SetgeI = (ord(SetgeTagId), "setge")  ## set byte if greater or equal
    SetnlI = (ord(SetnlTagId), "setnl")  ## set byte if not less
    SetlI = (ord(SetlTagId), "setl")  ## set byte if less
    SetngeI = (ord(SetngeTagId), "setnge")  ## set byte if not greater or equal
    SetleI = (ord(SetleTagId), "setle")  ## set byte if less or equal
    SetngI = (ord(SetngTagId), "setng")  ## set byte if not greater
    SetoI = (ord(SetoTagId), "seto")  ## set byte if overflow
    SetsI = (ord(SetsTagId), "sets")  ## set byte if sign
    SetpI = (ord(SetpTagId), "setp")  ## set byte if parity
    CmoveI = (ord(CmoveTagId), "cmove")  ## conditional move if equal
    CmovzI = (ord(CmovzTagId), "cmovz")  ## conditional move if zero
    CmovneI = (ord(CmovneTagId), "cmovne")  ## conditional move if not equal
    CmovnzI = (ord(CmovnzTagId), "cmovnz")  ## conditional move if not zero
    CmovaI = (ord(CmovaTagId), "cmova")  ## conditional move if above
    CmovnbeI = (ord(CmovnbeTagId), "cmovnbe")  ## conditional move if not below or equal
    CmovaeI = (ord(CmovaeTagId), "cmovae")  ## conditional move if above or equal
    CmovnbI = (ord(CmovnbTagId), "cmovnb")  ## conditional move if not below
    CmovncI = (ord(CmovncTagId), "cmovnc")  ## conditional move if not carry
    CmovbI = (ord(CmovbTagId), "cmovb")  ## conditional move if below
    CmovnaeI = (ord(CmovnaeTagId), "cmovnae")  ## conditional move if not above or equal
    CmovcI = (ord(CmovcTagId), "cmovc")  ## conditional move if carry
    CmovbeI = (ord(CmovbeTagId), "cmovbe")  ## conditional move if below or equal
    CmovnaI = (ord(CmovnaTagId), "cmovna")  ## conditional move if not above
    CmovgI = (ord(CmovgTagId), "cmovg")  ## conditional move if greater
    CmovnleI = (ord(CmovnleTagId), "cmovnle")  ## conditional move if not less or equal
    CmovgeI = (ord(CmovgeTagId), "cmovge")  ## conditional move if greater or equal
    CmovnlI = (ord(CmovnlTagId), "cmovnl")  ## conditional move if not less
    CmovlI = (ord(CmovlTagId), "cmovl")  ## conditional move if less
    CmovngeI = (ord(CmovngeTagId), "cmovnge")  ## conditional move if not greater or equal
    CmovleI = (ord(CmovleTagId), "cmovle")  ## conditional move if less or equal
    CmovngI = (ord(CmovngTagId), "cmovng")  ## conditional move if not greater
    CmovoI = (ord(CmovoTagId), "cmovo")  ## conditional move if overflow
    CmovnoI = (ord(CmovnoTagId), "cmovno")  ## conditional move if not overflow
    CmovsI = (ord(CmovsTagId), "cmovs")  ## conditional move if sign
    CmovnsI = (ord(CmovnsTagId), "cmovns")  ## conditional move if not sign
    CmovpI = (ord(CmovpTagId), "cmovp")  ## conditional move if parity
    CmovnpI = (ord(CmovnpTagId), "cmovnp")  ## conditional move if not parity
    CmovpeI = (ord(CmovpeTagId), "cmovpe")  ## conditional move if parity even (alias for p)
    CmovpoI = (ord(CmovpoTagId), "cmovpo")  ## conditional move if parity odd (alias for np)
    JmpI = (ord(JmpTagId), "jmp")  ## unconditional jump
    JeI = (ord(JeTagId), "je")  ## jump if equal
    JzI = (ord(JzTagId), "jz")  ## jump if zero
    JneI = (ord(JneTagId), "jne")  ## jump if not equal
    JnzI = (ord(JnzTagId), "jnz")  ## jump if not zero
    JgI = (ord(JgTagId), "jg")  ## jump if greater
    JngI = (ord(JngTagId), "jng")  ## jump if not greater
    JgeI = (ord(JgeTagId), "jge")  ## jump if greater or equal
    JngeI = (ord(JngeTagId), "jnge")  ## jump if not greater or equal
    JaI = (ord(JaTagId), "ja")  ## jump if above
    JnaI = (ord(JnaTagId), "jna")  ## jump if not above
    JaeI = (ord(JaeTagId), "jae")  ## jump if above or equal
    JnaeI = (ord(JnaeTagId), "jnae")  ## jump if not above or equal
    JlI = (ord(JlTagId), "jl")  ## jump if less
    JleI = (ord(JleTagId), "jle")  ## jump if less or equal
    JbI = (ord(JbTagId), "jb")  ## jump if below
    JbeI = (ord(JbeTagId), "jbe")  ## jump if below or equal
    CallI = (ord(CallTagId), "call")  ## function call
    RetI = (ord(RetTagId), "ret")  ## return instruction
    PushI = (ord(PushTagId), "push")  ## push to stack
    PopI = (ord(PopTagId), "pop")  ## pop from stack
    NopI = (ord(NopTagId), "nop")  ## no operation
    SyscallI = (ord(SyscallTagId), "syscall")  ## system call
    LabI = (ord(LabTagId), "lab")  ## label definition
    IteI = (ord(IteTagId), "ite")  ## if-then-else structure
    LoopI = (ord(LoopTagId), "loop")  ## loop structure
    StmtsI = (ord(StmtsTagId), "stmts")  ## statement block
    JtrueI = (ord(JtrueTagId), "jtrue")  ## set control flow variable(s) to true
    KillI = (ord(KillTagId), "kill")  ## kill variable
    LockI = (ord(LockTagId), "lock")  ## atomic lock prefix
    XchgI = (ord(XchgTagId), "xchg")  ## atomic exchange
    CmpxchgI = (ord(CmpxchgTagId), "cmpxchg")  ## atomic compare and exchange
    XaddI = (ord(XaddTagId), "xadd")  ## atomic exchange and add
    Cmpxchg8bI = (ord(Cmpxchg8bTagId), "cmpxchg8b")  ## atomic compare and exchange 8 bytes
    MfenceI = (ord(MfenceTagId), "mfence")  ## memory fence
    SfenceI = (ord(SfenceTagId), "sfence")  ## store fence
    LfenceI = (ord(LfenceTagId), "lfence")  ## load fence
    PauseI = (ord(PauseTagId), "pause")  ## pause
    ClflushI = (ord(ClflushTagId), "clflush")  ## cache line flush
    ClflushoptI = (ord(ClflushoptTagId), "clflushopt")  ## optimized cache line flush
    Prefetcht0I = (ord(Prefetcht0TagId), "prefetcht0")  ## prefetch t0
    Prefetcht1I = (ord(Prefetcht1TagId), "prefetcht1")  ## prefetch t1
    Prefetcht2I = (ord(Prefetcht2TagId), "prefetcht2")  ## prefetch t2
    PrefetchntaI = (ord(PrefetchntaTagId), "prefetchnta")  ## prefetch non-temporal

proc rawTagIsX64Inst*(raw: TagEnum): bool {.inline.} =
  raw in {MovTagId, LeaTagId, MovapdTagId, MovsdTagId, AddTagId, SubTagId, MulTagId, ImulTagId, DivTagId, IdivTagId, AddsdTagId, SubsdTagId, MulsdTagId, DivsdTagId, AndTagId, OrTagId, XorTagId, ShlTagId, ShrTagId, SalTagId, SarTagId, IncTagId, DecTagId, NegTagId, NotTagId, CmpTagId, TestTagId, SeteTagId, SetzTagId, SetneTagId, SetnzTagId, SetaTagId, SetnbeTagId, SetaeTagId, SetnbTagId, SetncTagId, SetbTagId, SetnaeTagId, SetcTagId, SetbeTagId, SetnaTagId, SetgTagId, SetnleTagId, SetgeTagId, SetnlTagId, SetlTagId, SetngeTagId, SetleTagId, SetngTagId, SetoTagId, SetsTagId, SetpTagId, CmoveTagId, CmovzTagId, CmovneTagId, CmovnzTagId, CmovaTagId, CmovnbeTagId, CmovaeTagId, CmovnbTagId, CmovncTagId, CmovbTagId, CmovnaeTagId, CmovcTagId, CmovbeTagId, CmovnaTagId, CmovgTagId, CmovnleTagId, CmovgeTagId, CmovnlTagId, CmovlTagId, CmovngeTagId, CmovleTagId, CmovngTagId, CmovoTagId, CmovnoTagId, CmovsTagId, CmovnsTagId, CmovpTagId, CmovnpTagId, CmovpeTagId, CmovpoTagId, JmpTagId, JeTagId, JzTagId, JneTagId, JnzTagId, JgTagId, JngTagId, JgeTagId, JngeTagId, JaTagId, JnaTagId, JaeTagId, JnaeTagId, JlTagId, JleTagId, JbTagId, JbeTagId, CallTagId, RetTagId, PushTagId, PopTagId, NopTagId, SyscallTagId, LabTagId, IteTagId, LoopTagId, StmtsTagId, JtrueTagId, KillTagId, LockTagId, XchgTagId, CmpxchgTagId, XaddTagId, Cmpxchg8bTagId, MfenceTagId, SfenceTagId, LfenceTagId, PauseTagId, ClflushTagId, ClflushoptTagId, Prefetcht0TagId, Prefetcht1TagId, Prefetcht2TagId, PrefetchntaTagId}

type
  NifasmType* = enum
    NoType
    BoolT = (ord(BoolTagId), "bool")  ## boolean type
    IT = (ord(ITagId), "i")  ## signed integer type of N bits
    UT = (ord(UTagId), "u")  ## unsigned integer type of N bits
    FT = (ord(FTagId), "f")  ## float type of N bits
    PtrT = (ord(PtrTagId), "ptr")  ## pointer to single element
    AptrT = (ord(AptrTagId), "aptr")  ## pointer to array of elements
    ArrayT = (ord(ArrayTagId), "array")  ## array type
    ObjectT = (ord(ObjectTagId), "object")  ## object type definition
    UnionT = (ord(UnionTagId), "union")  ## union type definition
    FldT = (ord(FldTagId), "fld")  ## field definition

proc rawTagIsNifasmType*(raw: TagEnum): bool {.inline.} =
  raw >= BoolTagId and raw <= FldTagId and raw != TagEnum(8)

type
  NifasmDecl* = enum
    NoDecl
    TypeD = (ord(TypeTagId), "type")  ## type declaration
    ProcD = (ord(ProcTagId), "proc")  ## proc declaration
    ParamsD = (ord(ParamsTagId), "params")  ## parameters block
    ParamD = (ord(ParamTagId), "param")  ## parameter declaration
    ResultD = (ord(ResultTagId), "result")  ## result value declaration
    ClobberD = (ord(ClobberTagId), "clobber")  ## clobbered registers list
    VarD = (ord(VarTagId), "var")  ## variable declaration
    CfvarD = (ord(CfvarTagId), "cfvar")  ## control flow variable declaration
    RodataD = (ord(RodataTagId), "rodata")  ## read-only data (string/bytes)
    GvarD = (ord(GvarTagId), "gvar")  ## global variable
    TvarD = (ord(TvarTagId), "tvar")  ## thread local variable

proc rawTagIsNifasmDecl*(raw: TagEnum): bool {.inline.} =
  raw in {TypeTagId, ProcTagId, ParamsTagId, ParamTagId, ResultTagId, ClobberTagId, VarTagId, CfvarTagId, RodataTagId, GvarTagId, TvarTagId}

type
  NifasmExpr* = enum
    NoExpr
    SsizeX = (ord(SsizeTagId), "ssize")  ## stack size expression
    DotX = (ord(DotTagId), "dot")  ## field access
    AtX = (ord(AtTagId), "at")  ## array index
    MemX = (ord(MemTagId), "mem")  ## memory reference
    CastX = (ord(CastTagId), "cast")  ## type cast

proc rawTagIsNifasmExpr*(raw: TagEnum): bool {.inline.} =
  raw in {SsizeTagId, DotTagId, AtTagId, MemTagId, CastTagId}

type
  X64Flag* = enum
    NoFlag
    SO = (ord(STagId), "s")  ## stack slot location tag
    OfO = (ord(OfTagId), "of")  ## overflow flag
    NoO = (ord(NoTagId), "no")  ## no overflow flag
    ZfO = (ord(ZfTagId), "zf")  ## zero flag
    NzO = (ord(NzTagId), "nz")  ## not zero flag
    SfO = (ord(SfTagId), "sf")  ## sign flag
    NsO = (ord(NsTagId), "ns")  ## not sign flag
    CfO = (ord(CfTagId), "cf")  ## carry flag
    NcO = (ord(NcTagId), "nc")  ## not carry flag
    PfO = (ord(PfTagId), "pf")  ## parity flag
    NpO = (ord(NpTagId), "np")  ## not parity flag

proc rawTagIsX64Flag*(raw: TagEnum): bool {.inline.} =
  raw in {STagId, OfTagId, NoTagId, ZfTagId, NzTagId, SfTagId, NsTagId, CfTagId, NcTagId, PfTagId, NpTagId}

type
  X64Reg* = enum
    NoReg
    RaxR = (ord(RaxTagId), "rax")  ## register rax
    RbxR = (ord(RbxTagId), "rbx")  ## register rbx
    RcxR = (ord(RcxTagId), "rcx")  ## register rcx
    RdxR = (ord(RdxTagId), "rdx")  ## register rdx
    RsiR = (ord(RsiTagId), "rsi")  ## register rsi
    RdiR = (ord(RdiTagId), "rdi")  ## register rdi
    RbpR = (ord(RbpTagId), "rbp")  ## register rbp
    RspR = (ord(RspTagId), "rsp")  ## register rsp
    R8R = (ord(R8TagId), "r8")  ## register r8
    R9R = (ord(R9TagId), "r9")  ## register r9
    R10R = (ord(R10TagId), "r10")  ## register r10
    R11R = (ord(R11TagId), "r11")  ## register r11
    R12R = (ord(R12TagId), "r12")  ## register r12
    R13R = (ord(R13TagId), "r13")  ## register r13
    R14R = (ord(R14TagId), "r14")  ## register r14
    R15R = (ord(R15TagId), "r15")  ## register r15
    R0R = (ord(R0TagId), "r0")  ## register r0 (alias)
    R1R = (ord(R1TagId), "r1")  ## register r1 (alias)
    R2R = (ord(R2TagId), "r2")  ## register r2 (alias)
    R3R = (ord(R3TagId), "r3")  ## register r3 (alias)
    R4R = (ord(R4TagId), "r4")  ## register r4 (alias)
    R5R = (ord(R5TagId), "r5")  ## register r5 (alias)
    R6R = (ord(R6TagId), "r6")  ## register r6 (alias)
    R7R = (ord(R7TagId), "r7")  ## register r7 (alias)
    Xmm0R = (ord(Xmm0TagId), "xmm0")  ## register xmm0
    Xmm1R = (ord(Xmm1TagId), "xmm1")  ## register xmm1
    Xmm2R = (ord(Xmm2TagId), "xmm2")  ## register xmm2
    Xmm3R = (ord(Xmm3TagId), "xmm3")  ## register xmm3
    Xmm4R = (ord(Xmm4TagId), "xmm4")  ## register xmm4
    Xmm5R = (ord(Xmm5TagId), "xmm5")  ## register xmm5
    Xmm6R = (ord(Xmm6TagId), "xmm6")  ## register xmm6
    Xmm7R = (ord(Xmm7TagId), "xmm7")  ## register xmm7
    Xmm8R = (ord(Xmm8TagId), "xmm8")  ## register xmm8
    Xmm9R = (ord(Xmm9TagId), "xmm9")  ## register xmm9
    Xmm10R = (ord(Xmm10TagId), "xmm10")  ## register xmm10
    Xmm11R = (ord(Xmm11TagId), "xmm11")  ## register xmm11
    Xmm12R = (ord(Xmm12TagId), "xmm12")  ## register xmm12
    Xmm13R = (ord(Xmm13TagId), "xmm13")  ## register xmm13
    Xmm14R = (ord(Xmm14TagId), "xmm14")  ## register xmm14
    Xmm15R = (ord(Xmm15TagId), "xmm15")  ## register xmm15

proc rawTagIsX64Reg*(raw: TagEnum): bool {.inline.} =
  raw >= RaxTagId and raw <= Xmm15TagId

