# Generated by tools/gen_instructions.nim from doc/instructions.md. DO NOT EDIT!

import tags

type
  X64Inst* = enum
    NoX64Inst
    PrepareX64 = (ord(PrepareTagId), "prepare")  ## prepare block for function call
    MovX64 = (ord(MovTagId), "mov")  ## move instruction
    LeaX64 = (ord(LeaTagId), "lea")  ## load effective address
    MovapdX64 = (ord(MovapdTagId), "movapd")  ## move aligned packed double
    MovsdX64 = (ord(MovsdTagId), "movsd")  ## move scalar double
    AddX64 = (ord(AddTagId), "add")  ## add instruction
    SubX64 = (ord(SubTagId), "sub")  ## subtract instruction
    MulX64 = (ord(MulTagId), "mul")  ## unsigned multiply
    ImulX64 = (ord(ImulTagId), "imul")  ## signed multiply
    DivX64 = (ord(DivTagId), "div")  ## unsigned divide
    IdivX64 = (ord(IdivTagId), "idiv")  ## signed divide
    AddsdX64 = (ord(AddsdTagId), "addsd")  ## add scalar double
    SubsdX64 = (ord(SubsdTagId), "subsd")  ## subtract scalar double
    MulsdX64 = (ord(MulsdTagId), "mulsd")  ## multiply scalar double
    DivsdX64 = (ord(DivsdTagId), "divsd")  ## divide scalar double
    MovssX64 = (ord(MovssTagId), "movss")  ## move scalar single
    AddssX64 = (ord(AddssTagId), "addss")  ## add scalar single
    SubssX64 = (ord(SubssTagId), "subss")  ## subtract scalar single
    MulssX64 = (ord(MulssTagId), "mulss")  ## multiply scalar single
    DivssX64 = (ord(DivssTagId), "divss")  ## divide scalar single
    Cvtsi2sdX64 = (ord(Cvtsi2sdTagId), "cvtsi2sd")  ## int -> scalar double convert
    Cvtsi2ssX64 = (ord(Cvtsi2ssTagId), "cvtsi2ss")  ## int -> scalar single convert
    Cvttsd2siX64 = (ord(Cvttsd2siTagId), "cvttsd2si")  ## scalar double -> int convert (truncating)
    Cvttss2siX64 = (ord(Cvttss2siTagId), "cvttss2si")  ## scalar single -> int convert (truncating)
    Cvtsd2ssX64 = (ord(Cvtsd2ssTagId), "cvtsd2ss")  ## scalar double -> scalar single convert
    Cvtss2sdX64 = (ord(Cvtss2sdTagId), "cvtss2sd")  ## scalar single -> scalar double convert
    ComisdX64 = (ord(ComisdTagId), "comisd")  ## compare scalar double, set EFLAGS
    ComissX64 = (ord(ComissTagId), "comiss")  ## compare scalar single, set EFLAGS
    MovfqX64 = (ord(MovfqTagId), "movfq")  ## move 64 bits between gpr and xmm
    MovfdX64 = (ord(MovfdTagId), "movfd")  ## move 32 bits between gpr and xmm
    AndX64 = (ord(AndTagId), "and")  ## bitwise and
    OrX64 = (ord(OrTagId), "or")  ## bitwise or
    XorX64 = (ord(XorTagId), "xor")  ## bitwise xor
    ShlX64 = (ord(ShlTagId), "shl")  ## shift left
    ShrX64 = (ord(ShrTagId), "shr")  ## shift right
    SalX64 = (ord(SalTagId), "sal")  ## shift arithmetic left
    SarX64 = (ord(SarTagId), "sar")  ## shift arithmetic right
    IncX64 = (ord(IncTagId), "inc")  ## increment
    DecX64 = (ord(DecTagId), "dec")  ## decrement
    NegX64 = (ord(NegTagId), "neg")  ## negate
    NotX64 = (ord(NotTagId), "not")  ## bitwise not
    RolX64 = (ord(RolTagId), "rol")  ## rotate left
    RorX64 = (ord(RorTagId), "ror")  ## rotate right
    RclX64 = (ord(RclTagId), "rcl")  ## rotate left through carry
    RcrX64 = (ord(RcrTagId), "rcr")  ## rotate right through carry
    BsfX64 = (ord(BsfTagId), "bsf")  ## bit scan forward
    BsrX64 = (ord(BsrTagId), "bsr")  ## bit scan reverse
    BtX64 = (ord(BtTagId), "bt")  ## bit test
    BtsX64 = (ord(BtsTagId), "bts")  ## bit test and set
    BtrX64 = (ord(BtrTagId), "btr")  ## bit test and reset
    BtcX64 = (ord(BtcTagId), "btc")  ## bit test and complement
    CmpX64 = (ord(CmpTagId), "cmp")  ## compare
    TestX64 = (ord(TestTagId), "test")  ## test
    SeteX64 = (ord(SeteTagId), "sete")  ## set byte if equal
    SetzX64 = (ord(SetzTagId), "setz")  ## set byte if zero
    SetneX64 = (ord(SetneTagId), "setne")  ## set byte if not equal
    SetnzX64 = (ord(SetnzTagId), "setnz")  ## set byte if not zero
    SetaX64 = (ord(SetaTagId), "seta")  ## set byte if above
    SetnbeX64 = (ord(SetnbeTagId), "setnbe")  ## set byte if not below or equal
    SetaeX64 = (ord(SetaeTagId), "setae")  ## set byte if above or equal
    SetnbX64 = (ord(SetnbTagId), "setnb")  ## set byte if not below
    SetncX64 = (ord(SetncTagId), "setnc")  ## set byte if not carry
    SetbX64 = (ord(SetbTagId), "setb")  ## set byte if below
    SetnaeX64 = (ord(SetnaeTagId), "setnae")  ## set byte if not above or equal
    SetcX64 = (ord(SetcTagId), "setc")  ## set byte if carry
    SetbeX64 = (ord(SetbeTagId), "setbe")  ## set byte if below or equal
    SetnaX64 = (ord(SetnaTagId), "setna")  ## set byte if not above
    SetgX64 = (ord(SetgTagId), "setg")  ## set byte if greater
    SetnleX64 = (ord(SetnleTagId), "setnle")  ## set byte if not less or equal
    SetgeX64 = (ord(SetgeTagId), "setge")  ## set byte if greater or equal
    SetnlX64 = (ord(SetnlTagId), "setnl")  ## set byte if not less
    SetlX64 = (ord(SetlTagId), "setl")  ## set byte if less
    SetngeX64 = (ord(SetngeTagId), "setnge")  ## set byte if not greater or equal
    SetleX64 = (ord(SetleTagId), "setle")  ## set byte if less or equal
    SetngX64 = (ord(SetngTagId), "setng")  ## set byte if not greater
    SetoX64 = (ord(SetoTagId), "seto")  ## set byte if overflow
    SetsX64 = (ord(SetsTagId), "sets")  ## set byte if sign
    SetpX64 = (ord(SetpTagId), "setp")  ## set byte if parity
    CmoveX64 = (ord(CmoveTagId), "cmove")  ## conditional move if equal
    CmovzX64 = (ord(CmovzTagId), "cmovz")  ## conditional move if zero
    CmovneX64 = (ord(CmovneTagId), "cmovne")  ## conditional move if not equal
    CmovnzX64 = (ord(CmovnzTagId), "cmovnz")  ## conditional move if not zero
    CmovaX64 = (ord(CmovaTagId), "cmova")  ## conditional move if above
    CmovnbeX64 = (ord(CmovnbeTagId), "cmovnbe")  ## conditional move if not below or equal
    CmovaeX64 = (ord(CmovaeTagId), "cmovae")  ## conditional move if above or equal
    CmovnbX64 = (ord(CmovnbTagId), "cmovnb")  ## conditional move if not below
    CmovncX64 = (ord(CmovncTagId), "cmovnc")  ## conditional move if not carry
    CmovbX64 = (ord(CmovbTagId), "cmovb")  ## conditional move if below
    CmovnaeX64 = (ord(CmovnaeTagId), "cmovnae")  ## conditional move if not above or equal
    CmovcX64 = (ord(CmovcTagId), "cmovc")  ## conditional move if carry
    CmovbeX64 = (ord(CmovbeTagId), "cmovbe")  ## conditional move if below or equal
    CmovnaX64 = (ord(CmovnaTagId), "cmovna")  ## conditional move if not above
    CmovgX64 = (ord(CmovgTagId), "cmovg")  ## conditional move if greater
    CmovnleX64 = (ord(CmovnleTagId), "cmovnle")  ## conditional move if not less or equal
    CmovgeX64 = (ord(CmovgeTagId), "cmovge")  ## conditional move if greater or equal
    CmovnlX64 = (ord(CmovnlTagId), "cmovnl")  ## conditional move if not less
    CmovlX64 = (ord(CmovlTagId), "cmovl")  ## conditional move if less
    CmovngeX64 = (ord(CmovngeTagId), "cmovnge")  ## conditional move if not greater or equal
    CmovleX64 = (ord(CmovleTagId), "cmovle")  ## conditional move if less or equal
    CmovngX64 = (ord(CmovngTagId), "cmovng")  ## conditional move if not greater
    CmovoX64 = (ord(CmovoTagId), "cmovo")  ## conditional move if overflow
    CmovnoX64 = (ord(CmovnoTagId), "cmovno")  ## conditional move if not overflow
    CmovsX64 = (ord(CmovsTagId), "cmovs")  ## conditional move if sign
    CmovnsX64 = (ord(CmovnsTagId), "cmovns")  ## conditional move if not sign
    CmovpX64 = (ord(CmovpTagId), "cmovp")  ## conditional move if parity
    CmovnpX64 = (ord(CmovnpTagId), "cmovnp")  ## conditional move if not parity
    CmovpeX64 = (ord(CmovpeTagId), "cmovpe")  ## conditional move if parity even (alias for p)
    CmovpoX64 = (ord(CmovpoTagId), "cmovpo")  ## conditional move if parity odd (alias for np)
    JmpX64 = (ord(JmpTagId), "jmp")  ## unconditional jump
    JeX64 = (ord(JeTagId), "je")  ## jump if equal
    JzX64 = (ord(JzTagId), "jz")  ## jump if zero
    JneX64 = (ord(JneTagId), "jne")  ## jump if not equal
    JnzX64 = (ord(JnzTagId), "jnz")  ## jump if not zero
    JgX64 = (ord(JgTagId), "jg")  ## jump if greater
    JngX64 = (ord(JngTagId), "jng")  ## jump if not greater
    JgeX64 = (ord(JgeTagId), "jge")  ## jump if greater or equal
    JngeX64 = (ord(JngeTagId), "jnge")  ## jump if not greater or equal
    JaX64 = (ord(JaTagId), "ja")  ## jump if above
    JnaX64 = (ord(JnaTagId), "jna")  ## jump if not above
    JaeX64 = (ord(JaeTagId), "jae")  ## jump if above or equal
    JnaeX64 = (ord(JnaeTagId), "jnae")  ## jump if not above or equal
    JlX64 = (ord(JlTagId), "jl")  ## jump if less
    JleX64 = (ord(JleTagId), "jle")  ## jump if less or equal
    JbX64 = (ord(JbTagId), "jb")  ## jump if below
    JbeX64 = (ord(JbeTagId), "jbe")  ## jump if below or equal
    JoX64 = (ord(JoTagId), "jo")  ## jump if overflow
    JnoX64 = (ord(JnoTagId), "jno")  ## jump if not overflow
    CallX64 = (ord(CallTagId), "call")  ## function call marker inside prepare
    ExtcallX64 = (ord(ExtcallTagId), "extcall")  ## external call marker inside prepare
    IatX64 = (ord(IatTagId), "iat")  ## indirect call through IAT (Import Address Table)
    RetX64 = (ord(RetTagId), "ret")  ## return instruction
    PushX64 = (ord(PushTagId), "push")  ## push to stack
    PopX64 = (ord(PopTagId), "pop")  ## pop from stack
    NopX64 = (ord(NopTagId), "nop")  ## no operation
    SyscallX64 = (ord(SyscallTagId), "syscall")  ## system call
    LabX64 = (ord(LabTagId), "lab")  ## label definition
    IteX64 = (ord(IteTagId), "ite")  ## if-then-else structure
    LoopX64 = (ord(LoopTagId), "loop")  ## loop structure
    StmtsX64 = (ord(StmtsTagId), "stmts")  ## statement block
    JtrueX64 = (ord(JtrueTagId), "jtrue")  ## set control flow variable(s) to true
    KillX64 = (ord(KillTagId), "kill")  ## kill variable
    LockX64 = (ord(LockTagId), "lock")  ## atomic lock prefix
    XchgX64 = (ord(XchgTagId), "xchg")  ## atomic exchange
    CmpxchgX64 = (ord(CmpxchgTagId), "cmpxchg")  ## atomic compare and exchange
    XaddX64 = (ord(XaddTagId), "xadd")  ## atomic exchange and add
    Cmpxchg8bX64 = (ord(Cmpxchg8bTagId), "cmpxchg8b")  ## atomic compare and exchange 8 bytes
    MfenceX64 = (ord(MfenceTagId), "mfence")  ## memory fence
    SfenceX64 = (ord(SfenceTagId), "sfence")  ## store fence
    LfenceX64 = (ord(LfenceTagId), "lfence")  ## load fence
    PauseX64 = (ord(PauseTagId), "pause")  ## pause
    ClflushX64 = (ord(ClflushTagId), "clflush")  ## cache line flush
    ClflushoptX64 = (ord(ClflushoptTagId), "clflushopt")  ## optimized cache line flush
    Prefetcht0X64 = (ord(Prefetcht0TagId), "prefetcht0")  ## prefetch t0
    Prefetcht1X64 = (ord(Prefetcht1TagId), "prefetcht1")  ## prefetch t1
    Prefetcht2X64 = (ord(Prefetcht2TagId), "prefetcht2")  ## prefetch t2
    PrefetchntaX64 = (ord(PrefetchntaTagId), "prefetchnta")  ## prefetch non-temporal
    RepmovsbX64 = (ord(RepmovsbTagId), "repmovsb")  ## repeat move byte string
    RepmovswX64 = (ord(RepmovswTagId), "repmovsw")  ## repeat move word string
    RepmovsdX64 = (ord(RepmovsdTagId), "repmovsd")  ## repeat move doubleword string
    RepmovsqX64 = (ord(RepmovsqTagId), "repmovsq")  ## repeat move quadword string
    RebindX64 = (ord(RebindTagId), "rebind")  ## bind a phys reg to a typed name, killing its prior tenant
    WithregX64 = (ord(WithregTagId), "withreg")  ## block-scoped rebind; auto-killed at block end
    BswapX64 = (ord(BswapTagId), "bswap")  ## reverse byte order (BSWAP r32/r64; `__builtin_bswap*`)
    ScopeX64 = (ord(ScopeTagId), "scope")  ## statement block with a reclaimable stack-slot arena: `(s)` locals declared inside are freed at scope end so sibling scopes reuse the frame bytes

proc rawTagIsX64Inst*(raw: TagEnum): bool {.inline.} =
  raw in {PrepareTagId, MovTagId, LeaTagId, MovapdTagId, MovsdTagId, AddTagId, SubTagId, MulTagId, ImulTagId, DivTagId, IdivTagId, AddsdTagId, SubsdTagId, MulsdTagId, DivsdTagId, MovssTagId, AddssTagId, SubssTagId, MulssTagId, DivssTagId, Cvtsi2sdTagId, Cvtsi2ssTagId, Cvttsd2siTagId, Cvttss2siTagId, Cvtsd2ssTagId, Cvtss2sdTagId, ComisdTagId, ComissTagId, MovfqTagId, MovfdTagId, AndTagId, OrTagId, XorTagId, ShlTagId, ShrTagId, SalTagId, SarTagId, IncTagId, DecTagId, NegTagId, NotTagId, RolTagId, RorTagId, RclTagId, RcrTagId, BsfTagId, BsrTagId, BtTagId, BtsTagId, BtrTagId, BtcTagId, CmpTagId, TestTagId, SeteTagId, SetzTagId, SetneTagId, SetnzTagId, SetaTagId, SetnbeTagId, SetaeTagId, SetnbTagId, SetncTagId, SetbTagId, SetnaeTagId, SetcTagId, SetbeTagId, SetnaTagId, SetgTagId, SetnleTagId, SetgeTagId, SetnlTagId, SetlTagId, SetngeTagId, SetleTagId, SetngTagId, SetoTagId, SetsTagId, SetpTagId, CmoveTagId, CmovzTagId, CmovneTagId, CmovnzTagId, CmovaTagId, CmovnbeTagId, CmovaeTagId, CmovnbTagId, CmovncTagId, CmovbTagId, CmovnaeTagId, CmovcTagId, CmovbeTagId, CmovnaTagId, CmovgTagId, CmovnleTagId, CmovgeTagId, CmovnlTagId, CmovlTagId, CmovngeTagId, CmovleTagId, CmovngTagId, CmovoTagId, CmovnoTagId, CmovsTagId, CmovnsTagId, CmovpTagId, CmovnpTagId, CmovpeTagId, CmovpoTagId, JmpTagId, JeTagId, JzTagId, JneTagId, JnzTagId, JgTagId, JngTagId, JgeTagId, JngeTagId, JaTagId, JnaTagId, JaeTagId, JnaeTagId, JlTagId, JleTagId, JbTagId, JbeTagId, JoTagId, JnoTagId, CallTagId, ExtcallTagId, IatTagId, RetTagId, PushTagId, PopTagId, NopTagId, SyscallTagId, LabTagId, IteTagId, LoopTagId, StmtsTagId, JtrueTagId, KillTagId, LockTagId, XchgTagId, CmpxchgTagId, XaddTagId, Cmpxchg8bTagId, MfenceTagId, SfenceTagId, LfenceTagId, PauseTagId, ClflushTagId, ClflushoptTagId, Prefetcht0TagId, Prefetcht1TagId, Prefetcht2TagId, PrefetchntaTagId, RepmovsbTagId, RepmovswTagId, RepmovsdTagId, RepmovsqTagId, RebindTagId, WithregTagId, BswapTagId, ScopeTagId}

type
  A64Inst* = enum
    NoA64Inst
    PrepareA64 = (ord(PrepareTagId), "prepare")  ## prepare block for function call
    MovA64 = (ord(MovTagId), "mov")  ## move instruction
    LeaA64 = (ord(LeaTagId), "lea")  ## load effective address
    AddA64 = (ord(AddTagId), "add")  ## add instruction
    SubA64 = (ord(SubTagId), "sub")  ## subtract instruction
    MulA64 = (ord(MulTagId), "mul")  ## unsigned multiply
    SdivA64 = (ord(SdivTagId), "sdiv")  ## signed divide
    UdivA64 = (ord(UdivTagId), "udiv")  ## unsigned divide
    AndA64 = (ord(AndTagId), "and")  ## bitwise and
    OrrA64 = (ord(OrrTagId), "orr")  ## bitwise or
    EorA64 = (ord(EorTagId), "eor")  ## bitwise xor
    LslA64 = (ord(LslTagId), "lsl")  ## logical shift left
    LsrA64 = (ord(LsrTagId), "lsr")  ## logical shift right
    AsrA64 = (ord(AsrTagId), "asr")  ## arithmetic shift right
    NegA64 = (ord(NegTagId), "neg")  ## negate
    CmpA64 = (ord(CmpTagId), "cmp")  ## compare
    CallA64 = (ord(CallTagId), "call")  ## function call marker inside prepare
    ExtcallA64 = (ord(ExtcallTagId), "extcall")  ## external call marker inside prepare
    RetA64 = (ord(RetTagId), "ret")  ## return instruction
    NopA64 = (ord(NopTagId), "nop")  ## no operation
    SvcA64 = (ord(SvcTagId), "svc")  ## supervisor call (system call)
    AdrA64 = (ord(AdrTagId), "adr")  ## load address of label
    LdrA64 = (ord(LdrTagId), "ldr")  ## load register
    StrA64 = (ord(StrTagId), "str")  ## store register
    StpA64 = (ord(StpTagId), "stp")  ## store pair
    LdpA64 = (ord(LdpTagId), "ldp")  ## load pair
    BA64 = (ord(BTagId), "b")  ## branch (unconditional jump)
    BlA64 = (ord(BlTagId), "bl")  ## branch with link (function call)
    BeqA64 = (ord(BeqTagId), "beq")  ## branch if equal
    BneA64 = (ord(BneTagId), "bne")  ## branch if not equal
    BltA64 = (ord(BltTagId), "blt")  ## branch if less than (signed)
    BleA64 = (ord(BleTagId), "ble")  ## branch if less or equal (signed)
    BgtA64 = (ord(BgtTagId), "bgt")  ## branch if greater than (signed)
    BgeA64 = (ord(BgeTagId), "bge")  ## branch if greater or equal (signed)
    BloA64 = (ord(BloTagId), "blo")  ## branch if lower (unsigned <)
    BlsA64 = (ord(BlsTagId), "bls")  ## branch if lower or same (unsigned <=)
    BhiA64 = (ord(BhiTagId), "bhi")  ## branch if higher (unsigned >)
    BhsA64 = (ord(BhsTagId), "bhs")  ## branch if higher or same (unsigned >=)
    CseleqA64 = (ord(CseleqTagId), "cseleq")  ## conditional select: D = if equal then S1 else S2
    CselneA64 = (ord(CselneTagId), "cselne")  ## conditional select: D = if not equal then S1 else S2
    CselltA64 = (ord(CselltTagId), "csellt")  ## conditional select: D = if less than (signed) then S1 else S2
    CselleA64 = (ord(CselleTagId), "cselle")  ## conditional select: D = if less or equal (signed) then S1 else S2
    CselgtA64 = (ord(CselgtTagId), "cselgt")  ## conditional select: D = if greater than (signed) then S1 else S2
    CselgeA64 = (ord(CselgeTagId), "cselge")  ## conditional select: D = if greater or equal (signed) then S1 else S2
    CselloA64 = (ord(CselloTagId), "csello")  ## conditional select: D = if lower (unsigned <) then S1 else S2
    CsellsA64 = (ord(CsellsTagId), "csells")  ## conditional select: D = if lower or same (unsigned <=) then S1 else S2
    CselhiA64 = (ord(CselhiTagId), "cselhi")  ## conditional select: D = if higher (unsigned >) then S1 else S2
    CselhsA64 = (ord(CselhsTagId), "cselhs")  ## conditional select: D = if higher or same (unsigned >=) then S1 else S2
    CseteqA64 = (ord(CseteqTagId), "cseteq")  ## conditional set: D = if equal then 1 else 0
    CsetneA64 = (ord(CsetneTagId), "csetne")  ## conditional set: D = if not equal then 1 else 0
    CsetltA64 = (ord(CsetltTagId), "csetlt")  ## conditional set: D = if less than (signed) then 1 else 0
    CsetleA64 = (ord(CsetleTagId), "csetle")  ## conditional set: D = if less or equal (signed) then 1 else 0
    CsetgtA64 = (ord(CsetgtTagId), "csetgt")  ## conditional set: D = if greater than (signed) then 1 else 0
    CsetgeA64 = (ord(CsetgeTagId), "csetge")  ## conditional set: D = if greater or equal (signed) then 1 else 0
    CsetloA64 = (ord(CsetloTagId), "csetlo")  ## conditional set: D = if lower (unsigned <) then 1 else 0
    CsetlsA64 = (ord(CsetlsTagId), "csetls")  ## conditional set: D = if lower or same (unsigned <=) then 1 else 0
    CsethiA64 = (ord(CsethiTagId), "csethi")  ## conditional set: D = if higher (unsigned >) then 1 else 0
    CsethsA64 = (ord(CsethsTagId), "cseths")  ## conditional set: D = if higher or same (unsigned >=) then 1 else 0
    LabA64 = (ord(LabTagId), "lab")  ## label definition
    IteA64 = (ord(IteTagId), "ite")  ## if-then-else structure
    LoopA64 = (ord(LoopTagId), "loop")  ## loop structure
    StmtsA64 = (ord(StmtsTagId), "stmts")  ## statement block
    JtrueA64 = (ord(JtrueTagId), "jtrue")  ## set control flow variable(s) to true
    KillA64 = (ord(KillTagId), "kill")  ## kill variable
    LdaxrA64 = (ord(LdaxrTagId), "ldaxr")  ## load-acquire exclusive register
    StlxrA64 = (ord(StlxrTagId), "stlxr")  ## store-release exclusive register (St = status)
    LdarA64 = (ord(LdarTagId), "ldar")  ## load-acquire register
    StlrA64 = (ord(StlrTagId), "stlr")  ## store-release register
    DmbA64 = (ord(DmbTagId), "dmb")  ## data memory barrier (inner shareable)
    ClrexA64 = (ord(ClrexTagId), "clrex")  ## clear exclusive monitor
    FmovA64 = (ord(FmovTagId), "fmov")  ## fp move (reg-reg / gpr<->fp bitcast)
    FaddA64 = (ord(FaddTagId), "fadd")  ## fp add (D = D + S)
    FsubA64 = (ord(FsubTagId), "fsub")  ## fp subtract (D = D - S)
    FmulA64 = (ord(FmulTagId), "fmul")  ## fp multiply (D = D * S)
    FdivA64 = (ord(FdivTagId), "fdiv")  ## fp divide (D = D / S)
    FnegA64 = (ord(FnegTagId), "fneg")  ## fp negate (D = -D)
    FcmpA64 = (ord(FcmpTagId), "fcmp")  ## fp compare
    FldrA64 = (ord(FldrTagId), "fldr")  ## fp load register
    FstrA64 = (ord(FstrTagId), "fstr")  ## fp store register
    ScvtfA64 = (ord(ScvtfTagId), "scvtf")  ## signed int -> fp convert
    UcvtfA64 = (ord(UcvtfTagId), "ucvtf")  ## unsigned int -> fp convert
    FcvtzsA64 = (ord(FcvtzsTagId), "fcvtzs")  ## fp -> signed int convert (toward zero)
    FcvtzuA64 = (ord(FcvtzuTagId), "fcvtzu")  ## fp -> unsigned int convert (toward zero)
    FcvtA64 = (ord(FcvtTagId), "fcvt")  ## fp precision convert (f32<->f64)
    FstpA64 = (ord(FstpTagId), "fstp")  ## fp store pair (pre-indexed)
    FldpA64 = (ord(FldpTagId), "fldp")  ## fp load pair (post-indexed)
    LdrbA64 = (ord(LdrbTagId), "ldrb")  ## load byte (zero-extend), register offset [B,I]
    StrbA64 = (ord(StrbTagId), "strb")  ## store low byte, register offset [B,I]
    RebindA64 = (ord(RebindTagId), "rebind")  ## bind a phys reg to a typed name, killing its prior tenant
    WithregA64 = (ord(WithregTagId), "withreg")  ## block-scoped rebind; auto-killed at block end
    ScopeA64 = (ord(ScopeTagId), "scope")  ## statement block with a reclaimable stack-slot arena: `(s)` locals declared inside are freed at scope end so sibling scopes reuse the frame bytes

proc rawTagIsA64Inst*(raw: TagEnum): bool {.inline.} =
  raw in {PrepareTagId, MovTagId, LeaTagId, AddTagId, SubTagId, MulTagId, SdivTagId, UdivTagId, AndTagId, OrrTagId, EorTagId, LslTagId, LsrTagId, AsrTagId, NegTagId, CmpTagId, CallTagId, ExtcallTagId, RetTagId, NopTagId, SvcTagId, AdrTagId, LdrTagId, StrTagId, StpTagId, LdpTagId, BTagId, BlTagId, BeqTagId, BneTagId, BltTagId, BleTagId, BgtTagId, BgeTagId, BloTagId, BlsTagId, BhiTagId, BhsTagId, CseleqTagId, CselneTagId, CselltTagId, CselleTagId, CselgtTagId, CselgeTagId, CselloTagId, CsellsTagId, CselhiTagId, CselhsTagId, CseteqTagId, CsetneTagId, CsetltTagId, CsetleTagId, CsetgtTagId, CsetgeTagId, CsetloTagId, CsetlsTagId, CsethiTagId, CsethsTagId, LabTagId, IteTagId, LoopTagId, StmtsTagId, JtrueTagId, KillTagId, LdaxrTagId, StlxrTagId, LdarTagId, StlrTagId, DmbTagId, ClrexTagId, FmovTagId, FaddTagId, FsubTagId, FmulTagId, FdivTagId, FnegTagId, FcmpTagId, FldrTagId, FstrTagId, ScvtfTagId, UcvtfTagId, FcvtzsTagId, FcvtzuTagId, FcvtTagId, FstpTagId, FldpTagId, LdrbTagId, StrbTagId, RebindTagId, WithregTagId, ScopeTagId}

type
  NifasmType* = enum
    NoType
    BoolT = (ord(BoolTagId), "bool")  ## boolean type
    NilT = (ord(NilTagId), "nil")  ## nil: the null-pointer value/type, compatible with any pointer
    IT = (ord(ITagId), "i")  ## signed integer type of N bits
    UT = (ord(UTagId), "u")  ## unsigned integer type of N bits
    FT = (ord(FTagId), "f")  ## float type of N bits
    PtrT = (ord(PtrTagId), "ptr")  ## pointer to single element
    AptrT = (ord(AptrTagId), "aptr")  ## pointer to array of elements
    ArrayT = (ord(ArrayTagId), "array")  ## array type
    ObjectT = (ord(ObjectTagId), "object")  ## object type definition
    UnionT = (ord(UnionTagId), "union")  ## union type definition
    FldT = (ord(FldTagId), "fld")  ## field definition
    CT = (ord(CTagId), "c")  ## character type of N bits
    VoidT = (ord(VoidTagId), "void")  ## void type
    VarargsT = (ord(VarargsTagId), "varargs")  ## C varargs marker type
    FlexarrayT = (ord(FlexarrayTagId), "flexarray")  ## flexible array member
    EnumT = (ord(EnumTagId), "enum")  ## enum type (base type + fields)
    EfldT = (ord(EfldTagId), "efld")  ## enum field declaration
    ProctypeT = (ord(ProctypeTagId), "proctype")  ## procedure (function pointer) type

proc rawTagIsNifasmType*(raw: TagEnum): bool {.inline.} =
  raw in {BoolTagId, NilTagId, ITagId, UTagId, FTagId, PtrTagId, AptrTagId, ArrayTagId, ObjectTagId, UnionTagId, FldTagId, CTagId, VoidTagId, VarargsTagId, FlexarrayTagId, EnumTagId, EfldTagId, ProctypeTagId}

type
  NifasmDecl* = enum
    NoDecl
    TypeD = (ord(TypeTagId), "type")  ## type declaration
    ProcD = (ord(ProcTagId), "proc")  ## proc declaration
    ParamsD = (ord(ParamsTagId), "params")  ## parameters block
    ParamD = (ord(ParamTagId), "param")  ## parameter declaration
    ResultD = (ord(ResultTagId), "result")  ## result value declaration
    ClobberD = (ord(ClobberTagId), "clobber")  ## clobbered registers list
    VarD = (ord(VarTagId), "var")  ## variable declaration
    ArchD = (ord(ArchTagId), "arch")  ## architecture pragma
    CfvarD = (ord(CfvarTagId), "cfvar")  ## control flow variable declaration
    RodataD = (ord(RodataTagId), "rodata")  ## read-only data (string/bytes)
    GvarD = (ord(GvarTagId), "gvar")  ## global variable
    TvarD = (ord(TvarTagId), "tvar")  ## thread local variable
    ImpD = (ord(ImpTagId), "imp")  ## import dynamic library
    ExtprocD = (ord(ExtprocTagId), "extproc")  ## external proc from imported library
    SyprocD = (ord(SyprocTagId), "syproc")  ## system-call proc declaration (proctype + clobbers + number)
    RegsD = (ord(RegsTagId), "regs")  ## multi-register param/result location: `(regs (rdi) (rsi))`

proc rawTagIsNifasmDecl*(raw: TagEnum): bool {.inline.} =
  raw in {TypeTagId, ProcTagId, ParamsTagId, ParamTagId, ResultTagId, ClobberTagId, VarTagId, ArchTagId, CfvarTagId, RodataTagId, GvarTagId, TvarTagId, ImpTagId, ExtprocTagId, SyprocTagId, RegsTagId}

type
  NifasmExpr* = enum
    NoExpr
    AlignX = (ord(AlignTagId), "align")  ## stack-slot alignment annotation (child of `(s)`)
    SsizeX = (ord(SsizeTagId), "ssize")  ## stack size expression
    CsizeX = (ord(CsizeTagId), "csize")  ## call stack size expression
    ArgX = (ord(ArgTagId), "arg")  ## argument reference in prepare block
    ResX = (ord(ResTagId), "res")  ## result reference in prepare block
    DotX = (ord(DotTagId), "dot")  ## field access
    AtX = (ord(AtTagId), "at")  ## array index
    MemX = (ord(MemTagId), "mem")  ## memory reference
    CastX = (ord(CastTagId), "cast")  ## type cast
    RelocX = (ord(RelocTagId), "reloc")  ## rodata relocation: bake symbol S's address at byte offset O

proc rawTagIsNifasmExpr*(raw: TagEnum): bool {.inline.} =
  raw in {AlignTagId, SsizeTagId, CsizeTagId, ArgTagId, ResTagId, DotTagId, AtTagId, MemTagId, CastTagId, RelocTagId}

type
  X64Flag* = enum
    NoFlag
    SO = (ord(STagId), "s")  ## stack slot location tag
    OfO = (ord(OfTagId), "of")  ## overflow flag
    NoO = (ord(NoTagId), "no")  ## no overflow flag
    ZfO = (ord(ZfTagId), "zf")  ## zero flag
    NzO = (ord(NzTagId), "nz")  ## not zero flag
    SfO = (ord(SfTagId), "sf")  ## sign flag
    NsO = (ord(NsTagId), "ns")  ## not sign flag
    CfO = (ord(CfTagId), "cf")  ## carry flag
    NcO = (ord(NcTagId), "nc")  ## not carry flag
    PfO = (ord(PfTagId), "pf")  ## parity flag
    NpO = (ord(NpTagId), "np")  ## not parity flag

proc rawTagIsX64Flag*(raw: TagEnum): bool {.inline.} =
  raw in {STagId, OfTagId, NoTagId, ZfTagId, NzTagId, SfTagId, NsTagId, CfTagId, NcTagId, PfTagId, NpTagId}

type
  X64Reg* = enum
    NoReg
    RaxR = (ord(RaxTagId), "rax")  ## register rax
    RbxR = (ord(RbxTagId), "rbx")  ## register rbx
    RcxR = (ord(RcxTagId), "rcx")  ## register rcx
    RdxR = (ord(RdxTagId), "rdx")  ## register rdx
    RsiR = (ord(RsiTagId), "rsi")  ## register rsi
    RdiR = (ord(RdiTagId), "rdi")  ## register rdi
    RbpR = (ord(RbpTagId), "rbp")  ## register rbp
    RspR = (ord(RspTagId), "rsp")  ## register rsp
    R8R = (ord(R8TagId), "r8")  ## register r8
    R9R = (ord(R9TagId), "r9")  ## register r9
    R10R = (ord(R10TagId), "r10")  ## register r10
    R11R = (ord(R11TagId), "r11")  ## register r11
    R12R = (ord(R12TagId), "r12")  ## register r12
    R13R = (ord(R13TagId), "r13")  ## register r13
    R14R = (ord(R14TagId), "r14")  ## register r14
    R15R = (ord(R15TagId), "r15")  ## register r15
    R0R = (ord(R0TagId), "r0")  ## register r0 (alias)
    R1R = (ord(R1TagId), "r1")  ## register r1 (alias)
    R2R = (ord(R2TagId), "r2")  ## register r2 (alias)
    R3R = (ord(R3TagId), "r3")  ## register r3 (alias)
    R4R = (ord(R4TagId), "r4")  ## register r4 (alias)
    R5R = (ord(R5TagId), "r5")  ## register r5 (alias)
    R6R = (ord(R6TagId), "r6")  ## register r6 (alias)
    R7R = (ord(R7TagId), "r7")  ## register r7 (alias)
    Xmm0R = (ord(Xmm0TagId), "xmm0")  ## register xmm0
    Xmm1R = (ord(Xmm1TagId), "xmm1")  ## register xmm1
    Xmm2R = (ord(Xmm2TagId), "xmm2")  ## register xmm2
    Xmm3R = (ord(Xmm3TagId), "xmm3")  ## register xmm3
    Xmm4R = (ord(Xmm4TagId), "xmm4")  ## register xmm4
    Xmm5R = (ord(Xmm5TagId), "xmm5")  ## register xmm5
    Xmm6R = (ord(Xmm6TagId), "xmm6")  ## register xmm6
    Xmm7R = (ord(Xmm7TagId), "xmm7")  ## register xmm7
    Xmm8R = (ord(Xmm8TagId), "xmm8")  ## register xmm8
    Xmm9R = (ord(Xmm9TagId), "xmm9")  ## register xmm9
    Xmm10R = (ord(Xmm10TagId), "xmm10")  ## register xmm10
    Xmm11R = (ord(Xmm11TagId), "xmm11")  ## register xmm11
    Xmm12R = (ord(Xmm12TagId), "xmm12")  ## register xmm12
    Xmm13R = (ord(Xmm13TagId), "xmm13")  ## register xmm13
    Xmm14R = (ord(Xmm14TagId), "xmm14")  ## register xmm14
    Xmm15R = (ord(Xmm15TagId), "xmm15")  ## register xmm15

proc rawTagIsX64Reg*(raw: TagEnum): bool {.inline.} =
  raw >= RaxTagId and raw <= Xmm15TagId

type
  A64Reg* = enum
    NoReg
    X0R = (ord(X0TagId), "x0")  ## register x0
    X1R = (ord(X1TagId), "x1")  ## register x1
    X2R = (ord(X2TagId), "x2")  ## register x2
    X3R = (ord(X3TagId), "x3")  ## register x3
    X4R = (ord(X4TagId), "x4")  ## register x4
    X5R = (ord(X5TagId), "x5")  ## register x5
    X6R = (ord(X6TagId), "x6")  ## register x6
    X7R = (ord(X7TagId), "x7")  ## register x7
    X8R = (ord(X8TagId), "x8")  ## register x8
    X9R = (ord(X9TagId), "x9")  ## register x9
    X10R = (ord(X10TagId), "x10")  ## register x10
    X11R = (ord(X11TagId), "x11")  ## register x11
    X12R = (ord(X12TagId), "x12")  ## register x12
    X13R = (ord(X13TagId), "x13")  ## register x13
    X14R = (ord(X14TagId), "x14")  ## register x14
    X15R = (ord(X15TagId), "x15")  ## register x15
    X16R = (ord(X16TagId), "x16")  ## register x16
    X17R = (ord(X17TagId), "x17")  ## register x17
    X18R = (ord(X18TagId), "x18")  ## register x18
    X19R = (ord(X19TagId), "x19")  ## register x19
    X20R = (ord(X20TagId), "x20")  ## register x20
    X21R = (ord(X21TagId), "x21")  ## register x21
    X22R = (ord(X22TagId), "x22")  ## register x22
    X23R = (ord(X23TagId), "x23")  ## register x23
    X24R = (ord(X24TagId), "x24")  ## register x24
    X25R = (ord(X25TagId), "x25")  ## register x25
    X26R = (ord(X26TagId), "x26")  ## register x26
    X27R = (ord(X27TagId), "x27")  ## register x27
    X28R = (ord(X28TagId), "x28")  ## register x28
    X29R = (ord(X29TagId), "x29")  ## register x29
    X30R = (ord(X30TagId), "x30")  ## register x30
    SpR = (ord(SpTagId), "sp")  ## stack pointer
    W0R = (ord(W0TagId), "w0")  ## register w0 (32-bit)
    W1R = (ord(W1TagId), "w1")  ## register w1 (32-bit)
    W2R = (ord(W2TagId), "w2")  ## register w2 (32-bit)
    W3R = (ord(W3TagId), "w3")  ## register w3 (32-bit)
    W4R = (ord(W4TagId), "w4")  ## register w4 (32-bit)
    W5R = (ord(W5TagId), "w5")  ## register w5 (32-bit)
    W6R = (ord(W6TagId), "w6")  ## register w6 (32-bit)
    W7R = (ord(W7TagId), "w7")  ## register w7 (32-bit)
    W8R = (ord(W8TagId), "w8")  ## register w8 (32-bit)
    W9R = (ord(W9TagId), "w9")  ## register w9 (32-bit)
    W10R = (ord(W10TagId), "w10")  ## register w10 (32-bit)
    W11R = (ord(W11TagId), "w11")  ## register w11 (32-bit)
    W12R = (ord(W12TagId), "w12")  ## register w12 (32-bit)
    W13R = (ord(W13TagId), "w13")  ## register w13 (32-bit)
    W14R = (ord(W14TagId), "w14")  ## register w14 (32-bit)
    W15R = (ord(W15TagId), "w15")  ## register w15 (32-bit)
    W16R = (ord(W16TagId), "w16")  ## register w16 (32-bit)
    W17R = (ord(W17TagId), "w17")  ## register w17 (32-bit)
    W18R = (ord(W18TagId), "w18")  ## register w18 (32-bit)
    W19R = (ord(W19TagId), "w19")  ## register w19 (32-bit)
    W20R = (ord(W20TagId), "w20")  ## register w20 (32-bit)
    W21R = (ord(W21TagId), "w21")  ## register w21 (32-bit)
    W22R = (ord(W22TagId), "w22")  ## register w22 (32-bit)
    W23R = (ord(W23TagId), "w23")  ## register w23 (32-bit)
    W24R = (ord(W24TagId), "w24")  ## register w24 (32-bit)
    W25R = (ord(W25TagId), "w25")  ## register w25 (32-bit)
    W26R = (ord(W26TagId), "w26")  ## register w26 (32-bit)
    W27R = (ord(W27TagId), "w27")  ## register w27 (32-bit)
    W28R = (ord(W28TagId), "w28")  ## register w28 (32-bit)
    W29R = (ord(W29TagId), "w29")  ## register w29 (32-bit)
    W30R = (ord(W30TagId), "w30")  ## register w30 (32-bit)
    WspR = (ord(WspTagId), "wsp")  ## stack pointer (32-bit)
    LrR = (ord(LrTagId), "lr")  ## link register (alias for x30)
    FpR = (ord(FpTagId), "fp")  ## frame pointer (alias for x29)
    XzrR = (ord(XzrTagId), "xzr")  ## zero register
    D0R = (ord(D0TagId), "d0")  ## fp register d0
    D1R = (ord(D1TagId), "d1")  ## fp register d1
    D2R = (ord(D2TagId), "d2")  ## fp register d2
    D3R = (ord(D3TagId), "d3")  ## fp register d3
    D4R = (ord(D4TagId), "d4")  ## fp register d4
    D5R = (ord(D5TagId), "d5")  ## fp register d5
    D6R = (ord(D6TagId), "d6")  ## fp register d6
    D7R = (ord(D7TagId), "d7")  ## fp register d7
    D8R = (ord(D8TagId), "d8")  ## fp register d8
    D9R = (ord(D9TagId), "d9")  ## fp register d9
    D10R = (ord(D10TagId), "d10")  ## fp register d10
    D11R = (ord(D11TagId), "d11")  ## fp register d11
    D12R = (ord(D12TagId), "d12")  ## fp register d12
    D13R = (ord(D13TagId), "d13")  ## fp register d13
    D14R = (ord(D14TagId), "d14")  ## fp register d14
    D15R = (ord(D15TagId), "d15")  ## fp register d15
    D16R = (ord(D16TagId), "d16")  ## fp register d16
    D17R = (ord(D17TagId), "d17")  ## fp register d17
    D18R = (ord(D18TagId), "d18")  ## fp register d18
    D19R = (ord(D19TagId), "d19")  ## fp register d19
    D20R = (ord(D20TagId), "d20")  ## fp register d20
    D21R = (ord(D21TagId), "d21")  ## fp register d21
    D22R = (ord(D22TagId), "d22")  ## fp register d22
    D23R = (ord(D23TagId), "d23")  ## fp register d23
    D24R = (ord(D24TagId), "d24")  ## fp register d24
    D25R = (ord(D25TagId), "d25")  ## fp register d25
    D26R = (ord(D26TagId), "d26")  ## fp register d26
    D27R = (ord(D27TagId), "d27")  ## fp register d27
    D28R = (ord(D28TagId), "d28")  ## fp register d28
    D29R = (ord(D29TagId), "d29")  ## fp register d29
    D30R = (ord(D30TagId), "d30")  ## fp register d30
    D31R = (ord(D31TagId), "d31")  ## fp register d31
    S0R = (ord(S0TagId), "s0")  ## fp register s0
    S1R = (ord(S1TagId), "s1")  ## fp register s1
    S2R = (ord(S2TagId), "s2")  ## fp register s2
    S3R = (ord(S3TagId), "s3")  ## fp register s3
    S4R = (ord(S4TagId), "s4")  ## fp register s4
    S5R = (ord(S5TagId), "s5")  ## fp register s5
    S6R = (ord(S6TagId), "s6")  ## fp register s6
    S7R = (ord(S7TagId), "s7")  ## fp register s7
    S8R = (ord(S8TagId), "s8")  ## fp register s8
    S9R = (ord(S9TagId), "s9")  ## fp register s9
    S10R = (ord(S10TagId), "s10")  ## fp register s10
    S11R = (ord(S11TagId), "s11")  ## fp register s11
    S12R = (ord(S12TagId), "s12")  ## fp register s12
    S13R = (ord(S13TagId), "s13")  ## fp register s13
    S14R = (ord(S14TagId), "s14")  ## fp register s14
    S15R = (ord(S15TagId), "s15")  ## fp register s15
    S16R = (ord(S16TagId), "s16")  ## fp register s16
    S17R = (ord(S17TagId), "s17")  ## fp register s17
    S18R = (ord(S18TagId), "s18")  ## fp register s18
    S19R = (ord(S19TagId), "s19")  ## fp register s19
    S20R = (ord(S20TagId), "s20")  ## fp register s20
    S21R = (ord(S21TagId), "s21")  ## fp register s21
    S22R = (ord(S22TagId), "s22")  ## fp register s22
    S23R = (ord(S23TagId), "s23")  ## fp register s23
    S24R = (ord(S24TagId), "s24")  ## fp register s24
    S25R = (ord(S25TagId), "s25")  ## fp register s25
    S26R = (ord(S26TagId), "s26")  ## fp register s26
    S27R = (ord(S27TagId), "s27")  ## fp register s27
    S28R = (ord(S28TagId), "s28")  ## fp register s28
    S29R = (ord(S29TagId), "s29")  ## fp register s29
    S30R = (ord(S30TagId), "s30")  ## fp register s30
    S31R = (ord(S31TagId), "s31")  ## fp register s31

proc rawTagIsA64Reg*(raw: TagEnum): bool {.inline.} =
  raw in {X0TagId, X1TagId, X2TagId, X3TagId, X4TagId, X5TagId, X6TagId, X7TagId, X8TagId, X9TagId, X10TagId, X11TagId, X12TagId, X13TagId, X14TagId, X15TagId, X16TagId, X17TagId, X18TagId, X19TagId, X20TagId, X21TagId, X22TagId, X23TagId, X24TagId, X25TagId, X26TagId, X27TagId, X28TagId, X29TagId, X30TagId, SpTagId, W0TagId, W1TagId, W2TagId, W3TagId, W4TagId, W5TagId, W6TagId, W7TagId, W8TagId, W9TagId, W10TagId, W11TagId, W12TagId, W13TagId, W14TagId, W15TagId, W16TagId, W17TagId, W18TagId, W19TagId, W20TagId, W21TagId, W22TagId, W23TagId, W24TagId, W25TagId, W26TagId, W27TagId, W28TagId, W29TagId, W30TagId, WspTagId, LrTagId, FpTagId, XzrTagId, D0TagId, D1TagId, D2TagId, D3TagId, D4TagId, D5TagId, D6TagId, D7TagId, D8TagId, D9TagId, D10TagId, D11TagId, D12TagId, D13TagId, D14TagId, D15TagId, D16TagId, D17TagId, D18TagId, D19TagId, D20TagId, D21TagId, D22TagId, D23TagId, D24TagId, D25TagId, D26TagId, D27TagId, D28TagId, D29TagId, D30TagId, D31TagId, S0TagId, S1TagId, S2TagId, S3TagId, S4TagId, S5TagId, S6TagId, S7TagId, S8TagId, S9TagId, S10TagId, S11TagId, S12TagId, S13TagId, S14TagId, S15TagId, S16TagId, S17TagId, S18TagId, S19TagId, S20TagId, S21TagId, S22TagId, S23TagId, S24TagId, S25TagId, S26TagId, S27TagId, S28TagId, S29TagId, S30TagId, S31TagId}

