# Generated by tools/gen_tags.nim from doc/instructions.md. DO NOT EDIT!

import instructions

type
  X64Inst* = enum
    NoX64Inst
    MovX64 = (ord(MovTagId), "mov")  ## move instruction
    LeaX64 = (ord(LeaTagId), "lea")  ## load effective address
    MovapdX64 = (ord(MovapdTagId), "movapd")  ## move aligned packed double
    MovsdX64 = (ord(MovsdTagId), "movsd")  ## move scalar double
    AddX64 = (ord(AddTagId), "add")  ## add instruction
    SubX64 = (ord(SubTagId), "sub")  ## subtract instruction
    MulX64 = (ord(MulTagId), "mul")  ## unsigned multiply
    ImulX64 = (ord(ImulTagId), "imul")  ## signed multiply
    DivX64 = (ord(DivTagId), "div")  ## unsigned divide
    IdivX64 = (ord(IdivTagId), "idiv")  ## signed divide
    AddsdX64 = (ord(AddsdTagId), "addsd")  ## add scalar double
    SubsdX64 = (ord(SubsdTagId), "subsd")  ## subtract scalar double
    MulsdX64 = (ord(MulsdTagId), "mulsd")  ## multiply scalar double
    DivsdX64 = (ord(DivsdTagId), "divsd")  ## divide scalar double
    AndX64 = (ord(AndTagId), "and")  ## bitwise and
    OrX64 = (ord(OrTagId), "or")  ## bitwise or
    XorX64 = (ord(XorTagId), "xor")  ## bitwise xor
    ShlX64 = (ord(ShlTagId), "shl")  ## shift left
    ShrX64 = (ord(ShrTagId), "shr")  ## shift right
    SalX64 = (ord(SalTagId), "sal")  ## shift arithmetic left
    SarX64 = (ord(SarTagId), "sar")  ## shift arithmetic right
    IncX64 = (ord(IncTagId), "inc")  ## increment
    DecX64 = (ord(DecTagId), "dec")  ## decrement
    NegX64 = (ord(NegTagId), "neg")  ## negate
    NotX64 = (ord(NotTagId), "not")  ## bitwise not
    CmpX64 = (ord(CmpTagId), "cmp")  ## compare
    TestX64 = (ord(TestTagId), "test")  ## test
    SeteX64 = (ord(SeteTagId), "sete")  ## set byte if equal
    SetzX64 = (ord(SetzTagId), "setz")  ## set byte if zero
    SetneX64 = (ord(SetneTagId), "setne")  ## set byte if not equal
    SetnzX64 = (ord(SetnzTagId), "setnz")  ## set byte if not zero
    SetaX64 = (ord(SetaTagId), "seta")  ## set byte if above
    SetnbeX64 = (ord(SetnbeTagId), "setnbe")  ## set byte if not below or equal
    SetaeX64 = (ord(SetaeTagId), "setae")  ## set byte if above or equal
    SetnbX64 = (ord(SetnbTagId), "setnb")  ## set byte if not below
    SetncX64 = (ord(SetncTagId), "setnc")  ## set byte if not carry
    SetbX64 = (ord(SetbTagId), "setb")  ## set byte if below
    SetnaeX64 = (ord(SetnaeTagId), "setnae")  ## set byte if not above or equal
    SetcX64 = (ord(SetcTagId), "setc")  ## set byte if carry
    SetbeX64 = (ord(SetbeTagId), "setbe")  ## set byte if below or equal
    SetnaX64 = (ord(SetnaTagId), "setna")  ## set byte if not above
    SetgX64 = (ord(SetgTagId), "setg")  ## set byte if greater
    SetnleX64 = (ord(SetnleTagId), "setnle")  ## set byte if not less or equal
    SetgeX64 = (ord(SetgeTagId), "setge")  ## set byte if greater or equal
    SetnlX64 = (ord(SetnlTagId), "setnl")  ## set byte if not less
    SetlX64 = (ord(SetlTagId), "setl")  ## set byte if less
    SetngeX64 = (ord(SetngeTagId), "setnge")  ## set byte if not greater or equal
    SetleX64 = (ord(SetleTagId), "setle")  ## set byte if less or equal
    SetngX64 = (ord(SetngTagId), "setng")  ## set byte if not greater
    SetoX64 = (ord(SetoTagId), "seto")  ## set byte if overflow
    SetsX64 = (ord(SetsTagId), "sets")  ## set byte if sign
    SetpX64 = (ord(SetpTagId), "setp")  ## set byte if parity
    CmoveX64 = (ord(CmoveTagId), "cmove")  ## conditional move if equal
    CmovzX64 = (ord(CmovzTagId), "cmovz")  ## conditional move if zero
    CmovneX64 = (ord(CmovneTagId), "cmovne")  ## conditional move if not equal
    CmovnzX64 = (ord(CmovnzTagId), "cmovnz")  ## conditional move if not zero
    CmovaX64 = (ord(CmovaTagId), "cmova")  ## conditional move if above
    CmovnbeX64 = (ord(CmovnbeTagId), "cmovnbe")  ## conditional move if not below or equal
    CmovaeX64 = (ord(CmovaeTagId), "cmovae")  ## conditional move if above or equal
    CmovnbX64 = (ord(CmovnbTagId), "cmovnb")  ## conditional move if not below
    CmovncX64 = (ord(CmovncTagId), "cmovnc")  ## conditional move if not carry
    CmovbX64 = (ord(CmovbTagId), "cmovb")  ## conditional move if below
    CmovnaeX64 = (ord(CmovnaeTagId), "cmovnae")  ## conditional move if not above or equal
    CmovcX64 = (ord(CmovcTagId), "cmovc")  ## conditional move if carry
    CmovbeX64 = (ord(CmovbeTagId), "cmovbe")  ## conditional move if below or equal
    CmovnaX64 = (ord(CmovnaTagId), "cmovna")  ## conditional move if not above
    CmovgX64 = (ord(CmovgTagId), "cmovg")  ## conditional move if greater
    CmovnleX64 = (ord(CmovnleTagId), "cmovnle")  ## conditional move if not less or equal
    CmovgeX64 = (ord(CmovgeTagId), "cmovge")  ## conditional move if greater or equal
    CmovnlX64 = (ord(CmovnlTagId), "cmovnl")  ## conditional move if not less
    CmovlX64 = (ord(CmovlTagId), "cmovl")  ## conditional move if less
    CmovngeX64 = (ord(CmovngeTagId), "cmovnge")  ## conditional move if not greater or equal
    CmovleX64 = (ord(CmovleTagId), "cmovle")  ## conditional move if less or equal
    CmovngX64 = (ord(CmovngTagId), "cmovng")  ## conditional move if not greater
    CmovoX64 = (ord(CmovoTagId), "cmovo")  ## conditional move if overflow
    CmovnoX64 = (ord(CmovnoTagId), "cmovno")  ## conditional move if not overflow
    CmovsX64 = (ord(CmovsTagId), "cmovs")  ## conditional move if sign
    CmovnsX64 = (ord(CmovnsTagId), "cmovns")  ## conditional move if not sign
    CmovpX64 = (ord(CmovpTagId), "cmovp")  ## conditional move if parity
    CmovnpX64 = (ord(CmovnpTagId), "cmovnp")  ## conditional move if not parity
    CmovpeX64 = (ord(CmovpeTagId), "cmovpe")  ## conditional move if parity even (alias for p)
    CmovpoX64 = (ord(CmovpoTagId), "cmovpo")  ## conditional move if parity odd (alias for np)
    JmpX64 = (ord(JmpTagId), "jmp")  ## unconditional jump
    JeX64 = (ord(JeTagId), "je")  ## jump if equal
    JzX64 = (ord(JzTagId), "jz")  ## jump if zero
    JneX64 = (ord(JneTagId), "jne")  ## jump if not equal
    JnzX64 = (ord(JnzTagId), "jnz")  ## jump if not zero
    JgX64 = (ord(JgTagId), "jg")  ## jump if greater
    JngX64 = (ord(JngTagId), "jng")  ## jump if not greater
    JgeX64 = (ord(JgeTagId), "jge")  ## jump if greater or equal
    JngeX64 = (ord(JngeTagId), "jnge")  ## jump if not greater or equal
    JaX64 = (ord(JaTagId), "ja")  ## jump if above
    JnaX64 = (ord(JnaTagId), "jna")  ## jump if not above
    JaeX64 = (ord(JaeTagId), "jae")  ## jump if above or equal
    JnaeX64 = (ord(JnaeTagId), "jnae")  ## jump if not above or equal
    JlX64 = (ord(JlTagId), "jl")  ## jump if less
    JleX64 = (ord(JleTagId), "jle")  ## jump if less or equal
    JbX64 = (ord(JbTagId), "jb")  ## jump if below
    JbeX64 = (ord(JbeTagId), "jbe")  ## jump if below or equal
    CallX64 = (ord(CallTagId), "call")  ## function call
    IatX64 = (ord(IatTagId), "iat")  ## indirect call through IAT (Import Address Table)
    RetX64 = (ord(RetTagId), "ret")  ## return instruction
    PushX64 = (ord(PushTagId), "push")  ## push to stack
    PopX64 = (ord(PopTagId), "pop")  ## pop from stack
    NopX64 = (ord(NopTagId), "nop")  ## no operation
    SyscallX64 = (ord(SyscallTagId), "syscall")  ## system call
    LabX64 = (ord(LabTagId), "lab")  ## label definition
    IteX64 = (ord(IteTagId), "ite")  ## if-then-else structure
    LoopX64 = (ord(LoopTagId), "loop")  ## loop structure
    StmtsX64 = (ord(StmtsTagId), "stmts")  ## statement block
    JtrueX64 = (ord(JtrueTagId), "jtrue")  ## set control flow variable(s) to true
    KillX64 = (ord(KillTagId), "kill")  ## kill variable
    LockX64 = (ord(LockTagId), "lock")  ## atomic lock prefix
    XchgX64 = (ord(XchgTagId), "xchg")  ## atomic exchange
    CmpxchgX64 = (ord(CmpxchgTagId), "cmpxchg")  ## atomic compare and exchange
    XaddX64 = (ord(XaddTagId), "xadd")  ## atomic exchange and add
    Cmpxchg8bX64 = (ord(Cmpxchg8bTagId), "cmpxchg8b")  ## atomic compare and exchange 8 bytes
    MfenceX64 = (ord(MfenceTagId), "mfence")  ## memory fence
    SfenceX64 = (ord(SfenceTagId), "sfence")  ## store fence
    LfenceX64 = (ord(LfenceTagId), "lfence")  ## load fence
    PauseX64 = (ord(PauseTagId), "pause")  ## pause
    ClflushX64 = (ord(ClflushTagId), "clflush")  ## cache line flush
    ClflushoptX64 = (ord(ClflushoptTagId), "clflushopt")  ## optimized cache line flush
    Prefetcht0X64 = (ord(Prefetcht0TagId), "prefetcht0")  ## prefetch t0
    Prefetcht1X64 = (ord(Prefetcht1TagId), "prefetcht1")  ## prefetch t1
    Prefetcht2X64 = (ord(Prefetcht2TagId), "prefetcht2")  ## prefetch t2
    PrefetchntaX64 = (ord(PrefetchntaTagId), "prefetchnta")  ## prefetch non-temporal

proc rawTagIsX64Inst*(raw: TagEnum): bool {.inline.} =
  raw in {MovTagId, LeaTagId, MovapdTagId, MovsdTagId, AddTagId, SubTagId, MulTagId, ImulTagId, DivTagId, IdivTagId, AddsdTagId, SubsdTagId, MulsdTagId, DivsdTagId, AndTagId, OrTagId, XorTagId, ShlTagId, ShrTagId, SalTagId, SarTagId, IncTagId, DecTagId, NegTagId, NotTagId, CmpTagId, TestTagId, SeteTagId, SetzTagId, SetneTagId, SetnzTagId, SetaTagId, SetnbeTagId, SetaeTagId, SetnbTagId, SetncTagId, SetbTagId, SetnaeTagId, SetcTagId, SetbeTagId, SetnaTagId, SetgTagId, SetnleTagId, SetgeTagId, SetnlTagId, SetlTagId, SetngeTagId, SetleTagId, SetngTagId, SetoTagId, SetsTagId, SetpTagId, CmoveTagId, CmovzTagId, CmovneTagId, CmovnzTagId, CmovaTagId, CmovnbeTagId, CmovaeTagId, CmovnbTagId, CmovncTagId, CmovbTagId, CmovnaeTagId, CmovcTagId, CmovbeTagId, CmovnaTagId, CmovgTagId, CmovnleTagId, CmovgeTagId, CmovnlTagId, CmovlTagId, CmovngeTagId, CmovleTagId, CmovngTagId, CmovoTagId, CmovnoTagId, CmovsTagId, CmovnsTagId, CmovpTagId, CmovnpTagId, CmovpeTagId, CmovpoTagId, JmpTagId, JeTagId, JzTagId, JneTagId, JnzTagId, JgTagId, JngTagId, JgeTagId, JngeTagId, JaTagId, JnaTagId, JaeTagId, JnaeTagId, JlTagId, JleTagId, JbTagId, JbeTagId, CallTagId, IatTagId, RetTagId, PushTagId, PopTagId, NopTagId, SyscallTagId, LabTagId, IteTagId, LoopTagId, StmtsTagId, JtrueTagId, KillTagId, LockTagId, XchgTagId, CmpxchgTagId, XaddTagId, Cmpxchg8bTagId, MfenceTagId, SfenceTagId, LfenceTagId, PauseTagId, ClflushTagId, ClflushoptTagId, Prefetcht0TagId, Prefetcht1TagId, Prefetcht2TagId, PrefetchntaTagId}

type
  A64Inst* = enum
    NoA64Inst
    MovA64 = (ord(MovTagId), "mov")  ## move instruction
    AddA64 = (ord(AddTagId), "add")  ## add instruction
    SubA64 = (ord(SubTagId), "sub")  ## subtract instruction
    MulA64 = (ord(MulTagId), "mul")  ## unsigned multiply
    SdivA64 = (ord(SdivTagId), "sdiv")  ## signed divide
    UdivA64 = (ord(UdivTagId), "udiv")  ## unsigned divide
    AndA64 = (ord(AndTagId), "and")  ## bitwise and
    OrrA64 = (ord(OrrTagId), "orr")  ## bitwise or
    EorA64 = (ord(EorTagId), "eor")  ## bitwise xor
    LslA64 = (ord(LslTagId), "lsl")  ## logical shift left
    LsrA64 = (ord(LsrTagId), "lsr")  ## logical shift right
    AsrA64 = (ord(AsrTagId), "asr")  ## arithmetic shift right
    NegA64 = (ord(NegTagId), "neg")  ## negate
    CmpA64 = (ord(CmpTagId), "cmp")  ## compare
    CallA64 = (ord(CallTagId), "call")  ## function call
    RetA64 = (ord(RetTagId), "ret")  ## return instruction
    NopA64 = (ord(NopTagId), "nop")  ## no operation
    SvcA64 = (ord(SvcTagId), "svc")  ## supervisor call (system call)
    AdrA64 = (ord(AdrTagId), "adr")  ## load address of label
    LdrA64 = (ord(LdrTagId), "ldr")  ## load register
    StrA64 = (ord(StrTagId), "str")  ## store register
    StpA64 = (ord(StpTagId), "stp")  ## store pair
    LdpA64 = (ord(LdpTagId), "ldp")  ## load pair
    BA64 = (ord(BTagId), "b")  ## branch (unconditional jump)
    BlA64 = (ord(BlTagId), "bl")  ## branch with link (function call)
    BeqA64 = (ord(BeqTagId), "beq")  ## branch if equal
    BneA64 = (ord(BneTagId), "bne")  ## branch if not equal
    LabA64 = (ord(LabTagId), "lab")  ## label definition
    IteA64 = (ord(IteTagId), "ite")  ## if-then-else structure
    LoopA64 = (ord(LoopTagId), "loop")  ## loop structure
    StmtsA64 = (ord(StmtsTagId), "stmts")  ## statement block
    JtrueA64 = (ord(JtrueTagId), "jtrue")  ## set control flow variable(s) to true
    KillA64 = (ord(KillTagId), "kill")  ## kill variable

proc rawTagIsA64Inst*(raw: TagEnum): bool {.inline.} =
  raw in {MovTagId, AddTagId, SubTagId, MulTagId, SdivTagId, UdivTagId, AndTagId, OrrTagId, EorTagId, LslTagId, LsrTagId, AsrTagId, NegTagId, CmpTagId, CallTagId, RetTagId, NopTagId, SvcTagId, AdrTagId, LdrTagId, StrTagId, StpTagId, LdpTagId, BTagId, BlTagId, BeqTagId, BneTagId, LabTagId, IteTagId, LoopTagId, StmtsTagId, JtrueTagId, KillTagId}

type
  NifasmType* = enum
    NoType
    BoolT = (ord(BoolTagId), "bool")  ## boolean type
    IT = (ord(ITagId), "i")  ## signed integer type of N bits
    UT = (ord(UTagId), "u")  ## unsigned integer type of N bits
    FT = (ord(FTagId), "f")  ## float type of N bits
    PtrT = (ord(PtrTagId), "ptr")  ## pointer to single element
    AptrT = (ord(AptrTagId), "aptr")  ## pointer to array of elements
    ArrayT = (ord(ArrayTagId), "array")  ## array type
    ObjectT = (ord(ObjectTagId), "object")  ## object type definition
    UnionT = (ord(UnionTagId), "union")  ## union type definition
    FldT = (ord(FldTagId), "fld")  ## field definition

proc rawTagIsNifasmType*(raw: TagEnum): bool {.inline.} =
  raw >= BoolTagId and raw <= FldTagId and raw != TagEnum(8)

type
  NifasmDecl* = enum
    NoDecl
    TypeD = (ord(TypeTagId), "type")  ## type declaration
    ProcD = (ord(ProcTagId), "proc")  ## proc declaration
    ParamsD = (ord(ParamsTagId), "params")  ## parameters block
    ParamD = (ord(ParamTagId), "param")  ## parameter declaration
    ResultD = (ord(ResultTagId), "result")  ## result value declaration
    ClobberD = (ord(ClobberTagId), "clobber")  ## clobbered registers list
    VarD = (ord(VarTagId), "var")  ## variable declaration
    ArchD = (ord(ArchTagId), "arch")  ## architecture pragma
    CfvarD = (ord(CfvarTagId), "cfvar")  ## control flow variable declaration
    RodataD = (ord(RodataTagId), "rodata")  ## read-only data (string/bytes)
    GvarD = (ord(GvarTagId), "gvar")  ## global variable
    TvarD = (ord(TvarTagId), "tvar")  ## thread local variable
    ImpD = (ord(ImpTagId), "imp")  ## import dynamic library
    ExtprocD = (ord(ExtprocTagId), "extproc")  ## external proc from imported library

proc rawTagIsNifasmDecl*(raw: TagEnum): bool {.inline.} =
  raw in {TypeTagId, ProcTagId, ParamsTagId, ParamTagId, ResultTagId, ClobberTagId, VarTagId, ArchTagId, CfvarTagId, RodataTagId, GvarTagId, TvarTagId, ImpTagId, ExtprocTagId}

type
  NifasmExpr* = enum
    NoExpr
    SsizeX = (ord(SsizeTagId), "ssize")  ## stack size expression
    DotX = (ord(DotTagId), "dot")  ## field access
    AtX = (ord(AtTagId), "at")  ## array index
    MemX = (ord(MemTagId), "mem")  ## memory reference
    CastX = (ord(CastTagId), "cast")  ## type cast

proc rawTagIsNifasmExpr*(raw: TagEnum): bool {.inline.} =
  raw in {SsizeTagId, DotTagId, AtTagId, MemTagId, CastTagId}

type
  X64Flag* = enum
    NoFlag
    SO = (ord(STagId), "s")  ## stack slot location tag
    OfO = (ord(OfTagId), "of")  ## overflow flag
    NoO = (ord(NoTagId), "no")  ## no overflow flag
    ZfO = (ord(ZfTagId), "zf")  ## zero flag
    NzO = (ord(NzTagId), "nz")  ## not zero flag
    SfO = (ord(SfTagId), "sf")  ## sign flag
    NsO = (ord(NsTagId), "ns")  ## not sign flag
    CfO = (ord(CfTagId), "cf")  ## carry flag
    NcO = (ord(NcTagId), "nc")  ## not carry flag
    PfO = (ord(PfTagId), "pf")  ## parity flag
    NpO = (ord(NpTagId), "np")  ## not parity flag

proc rawTagIsX64Flag*(raw: TagEnum): bool {.inline.} =
  raw in {STagId, OfTagId, NoTagId, ZfTagId, NzTagId, SfTagId, NsTagId, CfTagId, NcTagId, PfTagId, NpTagId}

type
  X64Reg* = enum
    NoReg
    RaxR = (ord(RaxTagId), "rax")  ## register rax
    RbxR = (ord(RbxTagId), "rbx")  ## register rbx
    RcxR = (ord(RcxTagId), "rcx")  ## register rcx
    RdxR = (ord(RdxTagId), "rdx")  ## register rdx
    RsiR = (ord(RsiTagId), "rsi")  ## register rsi
    RdiR = (ord(RdiTagId), "rdi")  ## register rdi
    RbpR = (ord(RbpTagId), "rbp")  ## register rbp
    RspR = (ord(RspTagId), "rsp")  ## register rsp
    R8R = (ord(R8TagId), "r8")  ## register r8
    R9R = (ord(R9TagId), "r9")  ## register r9
    R10R = (ord(R10TagId), "r10")  ## register r10
    R11R = (ord(R11TagId), "r11")  ## register r11
    R12R = (ord(R12TagId), "r12")  ## register r12
    R13R = (ord(R13TagId), "r13")  ## register r13
    R14R = (ord(R14TagId), "r14")  ## register r14
    R15R = (ord(R15TagId), "r15")  ## register r15
    R0R = (ord(R0TagId), "r0")  ## register r0 (alias)
    R1R = (ord(R1TagId), "r1")  ## register r1 (alias)
    R2R = (ord(R2TagId), "r2")  ## register r2 (alias)
    R3R = (ord(R3TagId), "r3")  ## register r3 (alias)
    R4R = (ord(R4TagId), "r4")  ## register r4 (alias)
    R5R = (ord(R5TagId), "r5")  ## register r5 (alias)
    R6R = (ord(R6TagId), "r6")  ## register r6 (alias)
    R7R = (ord(R7TagId), "r7")  ## register r7 (alias)
    Xmm0R = (ord(Xmm0TagId), "xmm0")  ## register xmm0
    Xmm1R = (ord(Xmm1TagId), "xmm1")  ## register xmm1
    Xmm2R = (ord(Xmm2TagId), "xmm2")  ## register xmm2
    Xmm3R = (ord(Xmm3TagId), "xmm3")  ## register xmm3
    Xmm4R = (ord(Xmm4TagId), "xmm4")  ## register xmm4
    Xmm5R = (ord(Xmm5TagId), "xmm5")  ## register xmm5
    Xmm6R = (ord(Xmm6TagId), "xmm6")  ## register xmm6
    Xmm7R = (ord(Xmm7TagId), "xmm7")  ## register xmm7
    Xmm8R = (ord(Xmm8TagId), "xmm8")  ## register xmm8
    Xmm9R = (ord(Xmm9TagId), "xmm9")  ## register xmm9
    Xmm10R = (ord(Xmm10TagId), "xmm10")  ## register xmm10
    Xmm11R = (ord(Xmm11TagId), "xmm11")  ## register xmm11
    Xmm12R = (ord(Xmm12TagId), "xmm12")  ## register xmm12
    Xmm13R = (ord(Xmm13TagId), "xmm13")  ## register xmm13
    Xmm14R = (ord(Xmm14TagId), "xmm14")  ## register xmm14
    Xmm15R = (ord(Xmm15TagId), "xmm15")  ## register xmm15

proc rawTagIsX64Reg*(raw: TagEnum): bool {.inline.} =
  raw >= RaxTagId and raw <= Xmm15TagId

type
  A64Reg* = enum
    NoReg
    X0R = (ord(X0TagId), "x0")  ## register x0
    X1R = (ord(X1TagId), "x1")  ## register x1
    X2R = (ord(X2TagId), "x2")  ## register x2
    X3R = (ord(X3TagId), "x3")  ## register x3
    X4R = (ord(X4TagId), "x4")  ## register x4
    X5R = (ord(X5TagId), "x5")  ## register x5
    X6R = (ord(X6TagId), "x6")  ## register x6
    X7R = (ord(X7TagId), "x7")  ## register x7
    X8R = (ord(X8TagId), "x8")  ## register x8
    X9R = (ord(X9TagId), "x9")  ## register x9
    X10R = (ord(X10TagId), "x10")  ## register x10
    X11R = (ord(X11TagId), "x11")  ## register x11
    X12R = (ord(X12TagId), "x12")  ## register x12
    X13R = (ord(X13TagId), "x13")  ## register x13
    X14R = (ord(X14TagId), "x14")  ## register x14
    X15R = (ord(X15TagId), "x15")  ## register x15
    X16R = (ord(X16TagId), "x16")  ## register x16
    X17R = (ord(X17TagId), "x17")  ## register x17
    X18R = (ord(X18TagId), "x18")  ## register x18
    X19R = (ord(X19TagId), "x19")  ## register x19
    X20R = (ord(X20TagId), "x20")  ## register x20
    X21R = (ord(X21TagId), "x21")  ## register x21
    X22R = (ord(X22TagId), "x22")  ## register x22
    X23R = (ord(X23TagId), "x23")  ## register x23
    X24R = (ord(X24TagId), "x24")  ## register x24
    X25R = (ord(X25TagId), "x25")  ## register x25
    X26R = (ord(X26TagId), "x26")  ## register x26
    X27R = (ord(X27TagId), "x27")  ## register x27
    X28R = (ord(X28TagId), "x28")  ## register x28
    X29R = (ord(X29TagId), "x29")  ## register x29
    X30R = (ord(X30TagId), "x30")  ## register x30
    SpR = (ord(SpTagId), "sp")  ## stack pointer
    W0R = (ord(W0TagId), "w0")  ## register w0 (32-bit)
    W1R = (ord(W1TagId), "w1")  ## register w1 (32-bit)
    W2R = (ord(W2TagId), "w2")  ## register w2 (32-bit)
    W3R = (ord(W3TagId), "w3")  ## register w3 (32-bit)
    W4R = (ord(W4TagId), "w4")  ## register w4 (32-bit)
    W5R = (ord(W5TagId), "w5")  ## register w5 (32-bit)
    W6R = (ord(W6TagId), "w6")  ## register w6 (32-bit)
    W7R = (ord(W7TagId), "w7")  ## register w7 (32-bit)
    W8R = (ord(W8TagId), "w8")  ## register w8 (32-bit)
    W9R = (ord(W9TagId), "w9")  ## register w9 (32-bit)
    W10R = (ord(W10TagId), "w10")  ## register w10 (32-bit)
    W11R = (ord(W11TagId), "w11")  ## register w11 (32-bit)
    W12R = (ord(W12TagId), "w12")  ## register w12 (32-bit)
    W13R = (ord(W13TagId), "w13")  ## register w13 (32-bit)
    W14R = (ord(W14TagId), "w14")  ## register w14 (32-bit)
    W15R = (ord(W15TagId), "w15")  ## register w15 (32-bit)
    W16R = (ord(W16TagId), "w16")  ## register w16 (32-bit)
    W17R = (ord(W17TagId), "w17")  ## register w17 (32-bit)
    W18R = (ord(W18TagId), "w18")  ## register w18 (32-bit)
    W19R = (ord(W19TagId), "w19")  ## register w19 (32-bit)
    W20R = (ord(W20TagId), "w20")  ## register w20 (32-bit)
    W21R = (ord(W21TagId), "w21")  ## register w21 (32-bit)
    W22R = (ord(W22TagId), "w22")  ## register w22 (32-bit)
    W23R = (ord(W23TagId), "w23")  ## register w23 (32-bit)
    W24R = (ord(W24TagId), "w24")  ## register w24 (32-bit)
    W25R = (ord(W25TagId), "w25")  ## register w25 (32-bit)
    W26R = (ord(W26TagId), "w26")  ## register w26 (32-bit)
    W27R = (ord(W27TagId), "w27")  ## register w27 (32-bit)
    W28R = (ord(W28TagId), "w28")  ## register w28 (32-bit)
    W29R = (ord(W29TagId), "w29")  ## register w29 (32-bit)
    W30R = (ord(W30TagId), "w30")  ## register w30 (32-bit)
    WspR = (ord(WspTagId), "wsp")  ## stack pointer (32-bit)
    LrR = (ord(LrTagId), "lr")  ## link register (alias for x30)
    FpR = (ord(FpTagId), "fp")  ## frame pointer (alias for x29)
    XzrR = (ord(XzrTagId), "xzr")  ## zero register

proc rawTagIsA64Reg*(raw: TagEnum): bool {.inline.} =
  raw >= X0TagId and raw <= XzrTagId

