## Generates `src/nifasm/core/tags.nim` (the tag ids) and `src/nifasm/core/model.nim`
## (the per-target enums) from the table in `doc/instructions.md`, which is the
## single source of truth for the asm-NIF vocabulary. Run from the repo root.

import std / [strutils, sets, os]

proc toNimName(s: string; suffix: string): string =
  s[0].toUpperAscii & s.substr(1) & suffix

type
  EnumList = enum
    X64Inst, A64Inst, MInst, NifasmType, NifasmDecl, NifasmExpr, X64Flag, X64Reg,
    A64Reg, MReg

proc toSuffix(e: EnumList): (string, string) =
  case e
  of X64Inst: ("X64", "NoX64Inst")
  of A64Inst: ("A64", "NoA64Inst")
  of MInst: ("M", "NoMInst")
  of NifasmType: ("T", "NoType")
  of NifasmDecl: ("D", "NoDecl")
  of NifasmExpr: ("X", "NoExpr")
  of X64Flag: ("O", "NoFlag")
  of X64Reg: ("R", "NoReg")
  of A64Reg: ("R", "NoReg")
  of MReg: ("MR", "NoMReg")

proc shortcutToEnumList(shortcut: string): EnumList =
  try:
    result = parseEnum[EnumList](shortcut.strip())
  except ValueError:
    quit "unknown enum type: " & shortcut

const
  Header = "# Generated by tools/gen_instructions.nim from $1. DO NOT EDIT!\n"

type
  EnumField = object
    name: string
    tag: string
    value: int
    desc: string
  EnumImpls = array[EnumList, seq[EnumField]]

proc writeClassifier(f: File; e: EnumList; fields: seq[EnumField]) =
  if fields.len == 0:
    # An enum no row references yet — a target whose vocabulary is still being
    # added. Emit a classifier that is simply always false rather than indexing
    # an empty `first`/`last` spelling, which read out of bounds and crashed.
    f.write "\n\nproc rawTagIs" & $e & "*(raw: TagEnum): bool {.inline.} =\n  false\n"
    return
  var first = ""
  var last = ""
  var prev = -1
  var holes: seq[int] = @[]
  for f in fields:
    if first.len == 0: first = f.tag
    last = f.tag
    if prev >= 0 and f.value != prev + 1:
      for h in prev + 1..f.value - 1:
        holes.add h
    prev = f.value
  f.write "\n\nproc rawTagIs" & $e & "*(raw: TagEnum): bool {.inline.} ="
  if holes.len <= 3:
    f.write "\n  raw >= " & toNimName(first, "TagId") & " and raw <= " & toNimName(last, "TagId")
    for h in holes:
      f.write " and raw != TagEnum(" & $h & ")"
    f.write "\n"
  else:
    f.write "\n  raw in {"
    var i = 0
    for field in fields:
      if i > 0: f.write ", "
      f.write toNimName(field.tag, "TagId")
      inc i
    f.write "}\n"

proc writeModel(basename: string; data: EnumImpls; first, last: EnumList; input: string) =
  let f = open(basename, fmWrite)
  f.writeLine Header % input
  f.writeLine "import tags"
  for e in first..last:
    f.write "\ntype"
    f.write "\n  " & $e & "* = enum"
    f.write "\n    " & toSuffix(e)[1]
    for field in data[e]:
      f.write "\n    " & field.name
      f.write " = (ord(" & toNimName(field.tag, "TagId") & "), " & escape(field.tag) & ")"
      if field.desc.len > 0:
        f.write "  ## " & field.desc
    writeClassifier(f, e, data[e])
  f.write "\n"
  f.close()

proc writeTagsFile(output: string; data: seq[(string, int)]; input: string;
                   anonHead = false) =
  ## `anonHead` emits `AnonTagId` at ordinal 1 for the tag with no spelling:
  ## a tree whose head is a SymbolDef rather than a tag (`(:ret.0 (rax) (i 64))`)
  ## interns under the EMPTY name. It has no row in the document — there is
  ## nothing to write there — but it must be SEEDED all the same, or the parser
  ## interns it at whatever id is free, and past 511 that id no longer fits a
  ## token and takes the escape (see nifasm/tagpool.nim). Its ordinal has to be
  ## a real enum member because every decoder here is `cast[TagEnum](tagId)`,
  ## which needs ordinal and id to stay equal.
  let f = open(output, fmWrite)
  f.writeLine Header % input
  f.writeLine "type\n  TagEnum* = enum"
  f.writeLine "    InvalidTagId"
  if anonHead: f.writeLine "    AnonTagId"
  for d in data:
    f.writeLine "    " & toNimName(d[0], "TagId")
  f.writeLine "const"
  f.writeLine "  TagData*: array[TagEnum, (string, int)] = ["
  f.write "    (" & escape("InvalidTagId") & ", 0)"
  if anonHead: f.write ",\n    (" & escape("") & ", 1)"
  for d in data:
    f.write ",\n"
    f.write "    (" & escape(d[0]) & ", " & $d[1] & ")"
  f.writeLine "\n  ]"
  f.close()

proc extractTagName(s: string): string =
  var i = 0
  while i < s.len and s[i] == ' ': inc i
  if i < s.len and s[i] == '`': inc i
  if i < s.len and s[i] == '(': inc i
  if i < s.len and s[i] in IdentStartChars:
    let start = i
    while i < s.len and s[i] in IdentChars:
      inc i
    result = s.substr(start, i - 1)
  else:
    quit "Cannot extract tag name from: " & s

const
  LateEnums = {X64Inst, A64Inst, MInst}
    ## Enums whose SINGLE-target members are numbered LAST (see `genTags`).

proc genTags(inp: File; inputName: string) =
  ## Tag ids are assigned here, and the order matters for one reason: a NIF tag
  ## id is 9 bits in the token, so the first 511 tags cost one token and the
  ## rest cost two (nifcore spells them through the `other` escape, which is why
  ## the pool is not capped at 511 — see `TagPool.escapeTag`).
  ##
  ## So the overflow is placed deliberately rather than left to document order.
  ## A row naming EXACTLY ONE of `X64Inst`/`A64Inst`/`MInst` is one target's
  ## machine mnemonic, and those are numbered last: there are hundreds of them,
  ## each target's are dead weight to every other target, and a mnemonic appears
  ## once per instruction where a register appears two or three times. A row
  ## naming SEVERAL is the cross-target vocabulary (`mov`, `add`, `ret`, `lab`,
  ## `stmts`, `scope`, `ite`, …) and stays with the types, decls and registers up
  ## front.
  ##
  ## Cortex-M reuses the register spellings that already exist rather than
  ## minting its own: `(r0)`..`(r12)` are already there as x86-64 aliases and
  ## `(sp)`/`(lr)` as AArch64 ones, so those rows simply gain `MReg` and no tag
  ## id moves. Which register file `(r0)` names is decided by `(arch …)`, the
  ## same way `(mov …)` already means different encodings per target.
  ##
  ## The practical effect: today only the very tail of the mnemonics overflows,
  ## and adding a target (Cortex-M, RISC-V) can never push a register or a
  ## structural tag over — it only lengthens the tail.
  var tableRow = 0
  var enumDecls = default EnumImpls
  var tags: seq[(string, int)] = @[]
  var knownTags = initHashSet[string]()
  var rows: seq[tuple[tag, desc: string; enums: seq[EnumList]; late: bool]] = @[]
  for line in lines(inp):
    # Anything that is not a table row is prose: the document is read by humans
    # too, so a heading or a paragraph above the table must not be a parse error.
    if not line.strip().startsWith("|"): continue
    inc tableRow
    if tableRow <= 2: continue # the table's header row and its `|---|` separator
    var parts = line.split("|")
    if parts.len < 5:
      quit "WRONG LINE: " & line
    let tagName = extractTagName parts[1]
    if knownTags.containsOrIncl(tagName):
      quit "DUPLICATE TAG: " & tagName

    let desc = parts[3].strip()
    var affectedEnums: seq[EnumList] = @[]
    if parts[2].strip() != "-":            # `-` = a tag that belongs to no enum
      for a in parts[2].split(","):
        affectedEnums.add shortcutToEnumList(a)
      assert affectedEnums.len > 0
    rows.add (tagName, desc, affectedEnums,
              affectedEnums.len == 1 and affectedEnums[0] in LateEnums)

  var ordered: seq[int] = @[]
  for late in [false, true]:
    for idx in 0 ..< rows.len:
      if rows[idx].late == late: ordered.add idx
  # Id 1 belongs to the anonymous tree head; see `writeTagsFile`'s `anonHead`.
  var id = 1
  for idx in ordered:
    inc id
    let r = rows[idx]
    tags.add (r.tag, id)
    for e in r.enums:
      enumDecls[e].add EnumField(
        name: toNimName(r.tag, toSuffix(e)[0]),
        tag: r.tag,
        value: id,
        desc: r.desc
      )

  createDir "src/nifasm/core"
  writeTagsFile "src/nifasm/core/tags.nim", tags, inputName, anonHead = true
  writeModel "src/nifasm/core/model.nim", enumDecls, X64Inst, MReg, inputName

proc main(inputName: string) =
  var inp = open(inputName, fmRead)
  genTags(inp, inputName)
  inp.close()

let inputName = if os.paramCount() == 0: "doc/instructions.md" else: os.paramStr(1)
  ## The vocabulary table. Only `doc/instructions.md` exists; the parameter is
  ## there so it can be given by an absolute path.

main(inputName)

